### ISSUE TITLE
Zoom: Option to retain zoom-level when changing between Images

### ISSUE THREAD

**Issue by Aligorith** [woelper/oculante#100]
**Description:**
It would be nice to be able to retain the zoom level when changing between images, instead of having it automatically zoom out / try to fit the entire image to the window size.

**Use Case / Rationale:**
I often need to switch between multiple images in a sequence (e.g. frames of an animation, or slices of geometry for 3D Printing), carefully checking how the pixels in a particular area change over the sequence. Being able to set the viewport to focus on a particular region of interest, and then change between those using the arrow keys therefore becomes important.

**Interactive Example:**
For an example of this behaviour in action, see my fork of Emulsion (https://github.com/Aligorith/emulsion)

**Comment by woelper** [comment]
Thanks for the request!
This is of course not very hard to do, as the only thing needed is to skip resetting the view.
How do you want this to work? As a setting or an entirely new command which you can bind to a key?
Where should the setting be in the UI and should it persist between restarts?

**Comment by Aligorith** [comment]
It would best as a setting instead of a needing to introduce a set of separate commands. Probably having it persist across sessions would be good, so you don't have to keep remembering to turn it on, if you're jumping between folders.

As for where it should go, that's a bit trickier. Perhaps the settings popup would be ok, since the toolbar is a bit crowded (and it could get easily confused with the fullscreen / always on top buttons)?

(Speaking of the toolbar, I was initially a bit confused with the Info/Edit toggles, particularly why they had the separate checkboxes beside them, as I thought the checkboxes were icons for something else)

**Comment by woelper** [comment]
This is now added and will be part of the next release. I'll leave this open until I improved the info/edit toggles.

**Comment by Aligorith** [comment]
Cool thanks! That's great to hear

**Comment by woelper** [comment]
info/edit toggles should now be less confusing.
