### ISSUE TITLE
Enhancement: Improved File/Folder Opening Options

### ISSUE THREAD

**Issue by Aligorith** [woelper/oculante#101]
**Description:**
Currently, the options available for how to select a file / folder to open are a bit restrictive and/or buggy.

What works:
* Dragging an image onto an open instance
* Providing a path to a specific image as an argument to the program
  * **BUG:** If you provide the path of a folder instead though, it fails to load anything, and just sits there showing the loading message + the spinner icon
* Use left/right arrows (buttons on toolbar, or keyboard) to change between images within a folder

Additional methods that would be nice to have:
* Ctrl-O / F1 - Open a file browse dialog, that lets you select a folder from the file system to use
* Passing a folder will open the first file found, instead of hanging
* Using Ctrl-Scrollwheel can also be used to change between images
* Have an option to display a horizontal panel/bar across the bottom of the UI, where clicking / click-dragging anywhere in there will jump to another image in the folder. It should also have an indicator of where the current image sits within the folder.

Other minor issues noticed:
* The filenames should really be sorted using "[Natural Sorting](https://en.wikipedia.org/wiki/Natural_sort_order)", instead of the "character string" sorting that standard libraries typically give us. (e.g. Instead of getting something like `"slice_1", "slice_10", "slice_100", "slice_101", ..., "slice_11", ..., "slice_2", ...`, you get `"slice_1", "slice_2", ..., "slice_10", "slice_11", ..., "slice_100", "slice_101", ...` as expected)

**Example Implementations:**
Over last year's Christmas/New Year period, I ended up hacking support for a bunch of these into Emulsion (i.e. see [my fork with these features](https://github.com/Aligorith/emulsion)).

Back then, it was the closest to what I wanted from a lightweight image viewer. However, architectural issues ended up making it hard to move beyond those simple tweaks to trying to make it use egui for supporting many of the things you've added here (e.g. EXIF display + pixel-color sampling support). It now looks like it may be easier to try to bring over those customisations to this codebase instead / as well, giving me another image viewer option.

I'll see what I can do. If I get some of these working, I'll probably send a pull-request implementing those. Otherwise, hopefully some of these wishlist items show up in a future release :)

**Comment by woelper** [comment]
All these are great points. Thank you for taking the time to write this up, and I am happy that this viewer comes already close to what you are looking for. I will take a look at your fork and start seeing what I can do. Please don't hesitate to open other tickets in the meantime!

**Comment by Aligorith** [comment]
I've just submitted a Pull Request (#104) for implementing an initial implementation of these features. Probably some code style tweaks / cleanup of todo comments / etc. is needed

---

There are still a few items here that are not covered by the PR. I may end up looking into these later / as part of a separate PR, since it looks like they need more (invasive) infrastructure work to happen. Specifically, these are:
* Add a slider-bar (or similar) across the bottom of the UI, for jumping between images in the folder.
* Showing the current index of the file within the folder, along with the number of viewable images - e.g. something like "[12 / 1000]"

It seems like both of these look like they'd require at least keeping track of the current index and total number of viewable images in the folder, and perhaps even caching the list of images found in the folder (since we currently have to recalculate that every time we try to load the next/prev images).

Something else that may be worth considering is trying to prefetch / cache images, to reduce the loading time when switching between images.

**Comment by woelper** [comment]
Haha, I just saw the latest comment from you and realized I basically said something similar in the PR comment. Glad we are aligned! I had some very minor comments, thanks for the PR!

**Comment by woelper** [comment]
Caching is now implemented and will be in the next release (https://github.com/woelper/oculante/pull/114)

**Comment by woelper** [comment]
I will be looking at this (https://github.com/mitchmindtree/egui_timeline) and bind this to a generic Vec holding the image paths. We can then step/scrub through it, maybe indicate if images are cached and use the same Vec for prev/next and the slider.

**Comment by woelper** [comment]
Stepping through the timeline is now quite satisfying:
https://user-images.githubusercontent.com/3613791/210647481-14eb6249-7c1b-450d-8dfa-0de56c466da3.mp4

For now it's just an ugly slider, I'll see if I can make it more pretty. Since this may be useful for playing sequences, maybe even play/pause could be nice, together with a frame rate selector..

**Comment by woelper** [comment]
This is all done and will be in the next release. To make building easier on other platforms, opening files via a system browser dialog has been put behind a feature flag, but it is still enabled by default.
