### ISSUE TITLE
Key order is random in keybinding settings

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#111]
The keybinding settings doesn't seem to preserve any kind of order for the keys — for every knew app instance you get a new order — making them a challenge to find

Ideally, commands should be grouped by the similarity of function:
  - all `PanX` commands are together as well as
  - `RedChannel` and `GreenChannel` are close together even though they're not alphabetically close

(but even alphabetical sorting by command is better than a purely random order)

**Comment by woelper** [comment]
Thanks. This is now fixed and will be in the next release.
