### ISSUE TITLE
Allow remembering window's size/position on app's restart

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#120]
Would be great for these parameters not to reset (at least with an option to remember previous window's size/position)

**Comment by woelper** [comment]
This is done. The position is _not_ remembered as I am scared this may run into problematic scenarios with external monitors/changing resolutions. The size is saved though.

**Comment by eugenesvk** [comment]
Thank you! Is there any chance to hide it behind an option for the more common single monitor/fixed resolution setup? For some workflows (like having the window take 40% of the screen adjacent to the border so you can have some other app for comparison or something) it'd be rather beneficial not to use a window manager on restart

**Comment by woelper** [comment]
That could be an option. It is a bit more difficult then setting the size as this apparently must happen after window creation, so this takes more time for me to solve.

**Comment by eugenesvk** [comment]
Ok, understood, thanks
