### ISSUE TITLE
Mac: allow setting LSUIPresentationMode in Info.plist and alternate fullscreen

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#121]
You have a fullscreen mode, but on a Mac it suffers from an annoying flaw ('s fault, not your app's): there is some animation delay when you switch between a fullscreen app and any other regular app, and it can't be eliminated (accessibility settings only reduce it a bit)
But there is an alternative: you can add to your app's `Info.plist` set `<key>LSUIPresentationMode</key><integer>3</integer>` ([apple's source](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/TP40009250-113616-TPXREF134)), and this would achieve a similar goal: the sytem's menu is hidden, the bottom's Dock is hidden as well, and they stay hidden, just like in a fullscreen mode, but without any switching delays!

There are a few issues with that, though:
  - if I manually edit the `Info.plist` file, it's reset on every app update
  - the is no in-app way to maximize the window's size
  - (tracked here https://github.com/woelper/oculante/issues/120) window's size/position is reset on startup
  - (tracked here https://github.com/woelper/oculante/issues/43) titlebar is not hidden

Would it be possible to add an config that would write this setting to `info.plist` so that it's not reset on app updates?
And maybe add a keybind for an "alternative fullscreen" mode that would enlarge the window to the size of the whole screen (including the system's top menu)?

**Comment by woelper** [comment]
Would it be bad to add `<key>LSUIPresentationMode</key><integer>3</integer>` as default in Info.plist?

Not sure if I can enlarge the window over the system's top menu...

**Comment by woelper** [comment]
I went ahead and added the proposed changes to the plist - it probably won't hurt I guess!

**Comment by eugenesvk** [comment]
> Would it be bad to add `<key>LSUIPresentationMode</key><integer>3</integer>` as default in Info.plist?

Hm, I think this might be too strong of an opinion for an app as system menu is a kind of a fixture on a Mac (I don't know apps that use this trick)?
Maybe you could read this `Info.plist` file from a users's config folder and if it exists, add the keys it has to the native plist? Then a user could simply add this one key if he wants to, and it won't be overwritten on updates (and also if you change any defaults, add new keys, the user will get them)?

> Not sure if I can enlarge the window over the system's top menu

Well, the menu is not there anymore, so, e.g., if I drag the topmost resize border I can resize to the top of my screen, so hopefully it might be a simple "make the app's window the size of the screen"? command, just not a "fullscreen" command that entails entering a special mode

**Comment by woelper** [comment]
Closing this since the key is now in the plist.

**Comment by eugenesvk** [comment]
But the second point remains (maximizing window size without going fullscreen), and is not tracked anywhere else

**Comment by woelper** [comment]
Maybe I don't understand, but can't you do that usually through the native window for enlarging it fully? I don't think I can cover the system menu on mac without entering fullscreen.

**Comment by eugenesvk** [comment]
> Maybe I don't understand, but can't you do that usually through the native window for enlarging it fully?

Definitely not with a single <kbd>F</kbd> key! I can only resize via the top bar border, so via the worst method of window management

> I don't think I can cover the system menu on mac without entering fullscreen.

Maybe, or maybe not since there is no system menu anymore, so you're not covering it, but not sure what level of window control Apple allows here. Would it be possible to expose window's size/position behind some keybind, then I could check if passing different size/position values can move the window to the true 0,0 position when the system menu is invisible?

**Comment by eugenesvk** [comment]
Meanwhile, I've found a way to maximize to cover the hidden menubar — BetterTouchTool allows that via saving/restoring a window profile (though curiously enough, not via maximizing a window) — so it's definitely possible to command a window to take the full screen size

(though this doesn't work right after launch of oculante, you need to <kbd>⌥</kbd><kbd>↹</kbd> once, but that's an OS bug since I can't manually move the window to that black line right away either)
