### ISSUE TITLE
Quitting while file picker is opened hangs the app

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#122]
(on a Mac)
- ⌘O to open the file picker
- ⌘Q to quit the app
- the app hangs (the file picker is active unless you pick a file, then it becomes unresponsive as well)

**Comment by woelper** [comment]
This should be fixed now as the file dialog is threaded. The last place left could be the save dialog.

**Comment by woelper** [comment]
Closing as I've also addressed the save option. Feel free to reopen if this happens again!
