### ISSUE TITLE
Metadata gone on png rotation (XMP, ICC profile, EXIF)

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#127]
Original PNG (screenshot with a few bits of EXIF, XMP, ICC metadata)
<img width="43" alt="oc" src="https://user-images.githubusercontent.com/12956286/211208542-2a323ac3-4e0e-49b8-a57b-d24b562e1c38.png">

PNG rotated in Oculante
![oc_rotate](https://user-images.githubusercontent.com/12956286/211208538-3d1c9e6a-5409-432e-a29b-d27891ecbb2c.png)

Note that all XMP, ICC profile, EXIF metadata is gone

This might be due to the fact that the PNG lib oculante uses forgot to update to the "newer" PNG spec that supports metadata?
(from this [SO answer](https://stackoverflow.com/questions/9542359/does-png-contain-exif-data-like-jpg) EXIF is part of the PNG spec since 2017 (Version 1.5.0 (July 2017) of the Extensions to the PNG 1.2 Specification)

**Comment by woelper** [comment]
All images end up as a generic image buffer when loaded, without any extra data - so this is expected. I would have to find a way to preserve this in a generic way to re-apply when saving. 
On top of that, `image` does not easily support this (https://github.com/image-rs/image/issues/1045) so I doubt this would be easy.

**Comment by woelper** [comment]
I have been thinking about this, and since oculante supports _loading_ of metadata and stores it in memory, it could _write_ that upon saving, even if the underlying library does not do that by default. I'll try to prototype something for a small set (maybe png/jpeg first) and see how that works. I'd probably check for metadata being present and write it after saving to the file.

**Comment by woelper** [comment]
I've made a branch for this (linked) which seems promising. It's a bit brutal since it's a post-process, but it completely preserves EXIF, even if you save from jpeg to png or tiff.

**Comment by woelper** [comment]
Metadata should now be preserved as-is when saving.
