### ISSUE TITLE
Best visual comparison of 2 images: pin size/zoom setting per image

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#129]
Below is an approximation of a relatively common workflow of comparing quality of the same "source" represented in images of different "view" (size/position)

Let's say you have this original
<img width="43" alt="oc" src="https://user-images.githubusercontent.com/12956286/211209236-b21669eb-a983-48b5-92dd-7e84959df9c4.png">

And then you've made some edits to it, specifically, cropped 50% from the right, 25% from the top, 25% from the bottom
![oc_50r 25t 25b](https://user-images.githubusercontent.com/12956286/211209238-56ca29a0-44d6-478a-b29e-f5818da5fd93.png)

Now you'd like to check the quality of your edits vs. the original
Since the best way to spot differences in images is:
  - align them spatially (and since one picture is a sub-picture, it's possible to achieve the perfect alignment) and then
  - flip back&forth
 
one common way to do that is open two instances of some imaging app, carefully align the pictures to match on the physical screen and then press the shortcut to switch only between two apps

Another alternative is this feature request: allow to "pin" an image's position/zoom level, for example
  - set `oc`'s zoom it 8 times, don't move it, `pin` (so if you switch to another image, change something there and switch back, you'll still be at 8×zoom and centered pic)
  - set `oc_50r 25t 25b`'s 8×zoom, move ↓×5, `pin` (so if you switch to another image, change something there and switch back, you'll still be at 8×zoom and a pic moved ↓×5)

Now these pictures are perfectly aligned (in this case they're still a few pixels off, so you'd need a few more pixel-precision pans, but let's assume they are) and you just need to quickly hit Next/Previous (or set up a shortcut that would flip between pinned images) to immediately see any difference, the zoom/position won't be reset to the "last" level like it currently happens with `Do not reset image view`

**Comment by woelper** [comment]
This is a nice idea. I've used tools which let you swipe interactively between different images to compare, and doing so is valuable. Also storing/loading the offset if of course possible - oculante could even remember the position of any image loaded in a session, so you could align and then go back and forth. Maybe this could be another option, like "store image offsets"?

**Comment by woelper** [comment]
Or, since you mentioned edits, would you like this explicitly to happen between an unmodified image and the edited one?

**Comment by eugenesvk** [comment]
> position of any image loaded in a session, so you could align and then go back and forth.

My original idea was for this to only happen between "pinned" images since it may so happen that these images are not adjacent, so you can't easily flip back&forth between just the two images: this is common when you have, say, 5 slightly different edits, but want to limit the comparison, usually you'd just add `1`, `2` to the filenames to make the two pics you want to compare to be sorted together; so pinning works as an tiny covenience boost to renaming

> Maybe this could be another option, like "store image offsets"?

But this is also an interesting idea to make quick comparison across many files easier

> Or, since you mentioned edits, would you like this explicitly to happen between an unmodified image and the edited one?

So if instead of 'overwriting' the file under a new name `oc_50r 25t 25b` like in my example above, the edits would just be in the  regular `.oculante` sidecar, and then I could flip between the edited and the original, but while preserving each image's size/position? Yeah, that would be very neat

**Comment by woelper** [comment]
I have been thinking about this recently. I think I should first unify position data for an image (right now, there is scaling and offset) into one attribute. Next I think we could make a "Compare window" or something like that, which points to images with position data attached. Clicking an image would load it with the exact position that you saved, enabling you to quickly compare multiple images with stored positions. Would this be useful?

**Comment by eugenesvk** [comment]
So would the workflow be like this?:
  - in your main window, you browse images and invoke `pin` command on some of them
  - then you invoke the `Compare pinned` command
  - this opens the `Compare window` that would work just like the regular window, but switching would only be between the images you've pinned before
  - you can unpin images in the `Compare window` or pin more in the main window

**Comment by woelper** [comment]
> So would the workflow be like this?:
> 
> * in your main window, you browse images and invoke `pin` command on some of them

Yes. They'd be added to a "compare list" and their position is saved

> * then you invoke the `Compare pinned` command

I think I'd make a list of pinned images and you can switch between them.

> * this opens the `Compare window` that would work just like the regular window, but switching would only be between the images you've pinned before

I'd probably (at least at first) just use the main window. No "overlay" of compared images, but switching between images quickly that you want to compare.

> * you can unpin images in the `Compare window` or pin more in the main window

That sounds about right!

**Comment by eugenesvk** [comment]
> I'd probably (at least at first) just use the main window. No "overlay" of compared images, but switching between images quickly that you want to compare.

So that would be like entering the "compare mode" or a Virtual folder with a smaller set of images you can switch between?

>> you can unpin images in the Compare window or pin more in the main window

>That sounds about right!

since both are in the same window, you'd only be able to add/remove by switching modes, right?

**Comment by eugenesvk** [comment]
> You'd only see one image at a time and can toggle between them. You could add/remove any image that has a path at all times

but the list of items you can toggle between is different, so you can't pin `pic3` if you've switched to a mode that only has `pic1` and `pic2` previously pinned (so the floating menu would show 2 items), you have to switch back to the regular mode, browse to `pic3`, pin it, then switch to the comparison mode, then you'd be able to switch between 3 images (the floating menu now shows 3 items)
That assumes that the commands for switching is the same and the mode constrains the total list of elements to pick from (regular mode - folder, comparison mode - list of pinned files)

Unless I'm missing something in your interface

**Comment by eugenesvk** [comment]
What UI do you use to reorder/remove? Do you have to switch to the floating "recent files" window for that?
Same for add: where do you get the new image from? Do you have to switch back away from the floating window to pin images from the main window?
And how do you switch between them? Would you need to switch to the floating window and then your prev/next keys would switch between items within that floating list?

**Comment by woelper** [comment]
Yeah, it ended up not being a floating window since I figured I could reuse what I have.

Sorry for giving you such a rough version, but I just wanted to get some feedback and see how it feels.

I will address your points later. Is it important for you to toggle this with the info panel closed?

**Comment by eugenesvk** [comment]
Would be nice to be able to do everything without an extra info panel click, although the most important part is being able to switch images without the info panel to avoid any distraction

**Comment by woelper** [comment]
I did not have much time to work on this, but you can now switch images without the info panel. It's bound do SHIFT+C, but you can of course change that. You have to edit the images to compare in the info panel though, there is no hotkey for it. Hope this helps!

**Comment by woelper** [comment]
I'll close this, feel free to open a new issue with requests for improvements. This might be a very specialized feature anyways, so maybe it is usable in the current state.
