### ISSUE TITLE
Edits not restored when switching files

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#131]
I've edited a picture, got my results
<img width="460" alt="oc_edit1" src="https://user-images.githubusercontent.com/12956286/211283898-28b1a36d-2a25-4040-a2b0-dc16bea9f87b.png">

pressed `Save edits`, switched to another image and then back, and the edits are gone (the filter remaining in the editor panel is misleading, it stays for all the other images as well, so it doesn't indicate that the settings were restored for this ppicture):
<img width="460" alt="oc_edit" src="https://user-images.githubusercontent.com/12956286/211283287-1a316c24-2680-4f83-825f-a0717a886bd5.png">

When I close oculante and open just this picture alone, then the edits are restored (both the edit panel is show with the proper edit, and the edits are applied to a picture)

this is `oc.oculante`
```
{"painting":false,"non_destructive_painting":false,"paint_strokes":[],"paint_fade":false,"pixel_op_stack":[{"Desaturate":100}],"image_op_stack":[],"export_extension":"png"}
```

**Comment by woelper** [comment]
Indeed. You have enabled "Do not reset image view" and image edits are only loaded when an image resets. I will move this somewhere else.
