### ISSUE TITLE
Option to store .oculante edits in image metadata?

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#132]
I'm rather partial to 'non-destructive' editing, but at the same time not a fan of having to carry around sidecars.
Do you think it'd be possible to add an option to instead store the same `.oculante` edit information (or a more compact representation thereof) in some `oculante` EXIF tag (or whatever the appropriate metadata tag exists for an image type)?

**Comment by woelper** [comment]
I don't think that every file format has metadata. I don't think this is very realistic because of that and would require lots of individual work per format. Non-destructive editing is completely optional, and you can choose to just commit the edits to the file and not save the metafile.
If you dislike metafiles, maybe this info could be shared centrally. But you would lose the ability to give someone a file with edit information this way.

**Comment by woelper** [comment]
I think this is a good example of something which increases complexity. I always try to find simple solutions, as this allows me to add and change things later, which is fundamentally more fun. The more complex something becomes, the less likely change is going to happen.

Even if there was a library perfectly handling metadata transparently for all formats, there would still be some images which don't support metadata. This would mean that there would now be two ways to read metadata.

Next, someone want the old way back and be able to choose if the edits go into a sidecar file or into metadata - which is perfectly reasonable.
For this, we'd maybe make this an option in settings, giving the control to the user. Now some user toggles this off and on, having a mixture of settings both embedded in the file AND in the sidecar file. Now this would have to be merged, or the newest would always be loaded, requiring a prompt or error message...

Apart from that, these edits are subject to change, and might grow in complexity. Maybe I want to have masks or brushes in there, or color lookup tables. This may not be compatible with all the limitation metadata offers.

**Comment by eugenesvk** [comment]
> This may not be compatible with all the limitation metadata offers

Unfortunately, metadata is a complete mess despite so many standards developed over so many years :(
So yeah, if you think you'll extend beyond the limitations it's not worth it investing much effort into trying to fit in this mess.
(I just thought that since some nondestructive editors do store edits in etadata that it might be ok-ish)

> Now some user toggles this off and on, having a mixture of settings both embedded in the file AND in the sidecar file.

For a single user+machine that could be solved by allowing only one way, so if you have a sidecar, change the setting to embed, then the sidecar data gets transferred and the sidecar file is removed; and vice versa: embedded edit info is deleted after being moved to a sidecar
But in general the proper sync is indeed too tricky to solve, though that could maybe be the price of flexibility?

> there would still be some images which don't support metadata. 

These designers' disgraces should just die :), the sooner, the better! But they refuse to...

**Comment by woelper** [comment]
I am cleaning up some tickets, and I think I'll close this one (of course no offense :) ) as this seems like something that is not super realistic as there is no common metadata across all image formats - although I liked the idea.
