### ISSUE TITLE
Switching to an image with .oculante file always increases the width of the edit panel

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#133]
↓ video switches back and forth between files, watch how the edit panel always increases on every switch to a file with edits preloaded

https://user-images.githubusercontent.com/12956286/211510399-29e62497-d8f9-49b7-8062-edd5ec1519cd.mov

**Comment by woelper** [comment]
I think this is fixed since I switched to a different font. At least I could not reproduce this any more. Do you still see this with the latest version?
