### ISSUE TITLE
Stop moving further picture if it's already fully offscreen

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#137]
I've noticed that if you hold the movement key and the picture moves offscreen and becomes invisible, it keeps moving, but there is no reason for it to, it just makes it harder to return it back to the visible area

Instead, once the picture (red below) leaves the viewport (green), it should not be possible to move it further in the **same direction** (moving in other directions is fine)
<img width="120" alt="mmap" src="https://user-images.githubusercontent.com/12956286/215158912-6ae1553c-c1ec-4edf-894c-85988ddf3170.png">

(not sure what information is available in oculante, but in the script for the screenshot above, the check is:
  - if we're moving ↑ and
  - the vertical margin ↑ (from the bottom of the window to the bottom of the image) >= visible screen height
  - => then the ↑ movement is ignored

**Comment by woelper** [comment]
Good point. I can maybe just stop scrolling if the offset is larger than the image dimensions, accounting for scale of course.
