### ISSUE TITLE
Provide a "fit to screen" keybinding

### ISSUE THREAD

**Issue by Shnatsel** [woelper/oculante#14]
Right now Oculante defaults to showing the images in their actual size, even if they don't fit in the window. This makes it nearly unusable for viewing photos, which are far larger than the typically screen sizes. Allowing to shrink the image if it exceeds the viewport size would be great.

**Comment by woelper** [comment]
Could you try if the `v` key does what you expect?

Would you like the "fit to screen" behavior to be default when opening images?

**Comment by Shnatsel** [comment]
`v` key seems to fit the image on the screen in just one dimension; i.e. it makes it so that the entire screen is filled, but not so I can see the entire image at once.

Yes, I'd expect this mode to be the default, and a keybinding to be provided for 1:1 view. This is usually mapped to the `1` key.

**Comment by woelper** [comment]
Fixed in 0.5.6.
Image is now fit into view based on the largest dimension as default. `1` maps to 1:1 as suggested.

**Comment by Shnatsel** [comment]
When I'm trying to run the new release, I'm getting the following error:

`/oculante_linux: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./oculante_linux)`

Looks like the binary is built with a newer glibc than I have installed. I'm on Ubuntu 18.04. Did you change the build server to a newer version of your Linux distro?

**Comment by woelper** [comment]
Hmm, I did not change anything. It's possible the github action now runs on a newer system. I'll check that out!

**Comment by woelper** [comment]
@Shnatsel Could you please try https://github.com/woelper/oculante/releases/tag/0.5.7 ? I pinned the CI job to use 18.04.

**Comment by Shnatsel** [comment]
Works now. Thanks!
