### ISSUE TITLE
crates.io version stuck on 0.6.46

### ISSUE THREAD

**Issue by 0323pin** [woelper/oculante#141]
Just in case you haven't noticed it,

![2023-02-12-183634_1366x768_scrot](https://user-images.githubusercontent.com/90570748/218327603-76ab8d1f-61bb-4f7e-9999-c8a686b82c6f.png)

**Comment by woelper** [comment]
Thanks so much. When I went back and forth with release testing on CI, I disabled crates.io upload in my release script - and of course forgot to re-enable it again. Fixed now, cheers!

**Comment by 0323pin** [comment]
@woelper Had to build `gtk3` from source as my version was lagging behind but, merged now http://mail-index.netbsd.org/pkgsrc-changes/2023/02/13/msg269399.html
