### ISSUE TITLE
Adding Gray/RGBA/HSV value thresholding and inpainting

### ISSUE THREAD

**Issue by B-LechCode** [woelper/oculante#147]

**Comment by woelper** [comment]
Could you please elaborate what you mean by this?

**Comment by B-LechCode** [comment]
Yes, in grayscale images it's the most simple approach.
You apply an threshold t to the gray values g(x,y) of your image.
If for example g(x,y) >= t applies, you paint that pixel with a previously defined color. If not, you keep the gray value.

In HSV or RGB(a) you would pick a channel and do the same as above. There are 3 different thresholding operations which come to my mind:
g(x,y) >= t 
g(x,y) <= t 
t1 <= g(x,y) <= t2

**Comment by B-LechCode** [comment]
Sorry for not answering for a long period of time: is there a little overview for the statements usable for Expressions?
I tried it today for some multiplications, it is really slow (Image was 16384x1024 tough). What about implementing it with 4 separate LUTS, one for each channel? 
My other PR uses a LUT;  Thresholding and Expression could use that mechanism, too.

**Comment by woelper** [comment]
First of all, thank you for your PR!!

I have investigated a bit in different directions, and I have also not updated this thread. I've started to experiment with shaders, but unfortunately I was not able to compile them at runtime, which makes that approach very inflexible. This may change in the future though.

I've also added LUT support (Hald CLUT) - (more [here](https://im.snibgo.com/edithald.htm)) I don't  know if that helps with your particular case.

Also there is now a gradient map filter which maps pixel values into a user-defined gradient.

**Comment by B-LechCode** [comment]
You're welcome :)
For simple thresholding and for the min/max scaling of my PR, the LUTs are generated dynamically in a simple loop. The CLUT would be overkill, I've seen them in the code, but haven't understood them yet. But for expressions, they may be a good idea :)

**Comment by woelper** [comment]
I think this can be closed now.
