### ISSUE TITLE
Folder specific ".oculante"-File

### ISSUE THREAD

**Issue by B-LechCode** [woelper/oculante#151]
In preparation for https://github.com/woelper/oculante/issues/148, I implemented the option to read a .oculante-File in a directory, which is applied for every image. In my implementation it just has to have the name ".occulante". File specific files have priority over this file.

I this beneficial? If yes, I would bring up a PR.

**Comment by woelper** [comment]
I wasn't sure about this as it increases complexity, but I think I can see the use. Would you like a separate button / toggle for storing edits "globally" (per folder) or per file or how does the user select whether they are editing the file or global edits?

**Comment by B-LechCode** [comment]
Currently I didn't add it to the GUI. I had just saved a normal settings file and renamed it afterwards. 
Maybe just two seperate buttons: image/folder?

**Comment by woelper** [comment]
This has been added now, together with a basic UI.
