### ISSUE TITLE
Large images load into a blackscreen windows

### ISSUE THREAD

**Issue by Quackdoc** [woelper/oculante#152]
Tested v0.6.52 and commit https://github.com/woelper/oculante/commit/8ccc89b

When loading large images oculante simply shows a black screen, am able to replicate the issue using the following publically availible image, the resolution in question for this image is 23164x18480

https://dolphin-emu.org/m/user/blog/progress-report/2016-november/windwaker35xnative.jpg

only tested on windows compiled via mingw64

**Comment by woelper** [comment]
Thanks! This could maybe exceed the maximum texture size. I'll take a look and see if I can reproduce it!

**Comment by woelper** [comment]
This is strange. Opening does not fail, and it does not seem to be an issue of the texture size. All I am doing now in the jpg section is:

```rust
let jpeg_data = std::fs::read(img_location)?;
let img: RgbaImage = turbojpeg::decompress_image(&jpeg_data)?;
img.save("test.png");
```
The resulting "test.png" is also not correct as it does appear to be completely transparent. I am unsure if the size is the issue here or something else.

**Comment by Quackdoc** [comment]
I have also tried using png, and it causes the same issue so it's not related to jpegturbo. using this patch for loading the jpeg, and test it, I still get a black screen, however when getting the png output this works perfectly fine. it is ofcourse large and **very slow** to load, however the resulting PNG is perfectly fine. I also tried simply converting the image using image-rs and it seems to work fine. I tested with and without the conversion to rgba8

I wonder if there is a common error point thats being run into? below is the link to the resulting png
```patch
--- a/src/utils.rs
+++ b/src/utils.rs
@@ -934,8 +934,13 @@ pub fn open_image(img_location: &PathBuf) -> Result<FrameCollection> {
             col.add_still(img);
         }
         _ => {
-            let img = image::open(&img_location)?;
-            col.add_still(img.to_rgba8());
+            let file = File::open(&img_location)?;
+            let bufread = BufReader::new(file);
+            let mut reader = image::io::Reader::new(bufread).with_guessed_format()?;
+            reader.no_limits();
+            //col.add_still(reader.decode()?.into_rgba8());
+            let img = reader.decode()?.into_rgba8();
+            img.save("test.png").unwrap();
         }
     }

```

https://i.slow.pics/l4kLHavS.png

**Comment by Quackdoc** [comment]
it seems that drawing on the image then saving the image, the edits are actually saved fine (still using image instead of jpegturbo)

![image](https://user-images.githubusercontent.com/74831516/223328131-5cafa61e-b318-4172-b601-fc4f71e087be.png)

**Comment by woelper** [comment]
Yes, this was actually something I wanted to try, so thank you for that! `image` allows setting/removing limits, which apparently helps in this case. I have not found a similar option in `turbojpeg`, so I guess we should probably open an issue there?

**Comment by Quackdoc** [comment]
I think this might be an upstream notan issue, I made a demo using their example and the result is indeed a black screen. and if you change the background from black to blue you can certainly see that the result is it being transparent. smaller jpgs work fine with this example

```rust
use notan::draw::*;
use notan::prelude::*;

#[derive(AppState)]
struct State {
    img: Texture,
}

#[notan_main]
fn main() -> Result<(), String> {
    notan::init_with(init)
        .add_config(DrawConfig)
        .draw(draw)
        .build()
}

fn init(gfx: &mut Graphics) -> State {
    let texture = gfx
        .create_texture()
        .from_image(include_bytes!("assets/wind.jpg"))
        .build()
        .unwrap();
    State { img: texture }
}

fn draw(gfx: &mut Graphics, state: &mut State) {
    let mut draw = gfx.create_draw();
    draw.clear(Color::BLACK);
    draw.image(&state.img).position(250.0, 200.0);
    gfx.render(&draw);
}
```
and using the following patch to make it load 
```diff
diff --git a/crates/notan_glow/src/texture_source.rs b/crates/notan_glow/src/texture_source.rs
index c2b8180..0c5ca5f 100644
--- a/crates/notan_glow/src/texture_source.rs
+++ b/crates/notan_glow/src/texture_source.rs
@@ -2,6 +2,7 @@ use crate::texture::{create_texture, TextureKey};
 use crate::GlowBackend;
 use notan_graphics::color::Color;
 use notan_graphics::{TextureFormat, TextureInfo};
+use std::io::Cursor;

 pub(crate) fn add_empty_texture(
     backend: &mut GlowBackend,
@@ -17,7 +18,14 @@ pub(crate) fn add_texture_from_image(
     buffer: Vec<u8>,
     mut info: TextureInfo,
 ) -> Result<(u64, TextureInfo), String> {
-    let img = image::load_from_memory(&buffer).map_err(|e| e.to_string())?;
+
+    //let img = image::load_from_memory(&buffer).map_err(|e| e.to_string())?;
+    let mut reader = image::io::Reader::new(Cursor::new(&buffer));
+    reader.no_limits();
+    let imgo = reader.with_guessed_format().unwrap();
+    let img = imgo.decode().unwrap();
+    //code here
```

**Comment by Quackdoc** [comment]
I can report this or leave it up to you, matters not to me

**Comment by woelper** [comment]
Wow. Amazing job on finding that out! I'll add the issue there and reference your findings here, thanks!

**Comment by Quackdoc** [comment]
ah, I think you misunderstood. this doesn't fix the black screen, but rather is needed to get the image to open in the first place for testing purposes. my bad for being misleading.

**Comment by Quackdoc** [comment]
@woelper seems like it is a texture size limitation not sure how the best way to handle this, but off the top of my head, loading the image into multiple textures then tiling them might be the best solution

**Comment by woelper** [comment]
Thanks so much!

As soon as I get back the info from notan if the creation has failed (or I detect if we are over limits) we can either create multiple textures or do something else, such as resizing within limits. I like the tiling approach though, but I guess that would require some rewriting.

**Comment by woelper** [comment]
I have made a workaround which will be released in the next version. This queries your hardware texture limits, and, when exceeded, resizes the image to fit within them. This is not great as this loses information, but providing a proper, multi-texture approach might take very long.
