### ISSUE TITLE
support preview luminance

### ISSUE THREAD

**Issue by netpyoung** [woelper/oculante#156]
Thank you for making this one.

It will be good to have support preview luminance.
moreover good to support writing custom image filter.

**Comment by woelper** [comment]
Hi! Thanks for your suggestions!
> It will be good to have support preview luminance.

Do you mean this as a filter, as in "displaying image luminance" or is there a specific luminance image format you are referring to?

> moreover good to support writing custom image filter.

Can you elaborate on this? Oculante already as an expression filter that lets you enter any expression per pixel (like `r = b * 0.5` or `r=0.0; b=0.0; a*=0.1;`

If you are thinking of something else let me know!

**Comment by netpyoung** [comment]
Oh Thank you I found option what i want (desaturate: 100). I didn't notice there is filter option.

And I found expression option. It little bit slow when I turn on in my windows machine but work well.

It will be good to game programmer if support to matrix operation per pixel or per group of pixels.

and Save/Load filters.

## example

- per pixel matrix example

``` hlsl
half3x3 sepiaVals = half3x3
(
    0.393, 0.349, 0.272,    // Red
    0.769, 0.686, 0.534,    // Green
    0.189, 0.168, 0.131     // Blue
);

half3 sepiaResult = mul(tex.rgb, sepiaVals);
```

- per group of pixels example

``` dummy
identity_mat_3x3 =
 [[0, 0, 0]
  [0, 1, 0]
  [0, 0, 0]]

origin_image * identity_mat_3x3 => origin_image

sharpen_mat_3x3 =
 [[0, -1, 0]
  [-1, 5, -1]
  [0, -1, 0]]
origin_image * sharpen_mat_3x3 => sharpen_image
```

## Ref

- Luminance
  - https://github.com/Unity-Technologies/FPSSample/blob/6b8b27aca3690de9e46ca3fe5780af4f0eff5faa/Packages/com.unity.postprocessing/PostProcessing/Shaders/Colors.hlsl#L228
- Kernel
  - https://en.wikipedia.org/wiki/Kernel_(image_processing)
- sepia filter
  - https://danielilett.com/2019-05-01-tut1-1-smo-greyscale/
  - https://learn.microsoft.com/en-us/archive/msdn-magazine/2005/january/net-matters-sepia-tone-stringlogicalcomparer-and-more
- sharpen
  - https://datahacker.rs/004-how-to-smooth-and-sharpen-an-image-in-opencv/

**Comment by woelper** [comment]
Nice! Thanks for all the background information!

Yes, expressions are somewhat slower than other operators, mainly because of evaluating a script per pixel. If it helps you can resize your image to be very small, then tweak your expression quickly, then delete the resize operator.

As for your other ideas, I believe the best way would be to support proper pixel shaders. It is probably not super hard with the framework being used (notan) as long as it can dynamically compile shaders. This would offer the biggest flexibility and performance.

**Comment by netpyoung** [comment]
That's cool if this application support shaders.
okay I will recall this issue when It support shaders.
