### ISSUE TITLE
Add oculante package to AUR

### ISSUE THREAD

**Issue by Adhalianna** [woelper/oculante#162]
The motivation is similar to what was mentioned here in issue #93  but besides auto-updates managed by the package manager having oculante available in AUR would make it simpler for me to have it set-up automatically with other packages I consider core on my system (I just pipe the list of packages to pacman, the package manager, when I am starting with a fresh installation). There's also a chance more people would find out about oculante by searching for packages on AUR. 

I cannot promise help with this issue but if I find some spare time I will probably add some relevant resources here in the comments section.

**Comment by woelper** [comment]
Thanks, and I am grateful for the feedback.
I am all up for building a package, but I think I need some support and instructions as I have not used arch/AUR. Is anyone allowed to add new packages there?

**Comment by woelper** [comment]
There seems to be a cargo subcommand facilitating this. Could you try out this PKGBUILD please?
https://github.com/woelper/oculante/blob/master/PKGBUILD

**Comment by woelper** [comment]
@Adhalianna I am happy to realease the package to AUR once you test and we figure out the best way this should be installed according to cumminity guidelines.

**Comment by Adhalianna** [comment]
> @Adhalianna I am happy to realease the package to AUR once you test and we figure out the best way this should be installed according to cumminity guidelines.

In the next three days I should have some spare time finally and I'll try to look into it.

**Comment by woelper** [comment]
I added a CI step for this. I am going to do a test release soon!

**Comment by woelper** [comment]
Amazing, this seems to work!
https://aur.archlinux.org/packages/oculante

Thank you again for your awesome contribution, this was fun!
