### ISSUE TITLE
wayland: expectations + tips for building?

### ISSUE THREAD

**Issue by colemickens** [woelper/oculante#171]
Hi,

I'm trying to use oculante, from nixpkgs, under Sway, and so far winit just complains about not being able to find X.

Any tips for what other build dependencies are needed for oculante to work with Wayland?

Also, is my assumption correct that this should "just work"? Do I need to transitively enable some feature of some Cargo dep to unlock Wayland support?

Thanks for the help, and thanks for oculante.

**Comment by colemickens** [comment]
I did dig in a bit, egui seems to include wayland in the default feature set. And notan doesn't disable default features. So I would guess this should work?

Pretty confused, using throwing `wayland` and/or `wayland-protocols` into the package build dependencies and having WAYLAND_DISPLAY is sufficient.

**Comment by colemickens** [comment]
Also,

```
╭ zeph  ~/code/nixpkgs/cmpkgs 0.01s
╰─▶ ldd result/bin/oculante | grep wayland
        libwayland-client.so.0 => /nix/store/4qn8kb4mrvrqi0iyha50xkq7zd9g2dp0-wayland-1.21.0/lib/libwayland-client.so.0 (0x00007f1e82a5c000)
        libwayland-cursor.so.0 => /nix/store/4qn8kb4mrvrqi0iyha50xkq7zd9g2dp0-wayland-1.21.0/lib/libwayland-cursor.so.0 (0x00007f1e82a52000)
        libwayland-egl.so.1 => /nix/store/4qn8kb4mrvrqi0iyha50xkq7zd9g2dp0-wayland-1.21.0/lib/libwayland-egl.so.1 (0x00007f1e82a4b000)
```

**Comment by colemickens** [comment]
But,

```
~/code/nixpkgs/cmpkgs cmpkgs* ⇡
❯ export WINIT_UNIX_BACKEND=wayland

~/code/nixpkgs/cmpkgs cmpkgs* ⇡
❯ ./result/bin/oculante
thread 'main' panicked at 'Failed to initialize X11 backend: XOpenDisplayFailed', /build/cargo-vendor-dir/winit-0.27.5/src/platform_impl/linux/mod.rs:684:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction (core dumped)  ./result/bin/oculante
```

**Comment by woelper** [comment]
Thank you so much for bringing this up. I have no experience with Wayland, but I am committed to making oculante work on as many operating systems and desktop environments as possible.

I have had a similar issue in the past:
https://github.com/woelper/oculante/issues/24

Back then I added
std::env::set_var("WINIT_UNIX_BACKEND", "x11");
Which fixed the issue. 

Is there any live CD or such wich I can use to test this in a VM perhaps?

**Comment by woelper** [comment]
Reading your messages above, you are setting WINIT_UNIX_BACKEND to a value, and oculante overrides it immediately. This does not seem good. Should we try setting it only to a value if WINIT_UNIX_BACKEND is unset?

**Comment by colemickens** [comment]
I don't think `oculante` should be setting it at all. Winit has its own code for defaulting and allowing the user to override.

I think that "fix" you referenced just side-stepped some of the "extras" that come with using Wayland. In my case, on a tiling WM, I don't particularly care about decorations. Presumably anything else that doesn't work on Wayland is indicative of some other type of bug...

If you have a dev build, I'm happy to try it out, otherwise I think Fedora and likely others default to Wayland nowadays. If you `unset DISPLAY` on one of those (and sanity check that `WAYLAND_DISPLAY` is set), you should be able to effectively test.

**Comment by colemickens** [comment]
Indeed, simply removing that line makes it work under Sway. I can't test GNOME but I see no reason why it should be a problem. Further, wayland apps generally don't work with sudo, again making me wonder about that other bug report.

**Comment by woelper** [comment]
Thank you so much for investigating, this is great! I'd then probably lean towards your suggestion and remove any manual hacks and ask the author of #24 to check again and reopen if necessary. In any case setting that value prior to launch in their setup should also work I guess, but I am not familiar with Fedora.

**Comment by woelper** [comment]
I added 6ee60dec0bd430970b3dee9508b4cbaa325c5892 just now on master. I haven't done a release, but I am planning on doing that once notan `0.9.5` is out probably this week. I'll close this with a big thank you to you for  spotting this and the time you took to investigate!
