### ISSUE TITLE
Info panel's scrolling speed is to slow

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#175]
Might not be obvious from the video, but here the mouse wheel is in a "free scroll" mode (spinning fast), so a browser or a text editor would probably flip through dozen of pages in that time

https://user-images.githubusercontent.com/12956286/231513724-85be63de-e140-4c1c-b31a-11403c16ebe5.mov

**Comment by woelper** [comment]
This is a known issue and will be fixed upstream.

**Comment by eugenesvk** [comment]
Oh, I see https://github.com/Nazariglez/notan/issues/203

**Comment by woelper** [comment]
Fixed after notan update
