### ISSUE TITLE
Images with an Alfa channel of 0 and unpremult, are invisible with the default RGBA view

### ISSUE THREAD

**Issue by tonynoce** [woelper/oculante#178]
The default view for images seems to be RGBA which is fine for most use cases but in VFX an alpha channel can be ignored since the composition doens't have to rely on an Alpha to be there. Yet it is exported as black or in some cases with information.

Currently the fix is to change to RGB by hand, but if the channel Alpha is equal to 0, there is no GUI feedback and the user only sees a grey window.

I saw the unpremult example in the test and made this one, with the corresponding use case escenario:
( the pic is down here )
![unpremult_alpha_0](https://user-images.githubusercontent.com/95554128/232267475-846fe66f-a015-4910-b330-3d2a87de2255.png)

**Comment by woelper** [comment]
Thank you for opening the issue!
I _do_ think what you are seeing is exactly what should happen though. Imagemagick's `identify` says about your image above:

```
identify -verbose 232267475-846fe66f-a015-4910-b330-3d2a87de2255.png
Image:
  Filename: 232267475-846fe66f-a015-4910-b330-3d2a87de2255.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 1920x1080+0+0
  Units: Undefined
  Colorspace: sRGB
  Type: TrueColorAlpha
  Base type: Undefined
  Endianness: Undefined
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 1-bit
```
So it is a `TrueColorAlpha` image with an Alpha Channel which says none of the pixels should be visible. Oculante does the correct thing: It shows the image as fully transparent (as my browser does in your example image, and all other desktop viewers I tried on my linux machine). The difference is that Oculante _can_ show the "hidden" image data.
Is it a good user experience currently in Oculante? I don't think so. Right now you just get a grey screen, so you don't even know if your image loaded. The new release will have a "checkerbox background" pattern soon, maybe that could help? Also maybe drawing a small frame around the image could help? I could also store the mode in the user preferences, so you set Oculante to RGB once and it will remember it.

I am a bit clueless how to improve your experience other than the things above - if I make RGB the default display, many users will wonder why the alpha channel does not display. I could switch the mode if the image is completely transparent, but for that I'd need to go every pixel in the image, which costs a lot of performance.

Happy for your feedback!

**Comment by woelper** [comment]
This is how it could look with a frame:
![image](https://user-images.githubusercontent.com/3613791/232277167-49200e2e-b6ad-4c9a-ab1d-2cac2730f0e7.png)

**Comment by woelper** [comment]
And with a checker pattern:
![image](https://user-images.githubusercontent.com/3613791/232278968-be7b9dc2-cd55-4b4a-8d38-6e7f0462f927.png)

**Comment by tonynoce** [comment]
Well the checkboard pattern is the general consensus of an alpha being zero or transparency :D 
And the grey lines are also a nice touch !

I did realize that I approached this with a compositing program instead of with an image viewer one, below I made some contact sheets with RGBA channels to further illustrate the _issue_...
But I guess that this is more of a general issue with _premult_ and _unpremult_ as you say before, since this is something that most user don't have to deal with it.

All images below are unpremult :
 
![unpremul_test_alpha_full](https://user-images.githubusercontent.com/95554128/232333067-aca2c5a6-1ab6-40bd-9e51-ed7cee0696d3.png)

![unpremul_test_alpha_zero](https://user-images.githubusercontent.com/95554128/232331737-3dcc4126-5962-4c58-bb43-05a3bd6b6b20.png)

![unpremul_test_alpha](https://user-images.githubusercontent.com/95554128/232331738-a196a79a-522a-4e66-ac0b-e046312b55b4.png)

**Comment by woelper** [comment]
I have also added the feature to remember your last channel settings between restarts. You can then set the mode to "Rgb" and oculante will remember this. I hope this will make it easier for you. Thanks for the example images!

**Comment by woelper** [comment]
Closing this as I have released a version with fixes as outlined above
