### ISSUE TITLE
Settings file not updated/corrupted

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#180]
I've noticed that 0.6.62 version stopped updating settings (when I quit with a keybind), and while testing I've encountered that it could just corrupt the file on save (when I quit with a window close button)
Might have to do with this [Fix: Save settings on exit only](https://github.com/woelper/oculante/commit/5e024db48207289c1cf1e62607abcd4ceed5efe9)

Corruption example
- delete `.oculante` settings file
- launch oculante, the default file is created
- click the window close button
- the file is corrupted, the file ends with this:
```
    "NextImage": [
      "Right"
    ],
    "EditMode": [
      "E"
    ],
    "PanRight": [
    
``` 
(all the options below that are gone as are the `PanRight` closing bracket)

When exiting via a keybind, it just doesn't save anything, no recent files, nothing (though given the corruption issue, this might be a good thing :) )

**Comment by woelper** [comment]
Thank you for this. Yes, I believe you found a bug. Also I did notice (after release...) that once you pick a file with the "open" button, I don't get a exit notification from the engine any more. I might have to think of a robust way to save settings.

**Comment by woelper** [comment]
This is now addressed and released. The save operation blocks until it's done. Please let me know if you run into issues again and thanks for spotting this.

**Comment by eugenesvk** [comment]
The corruption is gone, but the save works only on clicking the close window button, quitting with the more convenient shortcut doesn't trigger it

**Comment by woelper** [comment]
That is strange. I do an explicit save when you invoke `Quit`:
https://github.com/woelper/oculante/blob/9f0524caf1982fde87789dbc78083e7df6b50a87/src/main.rs#L345
Is this what you have bound to the exit shortcut?

**Comment by eugenesvk** [comment]
No, I'm using the mac menu's quit button, I think that's the difference
I see that when I use the in-app bound quit button (which I guess invokes the `key_pressed`), it does save the config

(though for some reason now it also changes the order of all the keys, so that breaks my config version control, is there a way to serialize it like before?)

**Comment by woelper** [comment]
Thanks, that clears things up!
I guess the quit event I am getting is not of much use then. I will think of some other way, maybe saving periodically.

I did not change anything in the save logic. Some of the data might not be ordered, so some changes might be unavoidable right now. I have to look at it in detail, but I believe the hotkeys are an unordered map.

**Comment by eugenesvk** [comment]
Interesting, now the save changes the order every time, but previously it would not, the order was the same and it matched a pythons json dump (maybe it was ordering data before save even if the original data structure is not ordered ?)

**Comment by woelper** [comment]
I've added auto-save now, so I am closing this. If I get proper exit signalling from notan, I'll remove or relax auto-save and save on the quit event.
