### ISSUE TITLE
Investigate zune-image

### ISSUE THREAD

**Issue by woelper** [woelper/oculante#183]
can https://github.com/etemesi254/zune-image be used to speed up decoding of some formats, or replace non-native crates?

**Comment by woelper** [comment]
JPEG; Libjpeg-turbo is around the same speed. The only problem is that by replacing it, we'd lose lossless transformations. This is bad. However, zune could be used if oculante is built with default features.

**Comment by eugenesvk** [comment]
> lose lossless transformations. This is bad

agree, sorry for a noob question: is it not possible to use that crate with admirable goals of safety and performance by default and then "carry around" another JPEG lib that would be used only when the user performs a lossless transform?

**Comment by woelper** [comment]
That is not a noob question, it's great!
This is actually what I do with `libjpeg-turbo` as well. There is both `jpeg` support in `libjpeg-turbo` and `image`. But with `zune-image`, there is no other upside than being a pure-rust crate. It is actually slightly slower in my tests - the benefit would be a better build story and no external dependencies. If we still keep `libjpeg-turbo` it around, these benefits do not apply, so it does not make sense to use zune, at least not for jpeg. If it's faster for `tif` or `png` that is a different story of course!

**Comment by woelper** [comment]
Closing this as investigation ended with:

- `zune-image` seems great (almost as fast as `image` and libjpeg turbo bindings
- modules can be used without using the whole library
- png support is now done through zune, with better image support and slightly slower loading
- jpeg replacement will probably not happen unless it is either faster than turbojpeg or has lossless options
- if other formats are supported that oculante does not support yet, zune will be first choice
