### ISSUE TITLE
PPM file support

### ISSUE THREAD

**Issue by IceSentry** [woelper/oculante#195]
When I drag a .ppm image into an opened window, it can load the ppm file without issues, but when I open it using windows default app it says the file format is not supported. 

It's also not registered as a supported file format in the file picker.

I'm not familiar with the codebase, but I'd be willing to submit a PR if I can have some directions on where to fix this.

I'm using version 0.6.64

**Comment by woelper** [comment]
Thank you! I believe this was an oversight on my end. I am happy to add it as it probably is a trivial fix, but you are also welcome to try - I think all that's needed is to edit this line:
https://github.com/woelper/oculante/blob/1ba9f0fdca58d1360b803b1e0d79086f36fe9396/src/utils.rs#L45

I think the format is already supported in `image`, and Oculante does no checks if the image is dropped on the window. As a result, I think you just need to add the str `ppm` to the above list.

**Comment by woelper** [comment]
Thank you again for the PR! I'll add this to the next release.
