### ISSUE TITLE
Menu option to show view options.

### ISSUE THREAD

**Issue by Jerakin** [woelper/oculante#2]
View menu that have the different view modes in it (that are now only documented in the readme), they should also display which hotkey triggers when viewing an image.

**Comment by woelper** [comment]
Initially all UI was a non-goal (a fancy word for lazy). With some more options and inspection tools it might a good idea of adding a Ui library now I guess.

**Comment by Jerakin** [comment]
Makes sense, especially if you want to keep it as a small binary. The important bit is that the user shouldn't need to have the github page open to see all the hotkeys. One alternative to a meny could then be that when you start Oculante it says "Press H for help" (under the "Drag image here") that when pressed you get a HUD of the keyboard shortcuts.

**Comment by woelper** [comment]
Nice idea, I'll add this while I evaluate UI options!

**Comment by woelper** [comment]
This is now done pretty much as you described. Release 0.4.14 contains this fix.
I am still not very happy and would like to integrate egui/conrod/imgui later, but the integration with piston (the "engine" used) is pretty convoluted and undocumented.

**Comment by Jerakin** [comment]
It might currently be a bit too fast. On macOS fades out after ~1 sec. But as it fades it is pretty much not readable after 0.5 sec.
![showing](https://user-images.githubusercontent.com/5273682/105251506-f38ad880-5b7b-11eb-8cb5-fa31d8afd046.gif)

**Comment by woelper** [comment]
Agree. It's frame based and it's currently set to 180 I believe - i made it a bit longer. Will make it time based.

**Comment by woelper** [comment]
should be fixed now!
