### ISSUE TITLE
[BUG] Zune-PNG: Grayscale PNGs broken on latest git 

### ISSUE THREAD

**Issue by Quackdoc** [woelper/oculante#214]
Example PNG.

https://files.catbox.moe/wwv9xr.png

bisected to b9ace311ea2decb633f85ce4e6b7f3342893a029

seems like zune-png wasn't the golden nugget

**Comment by woelper** [comment]
I'll look into that, thanks for the source image. If it is indeed an issue in zune, let's report it there!

**Comment by Quackdoc** [comment]
does zune have a minimal testing program? that would be easiest to test with

**Comment by woelper** [comment]
It looks like zune-image itself is a command like application - I am only on a mobile phone (vacation :)) but the main.rs looks like you could just clone the zune main repo at https://github.com/etemesi254/zune-image

And run "cargo run". Maybe this would give you a barebones image viewer?

**Comment by Quackdoc** [comment]
it was unrelated, turns out oculante wasn't checking for graya added some noise to an image with `magick .\ina4k.png -set colorspace gray -alpha set -background none -channel A -noise 3 -evaluate multiply 0.9 +channel out.png` and yup, same corruption. PR posted

**Comment by woelper** [comment]
Thanks so much, merged this!
