### ISSUE TITLE
Please provide Cargo.lock

### ISSUE THREAD

**Issue by devhell** [woelper/oculante#22]
Hi,

I'm a [NixOS](https://nixos.org/) package maintainer, and I am currently packaging `oculante` for it (WIP). It would help a lot if you could retain the `Cargo.lock` file. This makes packaging easier for us, or in this case, me. More info can be found [here](https://nixos.org/manual/nixpkgs/stable/#rust). The argument for the `Cargo.lock` file is mentioned a bit further down after the `cargoHash = lib.fakeHash;` example.

Please consider adding it to your repo. Thank you also very much for this fine piece of software, it's awesome. :)

**Comment by woelper** [comment]
Thanks so much. I'll add it right away!

**Comment by devhell** [comment]
Thank you too!
