### ISSUE TITLE
High GPU usage after launch

### ISSUE THREAD

**Issue by mercuree** [woelper/oculante#220]
Oculante uses 80% of my Intel i3-8300 GPU just after launch without any images opened.
"Enable vsync" option has no any effect on this.

**Comment by woelper** [comment]
Hi! Thanks for opening the issue!

Oculante is constantly refreshing when no image is opened, so this is unfortunately expected behaviour. I'll leave this open to address this in the future. Once you open an image, the cpu/gpu usage should hopefully go down a lot, is that the case?

**Comment by woelper** [comment]
Thanks for checking. I'll try to see if I can reproduce that on a windows machine and find out where this is coming from.

**Comment by woelper** [comment]
Windows did not have the `lazy_loop` configuration that other operating systems had. This has been corrected and I am seeing much lower CPU and GPU usage now. 0.7.5 will have this feature, and I'd be super happy if you could verify that GPU usage goes down for you. Thanks for reporting this.

**Comment by mercuree** [comment]
Yes, this was fixed. Thank you!
