### ISSUE TITLE
update to smithay-client-toolkit 0.17

### ISSUE THREAD

**Issue by colemickens** [woelper/oculante#225]
Hi,

My loose understanding is that SCTK 0.17 is a non-trivial update, but I am finding that my various favorite Rust apps using SCTK <0.16 do not work in newer Wayland compositors like sway-tip, Plasma 6, etc.

Hence, this request, that oculante be updated to SCTK 0.17, directly or maybe via sctk-adwaita, from skimming the Cargo.lock.

<3 :pray: Thank you for Oculante! I hope to get back to using it :cry:

**Comment by colemickens** [comment]
That should say "using SCTK <=0.16", though its unclear if that's specifically because of the version or because 0.17 provokes other changes that cause the issue to go away.

**Comment by woelper** [comment]
Thanks for the kind words and the request!

I am totally unaware of this, sorry. I am still a non-wayland guy (I know...) so I don't run into these issues early.

Can you help me understand a bit how this ties together?

You are using a newer Wayland compositor like Plasma 6, and in these SCTK 0.17 is mandatory?

My issue is that I am not directly able to influence sub-dependencies. I can drill down a bit and see if I can update something that would cause SCTK to be updated though, or you could make the maintainers of a package such as `winit` aware of this issue for example.

There was an old issue related to wayland:
https://github.com/woelper/oculante/issues/24

I'd be interested to see if `WINIT_UNIX_BACKEND=x11 ./oculante_linux` from a terminal changes anything.

**Comment by colemickens** [comment]
Using the X11 backend does work, but is a suboptimal solution IMO. It winds up being blurry since I have sway set to >1 scale.

And yes, I do see that winit uses sctk-adwaita, which in turn uses sctk. I'll have to dig in a bit more to determine what needs to be upgraded. I understand that sctk-0.17 is a big-ish change, and it looks like the SCTK folks might cut a 0.16.1 that might workaround this issue without requiring the full upgrade to 0.17.

And indeed, a number of other apps use winit, so it needs to be fixed there.

I guess probably not much to do here for oculante until sctk-adwaita/winit are updated appropriately.

**Comment by colemickens** [comment]
Weird, I'm tired but it seems like you're using a new enough notan, but Oculante's Cargo.lock lists an older sctk-adwaita than I'd expect from looking through notan/winit/sctk-adwaita repos....

**Comment by colemickens** [comment]
Oh, I see it now.

winit's bump to sctk 0.17 is unreleased.

so, hopefully they have a release sometime :)

**Comment by woelper** [comment]
Cool, thanks for looking it up in depth. We can leave this open until winit updates, and I can do a release as soon as that happens!

**Comment by colemickens** [comment]
Hi @woelper, I have an update! I asked about this in #sway and some smithay devs did a thing.

In short `cargo update -p smithay-client-toolkit` should pull in a `0.16.1` bugfix release that resolves this issue while the ecosystem waits for the new `winit` release.

If you could bump that dep and publish a release, that would be dope. :slightly_smiling_face:

**Comment by woelper** [comment]
Aye! You got it!

`Updating smithay-client-toolkit v0.16.0 -> v0.16.1`

**Comment by colemickens** [comment]
Thanks for the speediness, hopefully in nixpkgs soon: https://github.com/NixOS/nixpkgs/pull/256343
