### ISSUE TITLE
Aur Package lto issue

### ISSUE THREAD

**Issue by LuisB79** [woelper/oculante#226]
You need to disable lto at PKGBUILD to compile properly the program, if not #191 will occur. Please add '!lto' into options array

**Comment by woelper** [comment]
Cool, then I remove LTO and release. If that's still an issue we'll look at disabling LTO from the release build or make it optional. I think it may give a minimal speedup, so removing it might come as a cost.

**Comment by woelper** [comment]
Cool, then I remove LTO and release. If that's still an issue we'll look at disabling LTO from the release build or make it optional. I think it may give a minimal speedup, so removing it might come as a cost.

**Comment by LuisB79** [comment]
> Cool, then I remove LTO and release. If that's still an issue we'll look at disabling LTO from the release build or make it optional. I think it may give a minimal speedup, so removing it might come as a cost.

Im going to check on it!

**Comment by woelper** [comment]
As soon as you give me an OK on this one, chief!
https://github.com/woelper/oculante/pull/227

**Comment by woelper** [comment]
As soon as you give me an OK on this one, chief!
https://github.com/woelper/oculante/pull/227

**Comment by LuisB79** [comment]
it worked!, now cargo.toml still has lto, so im betting the binary still has lto, even though the makepkg has !lto, but im not sure, i dont know who can confirm that,
