### ISSUE TITLE
Error: "extension to create ES context with wgl is not present"

### ISSUE THREAD

**Issue by Unknown78** [woelper/oculante#247]
### Background

OS: Windows 11 v10.0.22631.2715 64-bit
CPU: Intel i3-2310M
GPU: Integrated Intel HD Graphics 3000

App: [Release 0.7.7](https://github.com/woelper/oculante/releases/tag/0.7.7)

<hr>

### Steps to Reproduce

Run `oculante.exe`

### Expected Behaviour

It opens as usual.

### Actual Behaviour

It closes itself.

### Logs

`set RUST_LOG=debug && oculante > oculante.log`
Only `stdout` will output nothing.

It turns out that combined `stderr`, `stdout` and `set RUST_LOG=debug` is too much.
`set RUST_LOG=debug && oculante > oculante.log  2>&1`

Just `stderr` is suffice.
`oculante 2> oculante.log`

```
Error: "extension to create ES context with wgl is not present"
```

Found something that may related:
https://rustrepo.com/repo/tomaka-glutin
https://github.com/rust-windowing/glutin/issues/1550
https://github.com/rust-windowing/glutin/pull/1553

**Comment by woelper** [comment]
It seems your graphics card supports [OpenGL 3.0](https://www.notebookcheck.net/Intel-HD-Graphics-3000.37948.0.html), where Notan [requires](https://github.com/Nazariglez/notan/tree/develop) OpenGL 3.3.

**Comment by Unknown78** [comment]
The driver may be the issue that prevents me from having OpenGL 3.3
A reddit [post](https://www.reddit.com/r/lowendgaming/comments/1258usx/comment/jjzn6ri/) claim to have OpenGL 3.3 on Linux.

The original Intel graphics driver cames from Windows Update.
I have OpenGL 1.1
![1](https://github.com/woelper/oculante/assets/25132599/15608509-fab5-4e6f-ad92-f9a0b5e23cb5)


With an [unofficial driver](https://winraid.level1techs.com/t/get-your-intel-hd3000-sandy-bridge-windows-10-64bit-drivers-here/40044) and its [tutorial](https://www.reddit.com/r/lowendgaming/comments/1258usx/updated_win1011_drivers_for_intel_hd_3000/).
I have OpenGL 3.1
![2](https://github.com/woelper/oculante/assets/25132599/cd206882-ed86-4d85-86e5-b8ad6f9470d8)

<hr>

@woelper I couldn't find any Image viewer that's updated and written purely on Rust except this.
Could you please implement fallback mechanism by using different engine or something like that?

**Comment by woelper** [comment]
Thanks for sharing!

I've thought about this, but there is significant work attached to this for relatively low gain. I've actually even made some progress to offload some of the operations into the UI, which can be used on top of other libraries, even software-rendered ones. But in short, a fallback would mean:
- I am currently using a lot of engine features and data types, like Vec2 for example. If I want to transition / use a fallback, I would need to use a different data type and convert between them. This is not only more code, but also possibly a performance issue.
- The engine is doing a lot of window management (set always on top, full screen, setting an icon, window title...) - all that would need to be done for several frameworks or even manually.
- The engine does input handling as well, so for example mouse movement, scrolling, keyboard shortcuts... especially the shortcuts were a lot of work. If a different framework/engine would be used, these things would need to be redone.
