### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by aarmea** [woelper/oculante#251]
It would be great if I could get oculante working on my Pi 4, but as of right now I see the following when I try to run the aarch64 build:

![image](https://github.com/woelper/oculante/assets/724900/d5d3f7cc-3033-418f-8a22-2f96c1ad01d7)

Are there any dependencies I'm missing? For what it's worth I'm running Raspbian Bullseye 64-bit on a 8 GB Pi 4 plus the following packages installed normally:

```
sudo apt install htop tmux mosh git build-essential rsync python3-pip
sudo apt install pigpio-tools meson
sudo apt install -y libepoxy-dev libjpeg-dev libtiff5-dev
sudo apt install -y qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5
sudo apt install -y libavcodec-dev libavdevice-dev libavformat-dev libswresample-dev
sudo apt install -y cmake libboost-program-options-dev libdrm-dev libexif-dev
sudo apt install -y libboost-dev
sudo apt install -y libgnutls28-dev openssl libtiff5-dev
sudo apt install -y qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5
sudo apt install -y meson
sudo apt install -y libglib2.0-dev libgstreamer-plugins-base1.0-dev
sudo apt install -y libpng-dev
sudo apt install -y libcamera libcamera-dev libpigpio1 libpigpio-dev
sudo pip3 install jinja2
sudo pip3 install pyyaml ply
sudo pip3 install --upgrade meson
```

**Comment by woelper** [comment]
I am not absolutely sure, but it says in the beginning that OpenGL 3.30 is not supported. This is a requirement by the engine (notan) oculante is using. Unless your hardware is providing that capability, there might be no way to use oculante - unless notan lowers requirements or oculante somehow switches the engine.

**Comment by aarmea** [comment]
Thanks for confirming my suspicions so quickly. Feel free to close if this is not anywhere on your roadmap.

**Comment by Quackdoc** [comment]
The RPI should support this, IIRC, try making sure you are up to date, if not you may be able to run zink with some succsess

`MESA_LOADER_DRIVER_OVERRIDE=zink oculante`

**Comment by woelper** [comment]
I'll close this for now as this is likely out of reach.
