### ISSUE TITLE
Set app_id for wayland

### ISSUE THREAD

**Issue by martinlindhe** [woelper/oculante#253]
Background: in wayland WM:s such as sway or hyprland, you configure your desktop with some rules. One of them is filter on app_id, which holds some unique identifier.

This is analogous to class in X11 apps.

When running oculante 0.8.6 under wayland, app_id is null.

~~If using winit, one can achieve this using https://docs.rs/winit/latest/winit/window/struct.WindowBuilder.html#method.with_name-1~~

EDIT: I realized this is a notan thing.

**Comment by martinlindhe** [comment]
https://github.com/Nazariglez/notan/issues/304

**Comment by woelper** [comment]
I see this is released now. Will make a fix and new version soon!

**Comment by woelper** [comment]
Done, in next release

**Comment by martinlindhe** [comment]
Thank you!
