### ISSUE TITLE
Image is occluded by side panels

### ISSUE THREAD

**Issue by B-LechCode** [woelper/oculante#255]
An image is partially occluded by the side panels, when fit to the window.
This is annoying when dealing with ultra wide images, in my case: 16384x1024 pixels.

I wanted to work out a fix. Would this be useful, or is the current behavior intended?

A question for that: where may I query the width of the two side panels? Is it currently tracked somewhere, or may I add their widths to the state struct?

Thanks :)

**Comment by B-LechCode** [comment]
I'm working on this. Will provide a PR when I'm done with it.

**Comment by woelper** [comment]
Hi! Thanks!
Layouts in egui are dynamic and are recalculated per frame. I would not store that somewhere but instead query egui for the sizes. As this is per-frame, I think that would have to be done at a place where the image is reset / received.

**Comment by woelper** [comment]
Hi, and thank you again for your work!

I think your feature request is super good - I came to the conclusion that this should be the default how sizing is handled. With that in mind I made a new PR that directly modifies the function to scale - I hope this keeps the functionality a bit simpler while still keeping the original idea:

https://github.com/woelper/oculante/pull/267

Would you mind going for this simpler approach per default?

**Comment by B-LechCode** [comment]
It's perfect to use that approach, I just kept the old approach because I thought it was intentionally.

But you omitted some of the other small fixes I included with my PR:
- Centering and scaling the image to the available draw area, you use the whole window height for centering/scaling: If an image has a high aspect, you will get the same problem I had when I reported that issue. Suggestion: please copy the calculation part I provided.
- Truncating path strings that are too long to keep the left panel at a steady width
Both are positive aspects for the look and feel of the gui in my opinion.

PS: It would have been ok, if you would just have edited my branch as you should have had the rights to do so :) Maybe it would have saved you some time.

**Comment by woelper** [comment]
Thanks for the answer!

> Centering and scaling the image to the available draw area, you use the whole window height for centering/scaling: If an image has a high aspect, you will get the same problem I had when I reported that issue. Suggestion: please copy the calculation part I provided.

Are you referring to the menu bar occluding the image? I've tested lots of images and none occluded the side panels.

> Truncating path strings that are too long to keep the left panel at a steady width

I was not able to replicate that with a super long string. Also the left panel could potentially resize again in the future, so the approach should take a dynamic width into account. If you have a specific use case that fails I'd be happy to test it!

> PS: It would have been ok, if you would just have edited my branch as you should have had the rights to do so :) Maybe it would have saved you some time.

Just to be super clear: I deeply value your contribution, and this is not be trying to lessen your impact/work. Again, the idea is amazing - it was just less work for me to adjust the scaling than removing some aspects from your PR, for example adding extra options for the scaling mode and the placement of the code. I think by just moving the reset function to the end of the UI code makes the change smaller, hence that was how I did it.

**Comment by B-LechCode** [comment]
I thought about the menu strip (on the top) to possibly occlude the image, as you use the whole window height and no y-offset. That's a thing I addressed, too. I will try to generate some test images to test if my assumption is right.

The size of the text strongly depends on the naming. I had several images in my image folder which expanded the left panel unintentionally. It's not directly about the length of the string. I will test with that and come back with the results.

Sorry if my answer seemed "salty". It was just an idea and my statement, that I wouldn't have had a problem if you did so. Thank you for valuing my contributions :) I deeply value this project for it's performance and concept, that's why I chose to use and possibly extend it for my research and work instead of writing my own - Thank you :)

**Comment by B-LechCode** [comment]
I've built you 2 test images to prove my concerns. I created the images myself and you may freely use them.
For the wide version, the 30 white colums are visible, for the high version they aren't.
My calculation works in that case (0.86 is my branch, 0.87 is yours).
![Screenshot_20240128_123950](https://github.com/woelper/oculante/assets/31586281/1647e193-10da-4729-b0be-62284752b3be)
![Screenshot_20240128_123707](https://github.com/woelper/oculante/assets/31586281/52512149-2262-46e3-9a4a-77dd9f49d6c5)
![Screenshot_20240128_123640](https://github.com/woelper/oculante/assets/31586281/77ba65f6-edb8-4b05-8183-45317882bec0)

[wide](https://github.com/woelper/oculante/assets/31586281/b8015af9-3ba1-4f3e-bf01-2457bd7e08ed)
[high](https://github.com/woelper/oculante/assets/31586281/059b1ede-6150-4dd5-8ffa-095159922c29)

**Comment by woelper** [comment]
Amazing, thanks!

I've updated the PR - I was just missing the top menu bar. Your images were indeed helpful, and I have added them to the tests along with the PR here:
https://github.com/woelper/oculante/pull/267/files

**Comment by B-LechCode** [comment]
Thank you!

Would you mind if I'd check the file name thing in the next few days and bringing up a PR with the truncation if necessary?

Small question regarding the test images: my first test images were 32768x512. There was an error message and the image dimensions shown were only 16384x256. Do you know which part is limiting the size of the image?

**Comment by B-LechCode** [comment]
@woelper, I used some image names found in my image folder and "pasted" them to the test images in the repository.

Please have a look at the gif I created:
![panel_width](https://github.com/woelper/oculante/assets/31586281/2dffe32c-88c7-4524-9425-834c4ae282e6)

That's why I suggest adding some render width aware string truncation:
![panel_width_trunc](https://github.com/woelper/oculante/assets/31586281/b7ba5611-7bcb-4ffd-bc84-0672ec541410)

In the example I made, the path string was initially truncated from "leftside" to 18 chars and the truncate property of Label was activated.

Created a PR ( #277) with that approach

**Comment by woelper** [comment]
Thank you again! I merged the PR just now, so I think we can close this!
