### ISSUE TITLE
man this just happened when i installed it from cargo

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [woelper/oculante#26]
`C:\Users\10\Pictures>oculante`
`Error: "required extension \"WGL_ARB_create_context_profile\" not found"`

**Comment by soyDESKTOP68A2MRFT** [comment]
i think that the problem it's my graphics card

**Comment by woelper** [comment]
Are you able to run a binary from the releases tab?

**Comment by soyDESKTOP68A2MRFT** [comment]
> Are you able to run a binary from the releases tab?

i tried a release and the same happened

**Comment by woelper** [comment]
I just pushed a new release with an upgrade of notan (the engine used) could you please try the latest one? Your graphics card needs to support OpenGL 3.3 I believe.

**Comment by soyDESKTOP68A2MRFT** [comment]
Which one of the releases have a opengl 3.1 support (i cant change the
graphics card cus im on a laptop)

**Comment by woelper** [comment]
Please try this one:
https://github.com/woelper/oculante/releases/tag/0.5.25

I am sorry that the switch to a new engine caused this for you. I decided to go for a new UI and some more modern features which seem to require a higher OpenGL version.

**Comment by soyDESKTOP68A2MRFT** [comment]
Thanks, I'll check it out.

**Comment by soyDESKTOP68A2MRFT** [comment]
The thing keeps happening

**Comment by soyDESKTOP68A2MRFT** [comment]
So the same issue is happening with the release version for me so idk

**Comment by soyDESKTOP68A2MRFT** [comment]
Sorry for close it

**Comment by woelper** [comment]
No worries.
Unfortunately, as I don't share your hardware configuration, the only thing I can suggest is that you keep going back in the releases and pick the one that works. I assume it did work at some point for you?

**Comment by soyDESKTOP68A2MRFT** [comment]
No, it didn't worked and my setup is:
Intel core i5 2450m
4GB of ram
Intel hd graphics 3000

**Comment by woelper** [comment]
I've tested on my super old laptop and can't reproduce. I do have an intel hd 4000 in it though I believe. Can you run any of the demos located at https://nazariglez.github.io/notan-web/ ?

**Comment by woelper** [comment]
Closing and continuing in #247
