### ISSUE TITLE
Crash when trying to open PSD

### ISSUE THREAD

**Issue by octfx** [woelper/oculante#262]
I'm getting the following error when trying to open a psd file.  
Installed `0.8.6-1` via the deb package.

```
thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/psd-0.3.4/src/psd_channel.rs:171:25:
index out of bounds: the len is 6760000 but the index is 6760000
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by woelper** [comment]
Thanks for reporting!
Without knowing details, this seems like this could be an issue with the `psd` crate. Would you mind sharing the psd file or one with which we can reproduce this?

**Comment by woelper** [comment]
Hi @octfx ! Would you be able to provide a PSD file that crashes Oculante? I can then try to look into this or file a bug in the library if needed.

**Comment by woelper** [comment]
No worries, thanks for giving it a look! Feel free to reopen this once something unexpected happens!
