### ISSUE TITLE
Animated WebP

### ISSUE THREAD

**Issue by Airradda** [woelper/oculante#269]
Unless I am doing something wrong, it appears Oculante doesn't support animated WebP. Is this is a limitation of Oculante, the available bindings of libwebp-sys, or something else?

**Comment by woelper** [comment]
You are correct, there currently is no support in oculante for that. From skimming the docs, there might be support in the library. I'll leave this open to track the progress - thanks for opening this!

**Comment by woelper** [comment]
I've looked at it more, and I am trying to follow the official API docs here:
https://developers.google.com/speed/webp/docs/container-api#webpanimdecoder_api

However, webp-sys does not seem to have an easy way to replicate this - I opened a ticket to see what I might be missing here:

https://github.com/NoXF/libwebp-sys/issues/26

**Comment by woelper** [comment]
Well, I should have done more homework before. Apparently someone has done the heavy lifting already:
https://crates.io/crates/webp-animation

I will look at that next and possibly look at https://crates.io/crates/libwebp-sys2 as well.

**Comment by woelper** [comment]
I've made good progress and can successfully open animated webp images now. However, load time has become slower as I currently need to read in the animation to know its length. Once I have found a workaround I will make a release with that feature enabled.

**Comment by woelper** [comment]
The load time is minimally slower for single images, but I think having animations is worth it. This will be available in the next release.
