### ISSUE TITLE
Settings sometimes don't apply when set, and will sometimes unset themselves

### ISSUE THREAD

**Issue by Quackdoc** [woelper/oculante#271]
When i'm comparing images, I often need to close the application and re-opening it and toggle don't reset image. it will occasionally also reset the settings, which also needs a restart to fi.

tested commit c9dead5c89e6035cf552bef22d9d9e686659aa5e

**Comment by woelper** [comment]
Hi!
I think I need help understanding this issue.
> When i'm comparing images, I often need to close the application and re-opening it and toggle don't reset image.

Would you like the compare list to be saved across restarts? Is this the main issue?


If possible, could you list step-by-step instructions please how to reproduce the issue, e.g. "open file a and b, then restart, then click a - xxx should happen, but instead yyy happens"?

**Comment by Quackdoc** [comment]
Ah sorry, it's not about compare. I was needlessly misleading. Sometimes when I set an option in preference, it will become unset. 

example
Preferences > Enable `Do not reset image view` > flick between images > It works fine > keep going for a while > suddenly it will start to reset image view again

The only solution for this is to restart the app. It's quite sporadic now after recompiling but it does seem to still be happening

**Comment by woelper** [comment]
This was fixed in 4e06ca718d28b01884d24820a4dd36689c7bb73a.
