### ISSUE TITLE
Version 0.8.8 made all the text blurry

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#277]
left - before, no blurry fonts
right - v0.8.8 and 0.8.9 - everything is very blurry
<img width="186" alt="oc8" src="https://github.com/woelper/oculante/assets/12956286/94f4e34f-59b2-400f-882f-e3278a30a8ac">

This in on Windows 10 with some monitor scaling

**Comment by woelper** [comment]
Thanks!
This is after an `egui` and `notan` update and looks HiDPI-related. I'll take a look.

**Comment by woelper** [comment]
Seems to happen on mac, too :( 

<img width="592" alt="image" src="https://github.com/woelper/oculante/assets/3613791/05f31c42-f28f-4887-b134-41b9be42286f">
