### ISSUE TITLE
Do you have any plans to add "Ctrl+c Clipboard copy" function?

### ISSUE THREAD

**Issue by dymaxionkim** [woelper/oculante#28]
In MS Windows10 environment, I think it is probably the fastest and simplest Image Viewer.
With this feature, the number of users will increase significantly.

**Comment by woelper** [comment]
This is a great idea. I was already thinking about screen capture functionality, but I will start with ctrl c / ctrl v across mac/win/linux.

**Comment by woelper** [comment]
Hi @dymaxionkim , I just added this functionality and it is available in the `0.5.41` release. Thank you for the great suggestion and let me know if you have other great ideas.

**Comment by nonetrix** [comment]
Doesn't seem to work for me on Wayland/Hyprland
