### ISSUE TITLE
wrong draw surface size for some images

### ISSUE THREAD

**Issue by diegostafa** [woelper/oculante#285]
for some images `ctx.available_rect()` returns the biggest possible surface (around 8000x8000px in my case) which causes the image to be placed in the wrong position

this only happens in the first `reset_image` becasue in the next ones `available_rect()` returns the right surface size

the weird thing is that this only happens for some images but i can't figure out the reason

**Comment by diegostafa** [comment]
i think it happens when the loading time is too small

for small sized images this seems to happens much more frequently, for large ones it does not occur

**Comment by woelper** [comment]
Wow, you are my hero!
I have seen this happen lately and could not figure out why this was happening. What you say makes absolute sense. On top of that, this is rather recent functionality to make sure the image fits with panels active. I'll take a look soon, feel free to open a PR if you spot something!

**Comment by woelper** [comment]
not knowing the root cause, at least this

```rust
let window_size = nalgebra::Vector2::new(
    draw_area.width().min(app.window().width() as f32),
    draw_area.height().min(app.window().height() as f32),
);
```

makes sure that the draw area can't be larger than the window size...

**Comment by diegostafa** [comment]
> not knowing the root cause, at least this
> 
> ```rust
> let window_size = nalgebra::Vector2::new(
>     draw_area.width().min(app.window().width() as f32),
>     draw_area.height().min(app.window().height() as f32),
> );
> ```
> 
> makes sure that the draw area can't be larger than the window size...

i made a branch with the exact same patch but i noticed it didn't quite work with the offsets
