### ISSUE TITLE
Ability to paste an image and save it

### ISSUE THREAD

**Issue by spikespaz** [woelper/oculante#290]
When I screenshot something from my clipboard and don't want to load GIMP

**Comment by woelper** [comment]
This feature is already available. Could you try it out and see if it is working for you?

**Comment by spikespaz** [comment]
I was expecting it to work with Ctrl V. Strange that it doesn't. Either way, clicking the menu button, tells me the clipboard does not contain an image. If I use `wl-paste | image.png` I am able to open and view the image. It is from `grim`.

**Comment by woelper** [comment]
Yes, that seems to be a bug - it should work with the key combination. I have not used `wl-paste` myself - I have tried this by copying images from different graphics applications. Basically, there need to be bytes in the clipboard that the `image` library can decode.

**Comment by spikespaz** [comment]
Well the data is put into the clipboard with `grim`, using `--copy -t png`

**Comment by spikespaz** [comment]
If I copy the image with `wl-copy -t image/png < "$image_path"` it does not work.

**Comment by woelper** [comment]
Have you tried copying from something like gimp or a screenshot utility as well? Does that produce a similar effect?

**Comment by spikespaz** [comment]
No it does not work.wkth himp or any program. The issue appears to not be that the keybimd.doesnt.work, it is that clipboard is broken on Wayland. Consider using another cross-desktop (XDG) compatible clipboard crate?

**Comment by woelper** [comment]
The keybinding is actually broken, so it is great you spotted that! 
The library says:
```
There's also an optional wayland data control backend through the wl-clipboard-rs crate. This can be enabled using the wayland-data-control feature. When enabled this will be prioritized over the X11 backend, but if the initialization fails, the implementation falls back to using the X11 protocol automatically. Note that in my tests the wayland backend did not keep the clipboard contents after the process exited. (Although neither did the X11 backend on my Wayland setup).
```

I am not sure if there even is another cross-platform clipboard crate...

**Comment by spikespaz** [comment]
Could you please re-export the `wayland-data-control` feature as `wayland-clipboard` in the `Cargo.toml` and maybe make it a `default-features`?

**Comment by woelper** [comment]
I think enabling it as default in general makes sense - it sounds a feature might not even be needed.

**Comment by spikespaz** [comment]
There is currently:
 - [copypasta](https://lib.rs/crates/copypasta)
 - If we run into issues with the clipboard getting cleared for protocol reasons: [copypasta-ex](https://lib.rs/crates/copypasta-ext)

The second one looks like a good option as I am not sure if the first (a fork of another crate, to add Wayland support) did it properly. For windowed applications, the clipboard is supposed to be associated with the window.

**Comment by spikespaz** [comment]
Arboard currently has a warning in the readme:
```
Note that in my tests the wayland backend did not keep the clipboard contents after the process exited. (Although neither did the X11 backend on my Wayland setup).
```

**Comment by woelper** [comment]
It does not look like copypasta supports image data as far as I see

**Comment by spikespaz** [comment]
If the feature flag works then it works but it might not behave as desired under all circumstances.

**Comment by spikespaz** [comment]
No matter what, seems like the answer is that no rust crates can talk to a WL clipboard using the window handle. <https://smithay.github.io/smithay-clipboard/smithay_clipboard/struct.Clipboard.html> Not even Smithay.

So maybe the protocol needs to be built manually for some reason? It is unstable?

https://docs.rs/eframe/latest/eframe/struct.Frame.html#method.window_handle

We can use a window handle from eframe and port `wl-copy` code to Smithay's bindings:

<https://github.com/bugaevc/wl-clipboard/blob/master/src/wl-copy.c>

Obviously this is a separate crate now. Yet Another Clipboard Crate But This Time With Proper Wayland Support

ACCBTTWPWS

**Comment by spikespaz** [comment]
I don't know what this does but it looks like it works to get around the other problem
<https://github.com/Kirottu/watershot/blob/master/src/main.rs#L72-L90>
