### ISSUE TITLE
windows: `open with` mechanism no longer work

### ISSUE THREAD

**Issue by hUwUtao** [woelper/oculante#294]
as usual, file is launched by clicking a file and it should launch oculante like:

> `C:\bin\oculante.exe X:\image.jpg`

suddenly, it no longer work, no logs, just boot up oculante without any images. function like "drag in" still work as intended.

**Comment by woelper** [comment]
Thanks! This indeed happened after URI support here:
https://github.com/woelper/oculante/pull/283

I have fixed this and will release a fix soon.
