### ISSUE TITLE
images dont open properly when using dolphin

### ISSUE THREAD

**Issue by murl-digital** [woelper/oculante#297]
After moving to plasma 6, double clicking an image opens oculante but not the image itself. trying to open the same image in something like gimp still works.

**Comment by woelper** [comment]
Thank you for reporting. I suspect this is a regression. I've made a new release - could you please try https://github.com/woelper/oculante/releases/tag/0.8.16 and see if that fixes your issue?

**Comment by murl-digital** [comment]
that fixed it! thank you very much!

**Comment by woelper** [comment]
Awesome. Sorry for this and thanks for reporting!
