### ISSUE TITLE
Wayland seems to have broken

### ISSUE THREAD

**Issue by Quackdoc** [woelper/oculante#299]
Im getting the below issue when trying to run oculante on Wayland. I've tested `Smithay (Cosmic-comp)` `kwin (KDE)` `wlroots (Sway, Cage)`. I've seen similar issues before, I think it may have been on an egui app but updating that worked, as a work around for anyone else simply unsetting `WAYLAND_DISPLAY` will cause it to fall back to x11 which works fine

```
warning: queue 0x5c04daa707d0 destroyed while proxies still attached:
  xdg_wm_base@30 still attached
  wl_seat@16 still attached
  wl_output@15 still attached
  wl_output@14 still attached
  zwp_relative_pointer_manager_v1@13 still attached
  xdg_activation_v1@12 still attached
  zwp_text_input_manager_v3@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wp_viewporter@8 still attached
  wl_shm@7 still attached
  wp_fractional_scale_manager_v1@6 still attached
  wl_subcompositor@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
Error: "[3009] arguments are inconsistance"
```

**Comment by woelper** [comment]
Hi!

I've recently changed the app id here, specifically for wayland purposes:
https://github.com/woelper/oculante/blob/b3ff6a863fbee50de94d4843cc00c89da48e193b/src/main.rs#L80

This was requested in this issue here:
https://github.com/woelper/oculante/issues/253

I am not sure this has anything to do with it, and I am still on a non-wayland linux. I could either make you an executable for linux without the app_id or set up some kind of wayland environment on my end.

**Comment by woelper** [comment]
I managed to enable wayland on PopOS now, and if I run `echo "$XDG_SESSION_TYPE"` I get `wayland`. Oculante opens just fine without any suspicious message when I run `0.8.17` downloaded from the release tab. Is there anything more I can try to reproduce this?

```
./oculante_linux-0.8.17
[2024-03-29T15:10:40Z INFO  notan_glow] OpenGL Info:
    Version: 4.6 (Core Profile) Mesa 24.0.0-1pop0~1706872735~22.04~0fa430c
    Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 15.0.7, DRM 3.54, 6.6.10-76060610-generic)
    Vendor: AMD
    ---
[2024-03-29T15:10:40Z INFO  oculante] Successfully loaded previous settings.

```

**Comment by Quackdoc** [comment]
hmm even the release build isn't working for me. Error 3009 I think is an egl related error. I am running mesa-git which could be the issue I suppose. Ill try downgrading when I can

**Comment by martinlindhe** [comment]
> hmm even the release build isn't working for me. Error 3009 I think is an egl related error. I am running mesa-git which could be the issue I suppose. Ill try downgrading when I can.
> 
> EDIT: Yeah that was it, mesa-git caused the issue, im not sure if this is a regression in mesa or somewhere else as other winit/glow applications work fine. I don't have any notan based applications to to test them

Mesa-git is causing issues with gfx-rs on wayland currently. I hit the above issue with wezterm while using mesa-git myself. Had to revert to mesa stable. mesa-git did not exhibit this issue just 3 weeks ago or so, something happened recently.

Didn't get around to looking for a upstream bug report.

**Comment by Quackdoc** [comment]
@martinlindhe i have time today so I can bisect it later. do you have a known good commit or just the timeframe?

**Comment by martinlindhe** [comment]
> @martinlindhe i have time today so I can bisect it later. do you have a known good commit or just the timeframe?

Unfortunately I have no more details :(

**Comment by Quackdoc** [comment]
I was able to bisect the issue, the report is here https://gitlab.freedesktop.org/mesa/mesa/-/issues/10963 @woelper I can close this since this isn't an issue with oculante, but it might be nice to keep it open for tracking

**Comment by Quackdoc** [comment]
this was solved sometime in the past, possibly with c2c3d306

**Comment by paulcarroty** [comment]
Still actual on 0.8.22 & Sway 1.9: `Error: "[3009] arguments are inconsistance"`.

**Comment by paulcarroty** [comment]
@Quackdoc Clear Linux with Mesa 24.

**Comment by Quackdoc** [comment]
can you try 

A) recompiling occulante git (I think this was solved here) here is a build of the latest commit with gnu https://files.catbox.moe/zahmhx
B) try mesa-git 

but im on both and it's working for me

**Comment by paulcarroty** [comment]
```
 ./oculante
[2024-05-31T12:26:24Z ERROR oculante] Could not load settings: No such file or directory (os error 2)
[2024-05-31T12:26:24Z ERROR sctk_adwaita::config] XDG Settings Portal did not return response in time: timeout: 100ms, key: color-scheme
warning: queue 0x55ff473b5b50 destroyed while proxies still attached:
  xdg_wm_base@26 still attached
  wl_output@15 still attached
  wl_seat@14 still attached
  xdg_activation_v1@13 still attached
  wp_fractional_scale_manager_v1@12 still attached
  wp_viewporter@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zwp_pointer_constraints_v1@9 still attached
  zwp_relative_pointer_manager_v1@8 still attached
  zxdg_decoration_manager_v1@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
Error: "[3009] arguments are inconsistance"
```

Mesa here is pretty fresh, but I'll try to test it on Rawhide or something.
