### ISSUE TITLE
File path should priorities the tail 

### ISSUE THREAD

**Issue by Jerakin** [woelper/oculante#3]
Long paths are not fully visible inside the view. When this happens it would be nice if the path trails the front of the path so that we see something like this `...project/build/output/feature/github/image.webp` instead of a path like this `Home/Jerakin/Documents/repositories/project/build` that's cut off by the window.

**Comment by woelper** [comment]
This is partly improved in 0.4.11 with smaller fonts and will be further improved later hopefully.

**Comment by woelper** [comment]
File path is now just the base filename, not the full path. The window title bar now displays the full path.
