### ISSUE TITLE
(Windows) new instance launches a visible terminal window since v.15

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#300]
Instead of just launching a single oculante window, seems like some debug setting is on? it has `INFO  notan_glow` and `INFO  oculante Successfully loaded previous settings.` messages there

**Comment by woelper** [comment]
Thanks for reporting this. This seems to be the kind of issue I tend to overlook as I am not primarily working on Windows - also this is not caught by any unit tests. I'll check!
