### ISSUE TITLE
(Windows) can't set window to 0,0 position

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#301]
For example, if I set `"window_geometry":[[0,0],[200,200]]`, it's always reset to something like `"window_geometry":[[38,38],[200,200]]` (or sometimes `76` or sometimes `114`, so all seem to be a multiple of 38)

**Comment by woelper** [comment]
Hi! Are you talking about modifying the configuration file?

Currently, only the window **size** is read from the configuration file, the position is ignored.

The reason for this is potential bugs/problems with changing display resolutions and external monitors. I am pretty sure that disconnecting external monitors and other resolution-related actions would lead to a condition where a position is stored that is not on the physical screen. Until I have figured out an easy and reliable way to prevent that, I have decided not to load the position. I am storing it though.

**Comment by eugenesvk** [comment]
Yes, the config files. So currently there is no way to prevent the window from at least jumping around?
Curious how the multi-monitor bug manifess, you can't move  a window to an illegal position, right, so do you get a single top-left pixel in the bottom-right corner if you're missing the monitor that would be logically "bottom/right" of the main one?

**Comment by woelper** [comment]
>  So currently there is no way to prevent the window from at least jumping around?

What do you mean by that? Is that a separate issue? When is it "jumping around"?

> Curious how the multi-monitor bug manifess, you can't move a window to an illegal position, right, so do you get a single top-left pixel in the bottom-right corner if you're missing the monitor that would be logically "bottom/right" of the main one?

You have a 1920x1080 display, move the window to 3500,1500 on your secondary monitor, then close oculante, disconnect your laptop. Next time you open oculante, it will try to open off screen.

**Comment by eugenesvk** [comment]
I mean that the position of the window changes every time I launch the app. I thought it was tied to the app not respecting the corner coordinates, but maybe it's a separate one

**Comment by eugenesvk** [comment]
I'm launching without any window managers. Also other apps are not jumping around, but not sure if any of them uses Wininit. Tried simp (if I recall correctly, it's also egui, so also winit?) and it seems to have the same issue (only it doesn't support remembering window size which your app does.

Maybe it's due to the fact that you ignore the position and so winit does some random stuff? So maybe add an option to override the multimonitor safeguard and always read position from config (and if it's outside, let the OS force it back to whatever place)?

**Comment by woelper** [comment]
I am closing this as this seems to be a quite special use case and is very likely something that may be beyond my control (winit / egui)
