### ISSUE TITLE
MacOS: Command-Minus and Command-Plus make the UI elements get blurry and get sharp

### ISSUE THREAD

**Issue by bean-z** [woelper/oculante#304]
**Describe the bug**
Holding Command-Minus makes the oculante app UI (text and menus, not the image being displayed) get blurry (pixellate), and holding Command-Plus makes the app UI get sharp. The problem persists even when the keyboard shortcuts section of the preferences menu is open.

**To Reproduce**
1. Open the app.
2. Hold Command-Minus for a few seconds.
3. Hold Command-Plus for a few seconds.

**Expected behavior**
The UI elements should not change size. Nothing should happen when I hold Command-Minus or Command-Plus, because my preferences don't use those keyboard shortcuts. (My zoom image shortcuts are Minus and Plus.)

**Screenshots / sample files**
In the video I start by doing the regular zoom in and zoom out (Minus and Plus), then start holding Command-Minus and then Command-Plus. I use the right Command key, which oculante calls RWin.
https://github.com/woelper/oculante/assets/143631489/01232590-bee7-4372-829e-748b19bcddf4

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Sonoma 14.4.1

**Additional context**
My guess is that Command-Minus makes the UI elements shrink ("fake" low resolution) while the app constantly fits the UI elements from their fake low resolution to a specific size, causing a pixellation effect as if the app were enlarging an image with an actually low resolution.

**Comment by woelper** [comment]
Found it - it was a change in egui. It is fixed now.
