### ISSUE TITLE
Oculante does not load single-channel EXR images

### ISSUE THREAD

**Issue by matteoscopel** [woelper/oculante#317]
**Describe the bug**
When opening EXR images that feature a single channel (a grayscale map), Oculante's loading indicator keeps spinning, but the image is not loaded. If I open an EXR image that has three channels, it opens regularly.

**To Reproduce**
1. Open a grayscale image.
2. Oculante does not manage to load it.

**Expected behavior**
I'd expect the image to load, showing the single channel it has.

**Screenshots / sample files**
[example.zip](https://github.com/woelper/oculante/files/15254505/example.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2

**Comment by woelper** [comment]
Thanks for adding the example!

Right now, I am expecting these images as rgba. I am going to see if I can change that. I also discovered (thanks to you!) that I did not properly propagate the error, so the spinner kept being active.

**Comment by woelper** [comment]
Hi!

Please try with this release:
https://github.com/woelper/oculante/releases/tag/0.8.20

Please let me know if you encounter any other images that are not able to load. Thanks for this issue!

**Comment by matteoscopel** [comment]
Fantastic, I confirm it works, thank you so much!

**Comment by woelper** [comment]
Nice, thanks for testing!
