### ISSUE TITLE
Oculante on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [woelper/oculante#32]
Hi,

After some minor hick-ups (it needs a couple of external dependencies to build, namely `openssl`, `pkgconf` and `libX11`), I've managed to build and create a native NetBSD package for `oculante` 😄 

![2022-08-21-091037_1366x768_scrot](https://user-images.githubusercontent.com/90570748/185780147-a2c4c169-87e8-4242-b7a8-3d86f9d22e0c.png)

I'll import the package into our repositories in a couple of days, want to do some testing first to see if something is missing. But, a few thoughts, already now.
(1) Would be nice to rename 'logo' in the res directory to something more specific. I would like to install the icon into the systems apps directory but, I'm afraid it may be overwritten (or overwrite) by other packages if they also have an icon named 'logo'.

(2) You are most probably already aware of this but, leaving the build warning here for reference anyway,
```
warning: unused imports: `Gaussian`, `Lanczos3`
 --> src/ui.rs:5:28
  |
5 |     imageops::FilterType::{Gaussian, Lanczos3},
  |                            ^^^^^^^^  ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unreachable pattern
  --> src/image_editing.rs:72:13
   |
72 |             _ => write!(f, "Not implemented Display"),
   |             ^
   |
   = note: `#[warn(unreachable_patterns)]` on by default

warning: variable does not need to be mutable
  --> src/main.rs:45:9
   |
45 |     let mut window_config = WindowConfig::new()
   |         ----^^^^^^^^^^^^^
   |         |
   |         help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default
```

(3) When launching `oculante` from the terminal, I get the following `Error initializing logs: attempted to set a logger after the logging system was already initialized` but, the application launches and works just fine. Ideas, thoughts on how logs could be initialized?

Thanks for your work on this tool. I'll keep you posted as of when it will become available for users.

**Comment by woelper** [comment]
Thank you so much, this is exciting! I'll address the issues you found and let you know in this ticket. I think it might be good that I update the Readme with NetBSD build instructions as well.

**Comment by 0323pin** [comment]
> I think it might be good that I update the Readme with NetBSD build instructions as well.

No worries, I'll do a PR when everything is ready.

I wonder if something like this

```
#[cfg(target_os = "netbsd")]
    {
        window_config = window_config.lazy_loop();
    }
```

should be added to `main.rs`

**Comment by woelper** [comment]
- I now switched to Notan's (the "engine" I am using) own logging, avoiding the log issue.
- The icon has been renamed to `oculante.png`
- Warnings are gone

**Comment by woelper** [comment]
> > I think it might be good that I update the Readme with NetBSD build instructions as well.
> 
> No worries, I'll do a PR when everything is ready.
> 
> I wonder if something like this
> 
> ```
> #[cfg(target_os = "netbsd")]
>     {
>         window_config = window_config.lazy_loop();
>     }
> ```
> 
> should be added to `main.rs`

That could be a good point - I don't have NetBSD installed on a machine here, but the idea of that lazy loop is to save CPU resources. If you see oculante consume a lot of CPU ( more than 5%) with just displaying an image, it would be a great idea to do as you suggest.

**Comment by woelper** [comment]
It also might make sense to release a version for NetBSD on push, as I do for other platforms. There seems to be a github workflow now: https://github.com/vmactions/netbsd-vm

**Comment by 0323pin** [comment]
> That could be a good point - I don't have NetBSD installed on a machine here, but ...

No worries, I'll patch the build and see if the cpu usage drops a bit. Will let you know but, maybe only tonight.

> It also might make sense to release a version for NetBSD on push, as I do for other platforms.

I need to check if the resulting binary works when built with cargo.
The thing is, NetBSD installs binaries in slightly different locations, depending if they are part of base, part of X or, third party.
So, I need to tell rustc where to find them. For example, if I don't link libX11 at compile time, the resulting binary will fail to find the needed shared object, libX11.so

Give me time to test this. If, it works it would be great.

**Comment by 0323pin** [comment]
@woelper Thanks for 0.5.47, all warnings are gone.

Adding the following patch to the build reduces the initial CPU load,

```
--- src/main.rs.orig	2022-08-21 09:16:54.000000000 +0000
+++ src/main.rs
@@ -60,6 +60,11 @@ fn main() -> Result<(), String> {
         window_config = window_config.lazy_loop();
     }
 
+    #[cfg(target_os = "netbsd")]
+    {
+        window_config = window_config.lazy_loop();
+    }
+
     #[cfg(target_os = "macos")]
     {
         window_config = window_config.lazy_loop().vsync();
```

But, it increases with time anyway. Maybe, that's just how it is for now 😄 

I've also built a binary with cargo to test if it worked but, with this I get

```
Error: "Received multiple errors. Errors: `[NotSupported(\"lacking either libGL or libEGL so could not fallback to other\"), NotSupported(\"both libGL and libEGL are not present\")]`"
Exception: oculante exited with 1
```

But, of course the libraries are there,
```
/usr/X11R7/lib > ls | grep libEGL
.r--r--r-- root wheel 350 KB Fri Aug 19 17:55:36 2022 libEGL.a
lrwxr-xr-x root wheel  13 B  Fri Aug 19 17:55:36 2022 libEGL.so ⇒ libEGL.so.0.0
lrwxr-xr-x root wheel  13 B  Fri Aug 19 17:55:36 2022 libEGL.so.0 ⇒ libEGL.so.0.0
.r--r--r-- root wheel 195 KB Fri Aug 19 17:55:36 2022 libEGL.so.0.0
.r--r--r-- root wheel 382 KB Fri Aug 19 17:55:36 2022 libEGL_p.a
/usr/X11R7/lib > ls | grep libGL.a
.r--r--r-- root wheel 892 KB Fri Aug 19 17:55:36 2022 libGL.a
```

else, it wouldn't work when I build it within the package framework.

Regards

**Comment by 0323pin** [comment]
@woelper Merged, http://mail-index.netbsd.org/pkgsrc-changes/2022/08/22/msg259015.html

CPU usage is astonishingly high after a few minutes. The lazy_loop works only for the initial image display.

**Comment by woelper** [comment]
Thank you so much for you work. It's strange however that CPU usage increases over time. As I use an immediate mode UI, it does quite some things if you interact with the window (hover over it, for example) so you could see varying CPU usage. If the window just sits there, you should however not get high CPU usage.

There is a bug/issue though if you have no image loaded at all - in this mode the application redraws each frame, which causes higher CPU usage. I'll put in a ticket and fix that later.

Thank you again for all the effort and great feedback. if you find out more about the high CPU usage please let me know!

**Comment by 0323pin** [comment]
> As I use an immediate mode UI, it does quite some things if you interact with the window (hover over it, for example) so you could see varying CPU usage. If the window just sits there, you should however not get high CPU usage.

This describes exactly what I see. Without the lazy_loop opening an image and doing nothing will give a CPU usage of about 30%. Adding the lazy_loop will keep it at about 1.5%.

Now, I use `leftwm` (tiling window manager), if I send the window to another tag (workspace) the CPU usage remains at about 1%. But, if I change to that tag and start playing with it, the CPU usage will increase with time. In about 1min, I'm over 100%.
Now, that might be something with how we look at it, I can easily get 200% of CPU usage while compiling 😄 

Anyway, feedback ... awesome tool for image manipulation. Not much I was aware of aside from GIMP.
I usually just use `feh` and `stitchy`, link in case you've never heard of it https://github.com/grimace87/Stitchy, but I see myself using `oculante`.
Hopefully CPU usage can be controlled in the near future, as I see it, nice (bloatware free) alternative to GIMP ❤️

**Comment by woelper** [comment]
Thank you so much for your feedback!
The CPU usage issue is really strange. I wonder if it's related to the tiling WM? On my linux/win/mac test systems, CPU returns to 0-1% if I stop interacting, and to around 10% if I do basic image viewing tasks, like zoom/pan, even after a long time. I'll do some more research on older hardware and installed NetBSD in a VM (can it be installed to a USB stick easily by the way?).

Are you testing with a release build (`cargo run --release`) by the way? The performance difference in rust is often drastic.

**Comment by 0323pin** [comment]
> The CPU usage issue is really strange.

Yes, and it gets even more strange.

> I wonder if it's related to the tiling WM?

So, I've installed `openbox` and tried it on it. CPU behaves as you describe it does for you 😮 

Then I installed `frankenwm` and it behaves the same as `leftwm`, _i.e._ CPU goes up all the time. Something with `oculante` window drawing and tiling is wrong but, I don't know enough at this low level to even guess what.

I don't know if you ever used a tiling window manager but, on both tiling wm's I've tested the worst you can do is send the `oculante` window to another tag (workspace), if I do this the CPU usage goes over the roof really quick.

Before you go ahead and try to install NetBSD, you could check the behavior with a tiling wm.

> Are you testing with a release build (cargo run --release) by the way?

As said, I need to build the app within the pkgsrc framework and link the relevant libs at compile time. If I simply pull the tarball into my home directory, unpack it and build with `cargo`, the build itself works but the resulting binary doesn't because it can't find the needed shared objects in the system, even though they are there.

Anyway, yes. When building within pkgsrc the build is done with `cargo build --offline --release -j${_MAKE_JOBS_N}`.

**Comment by 0323pin** [comment]
@woelper Btw, are the linux binaries compiled against GlibC? I have a Linux box with a tiling wm but, it runs on musl-libC.

**Comment by 0323pin** [comment]
@woelper So, I've built `oculante`-0.5.47 on my linux machine using `cargo build --release`, I use a LeftWM on this machine also.

CPU usage is slightly lower to start with but, once I sent the window to another workspace it triggers the bug. Actually, if I move that workspace and back to where I have top running CPU usage is above 95%, so even higher than on NetBSD.

I wonder what it's triggering this with tiling window managers?

**Comment by woelper** [comment]
Thanks for checking, @0323pin !
This could be an issue with one of the libraries I am using, notan, or oculante itself. I've tried tiling mode in Pop_OS, but saw no increased cpu usage. I'll try with some other tiling WMs later.

I am wondering if `window_config = window_config.lazy_loop().vsync();` will make a difference. My guess is that something in the WM is causing the application to receive an event, like resize, and causes a redraw. Without vsync, this will happen as fast as your GPU can draw, so maybe limiting it to 60 fps is making it at least a bit better with a tiling WM.

**Comment by 0323pin** [comment]
Thanks for your suggestion,

> wondering if window_config = window_config.lazy_loop().vsync(); will make a difference

I'll re-patch the build tomorrow and see if it fixes it 😄 

> I've tried tiling mode in Pop_OS, but saw no increased cpu usage

I don't really know how Pop integrates tiling into gnome but, if I suspect it's a script on top of metacity, so not a real tiling wm. Anyway, I got the same behavior with two different tiling wms (leftwm, written in rust and frankenwm, written in C) and two different OSs, NetBSD and Void Linux. So, I don't know if you need to try any further.

> My guess is that something in the WM is causing the application to receive an event, like resize, and causes a redraw.

Good point. I'd guess this happens quite a lot on tiling wms. Actually, the fact that if you leave the window alone doesn't trigger it, could indicate that it might just be the case.

I'll let you know how it goes with `vsync` enabled.

**Comment by 0323pin** [comment]
@woelper Good news 😄 
Adding `vsync` fixes the issue, I can now send the window to another workspace without issues.
I think it should be added to the Linux line also, as the behavior was the same when using a tiling window manager.

Now, if you don't mind one last thing.
I can't seem to be able to reach/see the graph on the lower left corner. I could on my Linux system since it has a larger monitor but, it gets cut-off on smaller resolutions.

![2022-08-24-062314_1366x768_scrot](https://user-images.githubusercontent.com/90570748/186329230-b6b882db-d2ff-4709-84dd-182fa7a91209.png)

**Comment by woelper** [comment]
Thank you so much! Amazing to get some really good feedback. I placed the left info UI in a scroll container and made a sub-menu for the alpha tools - this will make it more obvious that there is more content and increase the chance of the histogram showing on smaller monitors. I also released a new version with the changes and merged your PR (thanks!).

**Comment by 0323pin** [comment]
Thanks! I'll update the package as soon as possible, these are really nice improvements.
Also, I can remove our local patch.

Shall we close this issue?

**Comment by woelper** [comment]
I think we can. Thank you so much, and feel free to open new issues if you have any ideas and comments!

**Comment by 0323pin** [comment]
Don't worry, I will 😄 
Thanks for your fixes!
