### ISSUE TITLE
Allow configurable min window size

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#333]
**Is your feature request related to a problem? Please describe.**
Sometimes (especially for tiny images like icons that can be 24x24) I'd like to compare an image an app to the actual one, so it's best to minimize the window size to only fit the image, no more

**Describe the solution you'd like**
Allow configuring min. window size

**Describe alternatives you've considered**
Not sure

**Additional context**
A recent update set the min to 100,100 https://github.com/woelper/oculante/issues/325
While I think that's fine to have some default to avoid other issues, it'd be better to have it configurable for other use cases

**Comment by woelper** [comment]
I love obscure use cases like these, consider it done!
