### ISSUE TITLE
No dependencies in Cargo.lock for build with options: --no-default-features notan/shaderc

### ISSUE THREAD

**Issue by yurivict** [woelper/oculante#334]
**Describe the bug**
These items are missing:
```
                shaderc-0.8.3 \
                shaderc-sys-0.8.3 \
                roxmltree-0.14.1
```

**Desktop (please complete the following information):**
 - OS: FreeBSD 14.0
 - Version 0.8.22

**Additional context**
Building in the FreeBSD ports framework.

**Comment by woelper** [comment]
I don't think I understand this issue, could you elaborate please?

**Comment by yurivict** [comment]
The project depends on shaderc, but shaderc doesn't appear in Cargo.lock

**Comment by woelper** [comment]
The project only depends on shaderc if you enable the `notan/shaderc` feature flag, otherwise it does not. `notan/glsl-to-spirv` is the default feature as that covers most operating systems, so I think it is expected that Cargo.toml does not contain anything that is related to shaderc.

**Comment by yurivict** [comment]
Documentation says [here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) that ```[features]``` syntax should be used in such case:
```
[dependencies]
foo = { version = "1.0", optional = true }
bar = { version = "1.0", optional = true }

[features]
fancy-feature = ["foo", "bar"]
```

This can probably be done with some cargo command, but I don't know cargo enough.

**Comment by woelper** [comment]
Yes, features are currently used for this:

https://github.com/woelper/oculante/blob/57299c42f36dcea36a3d785e77a617882dd8976b/Cargo.toml#L94

**Comment by Stoppedpuma** [comment]
Build should work fine with a build command similar to `cargo run --no-default-features --features notan/shaderc`.
