### ISSUE TITLE
error[E0599]: no variant or associated item named `get_mouse_position` found for enum `mouse_position::mouse_position::Mouse` in the current scope

### ISSUE THREAD

**Issue by yurivict** [woelper/oculante#335]
**Describe the bug**
Build fails with options "--no-default-features notan/shaderc":
```
error[E0599]: no variant or associated item named `get_mouse_position` found for enum `mouse_position::mouse_position::Mouse` in the current scope
    --> src/ui.rs:2181:35
     |
2181 |             let position = Mouse::get_mouse_position();
     |                                   ^^^^^^^^^^^^^^^^^^ variant or associated item not found in `Mouse`
```

**Desktop (please complete the following information):**
 - OS: FreeBSD 14.0
 - Version 0.8.22

**Comment by woelper** [comment]
Oh, thanks! These are libraries that do not work on NetBSD. I've excluded certain features such as borderless mode for those operating systems. In this case, I've used `#[cfg(not(target_os = "netbsd"))]`. But apparently, FreeBSD is not equal to NetBSD!

**Comment by yurivict** [comment]
Everything that is related to mouse position should work the same way on FreeBSD as it works on Linux.

**Comment by woelper** [comment]
Unfortunately, it does not. I've added an issue here to ask for support:
https://github.com/fayez-nazzal/mouse_position/issues/3

**Comment by yurivict** [comment]
FYI:

fayez-nazzal/mouse_position actually works fine on FreeBSD if the OS limitations are removed in its code.

I've added [these patches](https://cgit.freebsd.org/ports/tree/graphics/oculante/files) and Oculante has successfully built on FreeBSD.

Now Oculante is available as a FreeBSD port.

**Comment by woelper** [comment]
Sorry for the late reply! You are amazing. Good to hear that!
Would you think that adding these patches as a PR to mouse_position makes sense? If they accept that we could get rid of the requirement to patch your port.

Great work and exciting to see it added as a port!

**Comment by woelper** [comment]
Can I close this issue now?

**Comment by yurivict** [comment]
Thank you!

I'll add the PR for fayez-nazzal/mouse_position.

Closing this issue.
