### ISSUE TITLE
ERROR rfd::backend::xdg_desktop_portal

### ISSUE THREAD

**Issue by 0323pin** [woelper/oculante#341]
**Describe the bug**
File browsing from the UI doesn't work on NetBSD.

**To Reproduce**
1. Build 0.8.22 from source within pkgsrc
2. Launch oculante and try to open using the browse icon
3. See error

`2024-05-20T06:58:19Z ERROR rfd::backend::xdg_desktop_portal] pick_file error No such file or directory (os error 2)`

It works fine giving the path on the command line.

**Comment by woelper** [comment]
Thanks! It is strange that this is a runtime error and succeeds to compile. I've long wanted to get rid of rfd (the native file picker) and made my own - you can use it by not building with the `rfd` feature, for example
`cargo run --no-default-features --features notan/glsl-to-spirv` and you should get something like this:

<img width="928" alt="image" src="https://github.com/woelper/oculante/assets/3613791/a4d4116a-2fbf-40e0-a191-b5159aee2961">

I haven't been brave enough to make it the default, but some day I might...

**Comment by 0323pin** [comment]
Cheers.
I'll try that in the coming days. I've merged the update, https://mail-index.netbsd.org/pkgsrc-changes/2024/05/20/msg300466.html already but, can of course change it. Thanks for the hint.

**Comment by woelper** [comment]
Yeah, thanks for your flexibility! I am figuring some of this out as well. There is now an unpleasant amount of combinations depending on operating systems and features flags that can fail.

The good news is that as the rust ecosystem matures, there will be less and less need for packages that wrap existing libraries which are hard to build and statically link against. Hopefully this will improve. Also I feel I should be getting some actual machine with some BSD on it to test - I'll have a look at some old hardware I did not throw out yet!

**Comment by 0323pin** [comment]
@woelper That's it! I'm making this the default on the NetBSD package 👍 

![2024-05-21-071859_1366x768_scrot](https://github.com/woelper/oculante/assets/90570748/4abfbde8-abb8-4b9f-8692-8ebf58a7ad49)

> Also I feel I should be getting some actual machine with some BSD on it to test - I'll have a look at some old hardware I did not throw out yet!

Perfect opportunity 😄

**Comment by 0323pin** [comment]
Closing this for now.

**Comment by 0323pin** [comment]
For your reference, https://github.com/Kl4rry/simp/issues/34 and https://github.com/PolyMeilex/rfd/issues/201
