### ISSUE TITLE
"Show checker background" option doesn't work"

### ISSUE THREAD

**Issue by Cosebdd** [woelper/oculante#345]
**Describe the bug**
Toggling  Preferences->"Show checker background" doesn't do anything

**To Reproduce**
1. Go to Preferences
2. Click on "Show checker background"

**Expected behavior**
I expected checker background

**Screenshots / sample files**
If applicable, add screenshots to help explain your problem. You can also attach problematic images here to help test the bug. Please pay attention to image copyright.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.8.22 Release

![oculante_2024-05-30_13-38-47](https://github.com/woelper/oculante/assets/7452950/9ed88f06-b822-45f2-aaa2-0394cdf967fc)
**Additional context**
GIF with a reproduction is attached

**Comment by woelper** [comment]
The checker background only works if the image has transparency. It is shown if a pixel is transparent.

<img width="928" alt="image" src="https://github.com/woelper/oculante/assets/3613791/6a54856a-8d6d-4e22-8a7a-7f85e04c0ff6">
