### ISSUE TITLE
A JPG file starting with 0x52 0x49 can't be opened

### ISSUE THREAD

**Issue by Cosebdd** [woelper/oculante#346]
**Describe the bug**
TurboJPEG returns an error that the file is not a JPG file because it starts with 0x52 0x49. It seems that it is actually a WebP file disguised as JPEG. Nevertheless, Windows Photo Viewer and MS Photos don't have any problem opening this file.

**To Reproduce**
1. Download the attached file
2. Try opening with Oculante

**Expected behavior**
Oculante should parse the format and render the file

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.8.22 Release

**Additional context**
The file 
[Plan_kluba.zip](https://github.com/woelper/oculante/files/15499338/Plan_kluba.zip)

**Comment by Quackdoc** [comment]
this would require reading the image's bytes first to indentify the type of file the `file-format` https://github.com/mmalecot/file-format crate should work for this

**Comment by woelper** [comment]
First of all, thanks for raising the issue. I understand the need, but I think this issue should probably be named "A WebP file with a jpeg extension can't be opened". Oculante is, or was at least, meant to examine and verify images. As a user, I'd like to know if an image has the wrong extension, even if some viewers are able to open them. At the very least, a warning should be displayed that the image extension is wrong.

I will probably have to add support for this anyways to detect any image coming over the network, as requested here: https://github.com/woelper/oculante/issues/323

**Comment by Stoppedpuma** [comment]
> At the very least, a warning should be displayed that the image extension is wrong.

UX wise it would probably be smart to still open the image but show a warning as well.

**Comment by woelper** [comment]
This is now implemented in https://github.com/woelper/oculante/pull/358.

The file is now probed for the type. If there is a mismatch, a warning will be displayed in the ui.
