### ISSUE TITLE
The executable icon on Windows is only available in 48x48px

### ISSUE THREAD

**Issue by Cosebdd** [woelper/oculante#347]
**Describe the bug**
The icon of the executable is 48x48 despite the ico file being 128x128.
Maybe having a [multi-res icon](https://superuser.com/questions/491180/how-do-i-embed-multiple-sizes-in-an-ico-file) could resolve the issue.

**To Reproduce**
1. Go to a directory where oculante.exe is located
2. Do Ctrl+Mousewheel

**Expected behavior**
The executable icon should scale correctly. 
Also, it should look smoother like the original ICO file.
Another suggestion is to have a 256x256 since it is available in the SVG format.

**Screenshots / sample files**
![explorer_2024-05-31_14-14-34](https://github.com/woelper/oculante/assets/7452950/ec00acb2-64fd-439d-a4a7-968664623003)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.8.22 Release

**Comment by woelper** [comment]
Thanks! Nice idea. This is hopefully easy to do. If you want to try a PR, here is the conversion:

https://github.com/woelper/oculante/blob/63e2234e0f79192e7c78314c24b2c16cfa012219/build.rs#L79
