### ISSUE TITLE
Can't open JPG files made on Sony NEX-3N

### ISSUE THREAD

**Issue by Cosebdd** [woelper/oculante#351]
**Describe the bug**
Oculante won't open a JPG file made on Sony NEX-3N showing "Unsupported file". Windows Photo Viewer and MS Photos open it without a problem.

**To Reproduce**
1. Try opening the attached file

**Expected behavior**
Oculante should be able to open such a JPG file.

**Screenshots / sample files**
If applicable, add screenshots to help explain your problem. You can also attach problematic images here to help test the bug. Please pay attention to image copyright.
The sample file:
[DSC01720.zip](https://github.com/user-attachments/files/15525503/DSC01720.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Both 0.8.22 Release and the latest built from source

**Comment by woelper** [comment]
Strange. This image opens fine on Linux. I will need to check on other operating systems.

**Comment by Cosebdd** [comment]
I looked at it closer and figured out the problem. The camera creates files with a "JPG" extension (all caps). After changing it to "jpg" I could open the file.

I prepared a PR that fixed the issue for me.

**Comment by Cosebdd** [comment]
This also shouldn't be a problem anymore after #323 is fixed
