### ISSUE TITLE
Ability to close images

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#355]
**Is your feature request related to a problem? Please describe.**
This becomes a problem when comparing multiple images, being able to close those which I've ruled out is extremely helpful and is my main reason for keeping imv around. Introducing this feature makes managing large image sets for comparison a lot easier.

**Describe the solution you'd like**
The ability to close images like imv when pressing x, this basically just skips the image when going past it.

**Comment by woelper** [comment]
I don't fully understand - in a single instance, you want to remove the current image from memory and stop displaying it? Or are you talking about removing images from the compare list? Both would be easy to do. I can also add a browse button directly to the compare list if that helps.

**Comment by Stoppedpuma** [comment]
I completely forgot the compare menu existed, I meant from memory but having the option to remove from the compare list as well is probably expected anyways? Here's a video showing how imv handles closing images:


https://github.com/woelper/oculante/assets/58333920/48adf3ad-fb8f-4928-b3d1-57680f036f5a

**Comment by woelper** [comment]
I have added support for this together with improved compare mode here:
https://github.com/woelper/oculante/pull/357

**Comment by woelper** [comment]
![image](https://github.com/woelper/oculante/assets/3613791/350d4676-6134-44dc-8ad0-d0d53fe56921)

There are a couple of improvements:
- There was a bug if you have cache disabled. It now works, but there is a warning message as no cache makes comparing images slow (they have to be reloaded from disk)
- You can close individual images
- If you pan or zoom an image, there is a button asking you to update the compare entry. Compare mode stores the image path **and** the position/scale, so you can compare regions between images.
- The option to close all images in the list is only shown if there are images in it
- There is a direct option to load new images from the compare menu
