### ISSUE TITLE
Cannot show images without file extension

### ISSUE THREAD

**Issue by martinlindhe** [woelper/oculante#360]
**Describe the bug**
If image.jpg shows in oculante, then it will fail to show if i remove the file extension.
Tested quickly with jpg and bmp files.

**To Reproduce**
1.View image.jpg with oculante
2. Rename to image
3. Try to view it again
4. See error "Unsupported file"

**Expected behavior**
Since oculante is associated with this mimetype, I expected it to handle the image no matter the file name.

**Desktop (please complete the following information):**
 - Linux, oculante 0.8.22

**Comment by woelper** [comment]
This is related to https://github.com/woelper/oculante/issues/346.
This should be easily fixed if it isn't already by that change.

**Comment by martinlindhe** [comment]
I just tried a compile from the master branch, but the same issue persist.

**Comment by woelper** [comment]
Hi!
The changes are currently here:
https://github.com/woelper/oculante/tree/any_extension

**Comment by woelper** [comment]
This should now be fixed in master. The open dialog might still filter these out, but associating or opening images from the command line should work if they don't have an extension.
