### ISSUE TITLE
ClearImage clears all images instead of only the current image.

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#365]
**Describe the bug**
Clear image clears all images

**To Reproduce**
1. Open folder with multiple images
2. Click Clear images (or use keybind)
3. Reproduced

**Expected behavior**
Only the current image to clear, not all images.

**Desktop (please complete the following information):**
 - OS: Arch Linux, Hyprland (Wayland compositor)

**Comment by woelper** [comment]
This is expected, as the current path is also cleared. Without this, oculante has no idea if there are other images.

**Comment by woelper** [comment]
Yeah, after you clear the current image, you would have to reopen one. There is no concept of a folder. I could _not_ clear the current path. This would let you still advance to the next or previous one. It depends what you are after with the clear button. If it is meant to fully unload the image and reset the viewer to the default state, it does what it should. If you only want to clear the texture memory, the button does too much.

I think this might have been specific to your use case of using multiple instances to compare. I was thinking that this button would remove anything related to the current image, in which case I think it is correct to lose any memory of other images.

**Comment by Stoppedpuma** [comment]
> I could not clear the current path. This would let you still advance to the next or previous one

Yeah, this is what I meant, this ones my fault since I should have explained better. Here's a written example of how this should work to follow imvs implementation:

Original
<example-1> <example-2> <example-3> <example-4>

Clear example-3

<example-1> <example-2> <example-4>

Basically if example 3 is cleared then it should unload, going from example-2 to example-4.

Let me know if you're still not understanding me

**Comment by woelper** [comment]
Oh I think I understand. You want the application to remember all images in a folder like in a timeline and want to be able to remove individual ones completely? So the image would not be loaded again, even if going back from example-4 or forward from example-2?

**Comment by Stoppedpuma** [comment]
Yes, sorry for the confusion!

**Comment by woelper** [comment]
This might require a bit of rewiring. May I ask what use case this has / what problem you are trying to solve with this feature?

**Comment by Stoppedpuma** [comment]
This is a feature I use pretty much daily in imv and is especially useful in tasks such as graphic design related tasks, yes the compare menu works for smaller image sets such as ~15 images but when it comes to large sets with over 50-100 images it's easier to just be able to clear one image at a time.

The problem with continuing to use imv for this task is that imv is unmaintained and basically a dead project at this point with no support for modern image formats such as JPEG-XL and various other issues such as crashes and nearly unusable performance with SVGs. This is where oculante comes into the picture, it has support for most design review related tasks I need in an image viewer and is useable across multiple operating systems.

**Comment by woelper** [comment]
Thank you for the context. 

I completely forgot that I changed my implementation to use a scrubber / timeline already and for that reason keep an index. I can remove individual elements from it, I just need to do a little bit of plumbing. This will likely also simplify the code and speed up the application, especially for animated images.

**Comment by woelper** [comment]
You can check out the new functionality now in master if you wish. Do you have thoughts on "removing an image shifts to the next"?

**Comment by Stoppedpuma** [comment]
Thanks a lot! This now works as I intended.

> Do you have thoughts on "removing an image shifts to the next"?

I agree it's rather jarring to just be blank on clear and shifting to the next / previous image would be nice, is it possible to have this based on the direction the user last went? Basically if the users last input before clearing was to the next image then display the next image and vise versa?

**Comment by Stoppedpuma** [comment]
Also additional edge case, using the keybind doesn't work correctly, it just blanks the current image. Video below shows this behaviour with example-2 (red):

https://github.com/woelper/oculante/assets/58333920/74486795-ead8-4f7c-9956-3718b32a475a

**Comment by woelper** [comment]
> I agree it's rather jarring to just be blank on clear and shifting to the next / previous image would be nice, is it possible to have this based on the direction the user last went? Basically if the users last input before clearing was to the next image then display the next image and vise versa?

Shifting to the next / prev is actually easier, that is why I asked :). I might have to store more state info if this needs to remember the last command. I am a bit reluctant to do that, as this is another source for things to go wrong (I am trying to keep things simple where possible). Maybe there is a clever workaround I can think of.

**Comment by Stoppedpuma** [comment]
> I am a bit reluctant to do that, as this is another source for things to go wrong

Rather large suggestion but it might be worth setting up some tests to prevent future issues and to keep code quality in-check.

**Comment by woelper** [comment]
There are a couple of tests, but especially UI tests are hard and I am not a big fan of doing those. 

I have good news - I've made a `Direction` enum on the scrubber, so the app knows in which directions you are shifting. When you remove an image this is taken into account. The same is re-used for the delete operation.
This also fixes the issue with the keybind.

This is fixed since https://github.com/woelper/oculante/commit/a0b7dc5a20a7966fc1b53a1cf4b6496c2a06cc9f.

I am closing this now, feel free to re-open. Thanks again for the suggestion - looking at this thread and the code, I think this has improved UX and quality.
