### ISSUE TITLE
Inkscape SVGs can't be displayed

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#371]
**Describe the bug**
Inkscape SVGs are read as XML and cannot be displayed

**To Reproduce**
1. Open inkscape SVG
2. Reproduced

**Expected behavior**
Inkscape SVGs to be able to be displayed

**Screenshots / sample files**
![image](https://github.com/woelper/oculante/assets/58333920/33f8c855-9e16-4628-ba6c-2396987843a2)

**Desktop (please complete the following information):**
 - OS: Arch Linux, Hyprland (Wayland compositor)

**Comment by woelper** [comment]
Good spot. This was because of the format identification that was added earlier. This was auto-detected as XML.
