### ISSUE TITLE
Theme accent colour is preserved after switching between them

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#375]
**Describe the bug**
Switching to light and then back to dark theme keeps the blue accent colour.

**To Reproduce**
1. Switch to opposite theme
2. Switch back
3. Reproduced

**Expected behavior**
Accent colour to return back to the correct colour.

**Screenshots / sample files**

![image](https://github.com/woelper/oculante/assets/58333920/a7acf223-094c-4ae0-95cf-eb814d2b1289)

**Desktop (please complete the following information):**
 - OS: Arch Linux, Hyprland (Wayland compositor)

**Additional context**
Should probably follow the accent colour anyways? Or have a separate changeable accent colour for dark and light themes for the user to set.

**Comment by woelper** [comment]
Accent color is designed to stay as it is. What would be the "correct" color in your case?

**Comment by Stoppedpuma** [comment]
While in dark mode it uses the chosen accent colour found here:

![image](https://github.com/woelper/oculante/assets/58333920/6a55e787-15d6-4f1b-bfa0-562db5e1c2ee)

Switching to light mode invalidates this which is fine but upon switching back it remains the blue from light mode until oculante is reopened.

**Comment by Stoppedpuma** [comment]
I apparently need to quit writing bug reports at midnight because I completely lose the ability to speak english to the point of where even I can't understand myself.

Here's a video to show what this bug report is about instead:

https://github.com/woelper/oculante/assets/58333920/842f6f9e-cb70-47c6-aed8-3230bc59f8ae

**Comment by woelper** [comment]
Ahhh! Cool! I get it!

No worries, better to write a bug report at midnight than to forget about it! :)

**Comment by Stoppedpuma** [comment]
Suggestion if you don't mind, would you be open to changing "Accent colour" to "Dark mode accent colour" and "Light mode accent colour" allowing for two different accent colours based on the theme, one for the dark theme and the other for the light theme?

**Comment by woelper** [comment]
I went with fixing the issue first. I think two accent colors would be more complex.
