### ISSUE TITLE
ClearImage sometimes skips over the next / previous image

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#378]
**Describe the bug**
ClearImage will sometimes skip the image it's supposed to go to next, E.g if I go from example-4 to example-5 and I clear example-5 it should go to example-6, sometimes it goes to example-7 instead.

**To Reproduce**
1. Clear image
2. Reproduced (sometimes)

**Expected behavior**
To go the next / previous image without skipping over one sometimes.

**Screenshots / sample files**

The video here shows it skipping to example-7 instead of going to example-6.

https://github.com/woelper/oculante/assets/58333920/4948bbfb-aeba-439c-99d2-cd297f8c7eb4

**Comment by woelper** [comment]
This should be fixed now.
