### ISSUE TITLE
ClearImage can go "out of bounds"

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#379]
Clearing all images leads to these errors:

ERROR oculante::image_loader] Can't determine image type
ERROR oculante::utils] No such file or directory (os error 2)

thread 'main' panicked at src/scrubber.rs:65:22:
removal index (is 4) should be < len (is 4)

**Comment by woelper** [comment]
Great catch. I had safe methods for these already, I was just too stupid to use them.
