### ISSUE TITLE
Hide trash icon when no images are available

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#380]
Causes this crash if pressed while no images are loaded:

ERROR oculante::image_loader] Can't determine image type
oculante::utils] No such file or directory (os error 2)

thread 'main' panicked at src/scrubber.rs:65:22:
removal index (is 0) should be < len (is 0)

Very easy to reproduce by clearing all images in a directory as the trash icon will still be there.

![image](https://github.com/woelper/oculante/assets/58333920/d43666a3-c162-4137-8db1-1d29230289f5)

**Comment by woelper** [comment]
I can't reproduce this on latest master. Is this fixed for you?

**Comment by Stoppedpuma** [comment]
Yep, thanks!
