### ISSUE TITLE
Going to the next / previous image can unload all images in a specific situation

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#385]
Not a clue why this happens, things work as intended when doing `oculante example/example-1.png`. Everything falls apart when going into the example directory and doing `oculante example-1.png`, the next / previous buttons seem to disappear as well.

How to reproduce step by step:

1. Create directory and put an image in it
2. cd into the directory
3. `oculante file.png`
4. Press next / previous keybind
5. Reproduced

`ERROR oculante::image_loader] Can't determine image type`
`ERROR oculante::utils] No such file or directory (os error 2)`

**Comment by Stoppedpuma** [comment]
Additionally instead of pressing next / previous on step 4, clearing the image instantly crashes oculante.

`thread 'main' panicked at src/scrubber.rs:70:22:`
`removal index (is 0) should be < len (is 0)`

**Comment by woelper** [comment]
I was able to reproduce this. Additionally I need to harden the scrubber code I think...

**Comment by woelper** [comment]
This should now be fixed in latest master.
