### ISSUE TITLE
EXIF rotation information should be addressed

### ISSUE THREAD

**Issue by kiyoon** [woelper/oculante#395]
**Describe the bug**
Some photos (especially from digital cameras) bake EXIF rotation information instead of making the aspect ratio actually vertical. Most image viewers read the information and rotate the view. It seems like Oculante doesn't do this and many of my photos are rotated.

**Desktop (please complete the following information):**
 - OS: macOS 14

**Comment by woelper** [comment]
This is a very good point. I am using the `image` library for loading most formats and have hoped for a long time to have exif / rotation support from it. Here are related upstream issues:
https://github.com/image-rs/image/issues/2222
https://github.com/image-rs/image/issues/1045

Maybe it is worth considering to rotate the images manually when loading.

**Comment by kiyoon** [comment]
In [zune-imageprocs](https://github.com/etemesi254/zune-image) there is an auto orient function but I'm not so sure if you can use it with `image-rs`.

**Comment by Shnatsel** [comment]
I'm working on Exif orientation support in `image` for use in [`wondermagick`](https://github.com/Shnatsel/wondermagick). 

I should get it working in the next few days, but there's no telling how long will it take to get the changes reviewed and released as part of `image`. You might have to just copy-paste some code if you need it ASAP.

**Comment by Shnatsel** [comment]
I got it working in `wondermagick`, but my implementation relies on several PRs not yet merged into `image`:
https://github.com/image-rs/image/pull/2291
https://github.com/image-rs/image/pull/2292

**Comment by woelper** [comment]
Wow! Firstly, wondermagick looks amazing!

Super cool you are adding this to image. Maybe all I have to do is wait then? Do you have experience with the time needed in image to merge PRs like yours? If that is a long time away, I might copy and paste some of your solution first.

Cheers!

**Comment by woelper** [comment]
That is amazing news, thanks!

If I recall correctly I am using some other crates that need to match the `image` crate I am using, so this might be difficult. Also I think I can't publish on crates.io with git dependencies unfortunately...

**Comment by Shnatsel** [comment]
`image` v0.25.4 with the orientation additions has been released. There is also a built-in function for extracting the orientation metadata, without requiring external crates such as kamadak-exif. See the [changelog](https://github.com/image-rs/image/blob/main/CHANGES.md) for more details.

**Comment by woelper** [comment]
You are amazing, and thank you for following up now that is released! I have to check if I can replace exif everywhere as I read maybe exif from more formats than `image` supports. But I'll update `image` asap!

**Comment by Shnatsel** [comment]
I see you're using kamadak-exif. You can keep using it for extracting Exif metadata and then use `image` to actually apply rotation, like this:

```rust
use image::{Orientation, DynamicImage, ImageReader, ImageDecoder};
use exif::{In, Tag}; // from `kamadak_exif`

let mut decoder = ImageReader::open("file.jpg")?.into_decoder()?;
let raw_exif = decoder.exif_metadata();
let mut image = DynamicImage::from_decoder(decoder)?;

// Parse Exif chunk (if present) and apply the orientation
if let Ok(Some(raw_exif)) = raw_exif {
    let reader = exif::Reader::new();
    let exif = reader.read_raw(raw_exif)?;
    if let Some(orientation) = exif.get_field(Tag::Orientation, In::PRIMARY) {
       if let Some(value) = orientation.value.get_uint(0) {
           if let Some(orientation) = Orientation::from_exif(value as u8) {
               image.apply_orientation(orientation);
           }
       }
   }
}
```

**Comment by woelper** [comment]
Wow, there is some other good stuff in the release notes. I can probably get rid of other external libraries such as fast blur. Exif support looks good as well!
I was naively expecting functionality to have some kind of auto rotation on load, but your example is much appreciated. I'll probably use the native exif functionality as I have hopes I can throw out kamadak-exif at some point, reducing the dependencies.

**Comment by Shnatsel** [comment]
> I was naively expecting functionality to have some kind of auto rotation on load

We couldn't add this in a point release because that would be a breaking change: if someone was already read Exif and rotate accordingly, auto-rotation on load would break their code.

> I have hopes I can throw out kamadak-exif at some point, reducing the dependencies.

You still need kamadak-exif to parse the extracted Exif chunk if you need things other than the orientation. But it's a robust library in 100% safe code, so I really don't see a good reason to remove it.

**Comment by woelper** [comment]
Thank you for taking the time to respond so quickly! That makes a lot of sense. I've got the rotation already working, and I actually like the flexibility with manually rotating. For JPG I am still using turbojpeg, so I have to manually rotate anyways. Maybe instead of doing this in all loaders I'll try to do this as a post process or generic step after loading is done.
