### ISSUE TITLE
oculante always got new access in mac

### ISSUE THREAD

**Issue by krakotay** [woelper/oculante#409]
**Describe the bug**
Every time when I open images on macos, oculante asks for new access permission no matter how many times I give it
**To Reproduce**
1. Open any image with oculante 
2. Close it 
3. Open again
Even if i press "don't allow", it open anyway
**Expected behavior**
That oculante ask just one time all permissions 
**Screenshots / sample files**
<img width="298" alt="image" src="https://github.com/user-attachments/assets/e3a83058-a1f9-45cb-848b-5e795439cca6">

**Desktop (please complete the following information):**
 - OS: MacOS
 - 14.6.1 

**Additional context**
No

**Comment by krakotay** [comment]
Ha-ha, when i compiled from source, all works fine... 
BTW, last mac version doesn't work and have weight just 1 kb.

**Comment by woelper** [comment]
I think this was recently introduced by Apple. When building the application yourself, this is not an issue. But if you download the app it becomes quarantined, as it is not signed. You can workaround it like this:

```
xattr -rd com.apple.quarantine oculante.app/
codesign --force --deep --sign - oculante.app/
```
I think unless I pay 99 bucks for a developer account per year and sign it, there may be no simpler solution.
