### ISSUE TITLE
Colour histogram gives up on 24-bit image

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#415]
A copy of this image can be downloaded [here](https://upload.wikimedia.org/wikipedia/commons/e/e9/16777216colors.png)

**Screenshots / sample files**
![image](https://github.com/user-attachments/assets/42186087-6214-458e-bc10-cc0f982ad125)

**Desktop (please complete the following information):**
Arch Linux, Hyprland (Wayland)

**Comment by woelper** [comment]
In Krita, the histogram looks like this:
![image](https://github.com/user-attachments/assets/c691fffd-caac-4caa-89ab-051511ec8dcf)


I think this is because the image has an equal distribution of colors maybe?

**Comment by woelper** [comment]
I think this is expected for this image.
