### ISSUE TITLE
Two flip filters do not combine correctly

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#418]
**Describe the bug**
Using two flip filters (one vertical, the other horizontal) doesn't work correctly as one will take priority over the other and not respect the others setting. This also causes the flip filter to break and sometimes combine actions and reverse them? Example in the video below.

**To Reproduce**
1. Add two flip filters
2. Set one to horizontal, the other to vertical
3. Switch between vertical and horizontal on both
4. Reproduced

**Expected behavior**
The flip filter should be able to be combined to allow an image which is flipped both vertically and horizontally. An alternative solution to this problem is to allow only one flip filter to be added and add an option labelled "both" or "VH".

**Screenshots / sample files**

[flip.webm](https://github.com/user-attachments/assets/b323fe62-ed41-436a-90be-51d890960583)

**Desktop (please complete the following information):**
 - OS: Arch Linux, Hyprland (Wayland)
 
 **Additional context**
The current flip behaviour is kind of weird, I would expect the vertical option to only flip vertically, not both horizontally and vertically.

**Comment by woelper** [comment]
There was a bug where the flip filter would always flip horizontally. From what I tested the stacking works as expected now. Great you found this!
