### ISSUE TITLE
Blur has near unusable performance at high values, causes crashes.

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#421]
Blur has horrible performance and can causes crashes pretty often. The higher the value is, the worse the performance is. An easy way this can be tested is with a 1080p image and just dragging the value around. This gets so bad in fact that trying to use blur on images around 4k will cause oculante to freeze nearly instantly and crash shortly after. These performance issues start on images around 800x600 on my system.

[blurcrash.webm](https://github.com/user-attachments/assets/14c3e963-6afc-4925-aca8-9276b8eb91d1)

**Comment by woelper** [comment]
This is expected as blur is a very expensive filter. It also depends on the image size. It should not crash though!

That said, there are other blur approaches which might be faster to do, perhaps at the expense of quality. I can try this:
https://docs.rs/fastblur/latest/fastblur/

**Comment by Stoppedpuma** [comment]
Might be worth trying! I'll look into the crash and send you some logs. Would scaling the image preview down based on how much blur is being used be possible? This could also help performance if fastblur doesn't help enough?

**Comment by Stoppedpuma** [comment]
> I'll look into the crash and send you some logs.

WARN  winit::platform_impl::platform::wayland::seat::pointer] Failed to set cursor to EwResize
ERROR smithay_client_toolkit::event_loop] Error trying to flush the wayland display: Broken pipe (os error 32)

These are the only logs I could get from terminal output, the EwResize warning is always present and I'm pretty sure unrelated, seeing the smithay_client_toolkit error is a first though! I've done a backtrace and sent you the output in DMs.

**Comment by woelper** [comment]
I have a PR ready which greatly improves the performance.
