### ISSUE TITLE
Flathub submission

### ISSUE THREAD

**Issue by Retengart** [woelper/oculante#427]
I think it's time to promote Oculante in the Flathub repo.
I've created full offline-during-build flatpak manifest and metainfo.xml
What should be added: the [oculante.png](https://github.com/woelper/oculante/blob/637c622b3384502f5c58ae295d5cc51549d5cfd3/res/oculante.png) icon has a resolution of 257x256 (Flathub uses only proportional icons, so it should be 256x256), [oculante.desktop](https://github.com/woelper/oculante/blob/637c622b3384502f5c58ae295d5cc51549d5cfd3/res/oculante.desktop) - there should be a separate version for Flathub (with the icon specified as io.github.oculante.Oculante), metainfo.xml should be placed somewhere in the [main](https://github.com/woelper/oculante) repo.

https://github.com/Retengart/flathub-oculante
https://docs.flathub.org/docs/for-app-authors/submission/

**Comment by woelper** [comment]
Hi! Thank you so much for that!

I was just talking to @Stoppedpuma about this - could you please coordinate what is left to do? You can also join the discord here to chat:
https://discord.gg/https://discord.gg/2Q6cF5ZWe7

**Comment by woelper** [comment]
Another question would be if this needs to be updated for new versions and how we integrate this in the build script - Oculante uses an automated release process which can be found here:

https://github.com/woelper/oculante/blob/master/.github/workflows/release.yml

Maybe there is additional value in Flatpack since we can bundle additional libraries which would be hard to impossible to bundle in regular builds, such as heif/heic support.

**Comment by Stoppedpuma** [comment]
@Retengart Hi, thanks for the request, I've already brought this to woelper and I am currently in the process of putting this onto flathub. We are currently redesigning the UI and will have Oculante on flathub as soon as we have the redesign into a presentable state at first glance. Regarding the icons, these have been redesigned will be uploaded as SVGs so there's nothing to worry about there!

> Another question would be if this needs to be updated for new versions and how we integrate this in the build script - Oculante uses an automated release process which can be found here:

@woelper the flathub build bot will automatically fetch new releases and submit a PR to update. This typically takes ~6 hours after merge to be updated.
