### ISSUE TITLE
xdg-desktop-portal FileChooser support for Linux

### ISSUE THREAD

**Issue by ludg1e** [woelper/oculante#450]
**Is your feature request related to a problem? Please describe.**
The default egui file picker is very basic and feels out of place with the rest of the desktop environment under Linux.

**Describe the solution you'd like**
Use the provided file picker by xdg-desktop-portal, which can vary depending the desktop environment being used.
Also, for flatpak it's recommended to use x-d-p.

**Describe alternatives you've considered**
Haven't thought of any.

**Additional context**
You can use the ashpd crate: https://github.com/bilelmoussaoui/ashpd

https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileChooser.html

**Comment by woelper** [comment]
You can currently use a file picker using `rfd` if you enable the `file_open` feature.

I would rather be interested in making the current file dialog better than using another wrapper around an external library as that has proven very hard to package and maintain for all operating systems.

**Comment by Stoppedpuma** [comment]
Hi, designer here! The file manager is currently pretty off from the reference designs I made, as is the entire UI. Oculante is currently in a state of implementing these designs (if you couldn't tell from the preview screenshots) and may take a while to meet user expectations.

Oculante isn't supposed to integrate as much as a "first party" application such as what you would find in a gnome or kde app as Oculante isn't necessarily a "Linux app" as much as it is an app with Linux support if that makes sense?

If you're curious on how the file manager will *eventually* look, here's a preview:

<img width="1004" alt="filemanager" src="https://github.com/user-attachments/assets/f3c0db85-45f6-48ec-a761-8e3b57ea44c9">

**Comment by woelper** [comment]
Closing this as you can use native dialogs with rfd and the current one will be improved
