### ISSUE TITLE
Textures don't seem to get freed

### ISSUE THREAD

**Issue by B-LechCode** [woelper/oculante#451]
**Describe the bug**
When using the application, switching between images let's the used VRAM increase. 
The VRAM isn't freed until the app is closed.

**To Reproduce**
1. Open VRAM monitoring tool (I used radeontop)
2. Open oculante
3. open image in a folder containing more than 1 image
4. Hold an arrow key
5. Watch the VRAM increase

**Expected behavior**
Freeing existing textures when a new image is loaded.

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Cinnamon X11 5.6.8
 - Version 0.9.1 (current master branch)

**Additional context**
[2024-09-29T11:33:28Z INFO  notan_glow] OpenGL Info: 
    Version: 4.6 (Core Profile) Mesa 22.3.6
    Renderer: AMD Radeon Pro W5700 (navi10, LLVM 15.0.6, DRM 3.49, 6.1.0-25-amd64)
    Vendor: AMD
    ---

**Comment by woelper** [comment]
Very good observation, thanks!
I looked at the `notan` API but did not find a method to manually free the texture I allocated. When the size does not change, I at least update the texture and don't create a new one. I will have to investigate if I need to do something special to make sure textures are freed.

**Comment by B-LechCode** [comment]
I first observed it with my big_images stuff - using gigabytes of textures at once amplifies this problem. After that I tried it with the master branch.

Please let me know if you have an idea - I didn't have one as I didn't see anything useful in the notan API.

**Comment by B-LechCode** [comment]
Hi @woelper,

can you confirm that i found the right spot? Do you have steady VRAM usage if the info menu is disabled?
If yes, I have an idea to fix that, would implement it within the big_images branch:

Registering the texture once a texture is generated and unregistering before it's overwritten, keeping the egui-texture(s) in the TextureWrapper struct.

**Comment by woelper** [comment]
Yes, I think that is the right spot. I was looking at that during the weekend as well. If you find a fix I'd love to fix it in current master as well.

**Comment by B-LechCode** [comment]
> Yes, I think that is the right spot. I was looking at that during the weekend as well. If you find a fix I'd love to fix it in current master as well.

I thought on fixing it in big_images, because I wanted to save some time. Would fixing it there and speed up merging an option, too?
Otherwise I will provide a fix in another branch and will file a PR for master and integrate it someday in big_images

**Comment by woelper** [comment]
>Would fixing it there and speed up merging an option, too?

Yes!

What do you think about not using egui at all to draw the preview? Would it be possible to use a similar approach you use for drawing the main image, perhaps re-using the texture?

**Comment by B-LechCode** [comment]
> What do you think about not using egui at all to draw the preview? Would it be possible to use a similar approach you use for drawing the main image, perhaps re-using the texture?

I thought about packing the egui texture as tuple together with the corresponding texture in the texture array. 
Would then unregister all textures on deletion. 

Don't think it's a problem to render the preview with egui then.

**Comment by B-LechCode** [comment]
Hi @woelper,
I added unregistering via a proxy struct. Please have a look.

There's only one problem: I can't get a reference for Graphics where "clear" is called (
- utils.rs, 754
- main.rs, 762)

What do you think? Should I cache the ids and unregister them as soon a new set of textures is assigned? Now the VRAM isn't "exploding" anymore. Won't have time to work on this for the next two weeks.
Please have a look :)
