### ISSUE TITLE
Extensions for Heif files are incomplete

### ISSUE THREAD

**Issue by Fiedzia** [woelper/oculante#457]
**Describe the bug**

I have sony camera (A7CR) that produces heif files with .HIF extensions.
This browser (with heif feature enabled) does not list heif files as images.

According to wikipedia, heif file extensions are:

.heif, .heifs; .heic, .heics; .avci, .avcs; .HIF

https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format

**To Reproduce**

enter directory containing .HIF file - it should be listed as image, but isn't

I can provide image files if that will help.

**Comment by woelper** [comment]
Thanks! This is easy to fix!
