### ISSUE TITLE
Pressing "Reset all edits" in edit-ui results in empty image

### ISSUE THREAD

**Issue by B-LechCode** [woelper/oculante#472]
**Describe the bug**
Pressing "Reset all edits" in edit-ui results in empty image. This will create a panic due to zero division in TextureWrapper.

**To Reproduce**
1. Start Oculante
2. Load an image
3. Open edit ui
4. Press "Reset all edits"
5. Panic...

**Expected behavior**
Resetting all edits should trigger switching back to the original texture and disabling the display button for the edited image in the compare section.

**Comment by B-LechCode** [comment]
Found this while working on #469, therefore zero texture size supression was implemented in the fix.
If #471 is merged, the Bug mentioned will result in an empty screen.

**Comment by woelper** [comment]
If I remember correctly, there are `result_pixel_op`and `result_image_op` for caching reasons which should be set to 0 if the `EditState` is reset. In the past, they would be filled with the original image on the next frame so I can see how that became a problem...

**Comment by Stoppedpuma** [comment]
Seems to be fixed.
