### ISSUE TITLE
Can not pick colors outside main spectra

### ISSUE THREAD

**Issue by 0323pin** [woelper/oculante#48]
Hi,

First of all, thank you for the new release. Awesome progress.
Maybe, you already know this but, I can not seem to be able to pick accent colors that are outside the main spectra.

![2022-09-08-090647_1366x768_scrot](https://user-images.githubusercontent.com/90570748/189058264-54f2999b-c985-4f04-b0ae-681063cdc18b.png)

I can move the _triangle cursor_ along the color spectra (left and right) but, I can not move the _circle cursor_ up and down to select variations of the main color. I hope that with the screenshot above, it is clear what I'm refering to.

Regards

**Comment by woelper** [comment]
This is interesting. I hope this is not an issue related to egui or because of the window manager. I will investigate. Does this issue also appear when you pick colors elsewhere, for example in the Multiply filter?

**Comment by 0323pin** [comment]
😄  Found it.
It works fine when the Edit field is not displayed. But, when the Edit field is displayed, I can not move the cursor to pick the accent color. The other color pickers on the tools works just fine. Well, except for the off-screen thing.

**Comment by woelper** [comment]
Hi!
The off-screen thing has now been fixed, along with a layout change to make the above less likely to happen / fix it.

**Comment by 0323pin** [comment]
Thanks!
