### ISSUE TITLE
Local files can't be piped into oculante

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#484]
Currently shows the following errors:

ERROR oculante] ERR loading from stdin: The image format could not be determined - for now, oculante only supports data that can be decoded by the image crate.
ERROR oculante::image_loader] Can't determine image type
ERROR oculante::utils] No such file or directory (os error 2)

**To Reproduce**
1. Run a command like `fd parameter | oculante -s`
2. Reproduced

**Comment by woelper** [comment]
I works for me if I use the stdin option, such as `cat tests/test.png | target/debug/oculante -s`. As your error states, the image might not be supported by the image library. What data are you trying to pipe?

**Comment by Stoppedpuma** [comment]
I believe I found why, I'm piping the output of file paths which Oculante doesn't seem to like.

**Comment by woelper** [comment]
Ah! Good point! I'll close this then, and we can create another issue if we want to support opening paths. Maybe we need to mess around with `clap` if we want that, but there are a couple of tripwires there.
