### ISSUE TITLE
Sliders are invisible in light mode after #479

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#485]
Now is a good time to set the colours on these properly, the slider background should be #0D0D0D in dark mode, and #000000 in light mode. Scrollbars should have a black background on both themes. The scrollbar head should be #FFFFFF in light mode, and #CCCCCC in dark mode.

In list order for readability sake:

Dark theme Slider BG: #0D0D0D
Light theme Slider BG: #000000

Dark theme Scrollbar Head: #CCCCCC
Light theme Scrollbar Head: #FFFFFF
\* theme Scrollbar BG: #000000

![image](https://github.com/user-attachments/assets/098ba63a-5a49-4ffc-8b48-06ffc3de9f56)

**Comment by woelper** [comment]
I've fixed this. I took the liberty to set it to button color (Whitish) and like it - please take a look and send a DM if you want to try other options.
