### ISSUE TITLE
All options under Alpha Tools cause crash

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#486]
ERROR notan_app::graphics] Invalid EGUI texture id User(5)
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/notan_app-0.12.1/src/graphics.rs:121:13:
Invalid EGUI texture id User(5)
stack backtrace:
   0:     0x5c5d22a108ca - std::backtrace_rs::backtrace::libunwind::trace::h02e7e86b2e735dcd
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x5c5d22a108ca - std::backtrace_rs::backtrace::trace_unsynchronized::h6da681a4cfb75062
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5c5d22a108ca - std::sys::backtrace::_print_fmt::h5602a4b492dc12dd
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/sys/backtrace.rs:66:9
   3:     0x5c5d22a108ca - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h4692be6f5ecb7860
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/sys/backtrace.rs:39:26
   4:     0x5c5d22a411a3 - core::fmt::rt::Argument::fmt::h345208fd7af429d2
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/fmt/rt.rs:177:76
   5:     0x5c5d22a411a3 - core::fmt::write::hdf001f36fa3b3f47
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/fmt/mod.rs:1186:21
   6:     0x5c5d22a0a2d3 - std::io::Write::write_fmt::h0830eb6780776006
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/io/mod.rs:1839:15
   7:     0x5c5d22a10712 - std::sys::backtrace::BacktraceLock::print::h3841e7a26406a42b
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/sys/backtrace.rs:42:9
   8:     0x5c5d22a1187c - std::panicking::default_hook::{{closure}}::hc9ee0a20637246f8
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panicking.rs:268:22
   9:     0x5c5d22a116c2 - std::panicking::default_hook::h5c389b9a8d35868b
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panicking.rs:295:9
  10:     0x5c5d22a11eb7 - std::panicking::rust_panic_with_hook::h8de63949f2bff3db
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panicking.rs:801:13
  11:     0x5c5d22a11d4a - std::panicking::begin_panic_handler::{{closure}}::hb7da7d31da8f7ff8
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panicking.rs:674:13
  12:     0x5c5d22a10da9 - std::sys::backtrace::__rust_end_short_backtrace::hba78a8b979834e74
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/sys/backtrace.rs:170:18
  13:     0x5c5d22a119dc - rust_begin_unwind
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panicking.rs:665:5
  14:     0x5c5d22a3ddd0 - core::panicking::panic_fmt::hce121bde1cc1b30a
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/panicking.rs:74:14
  15:     0x5c5d214013a1 - core::panicking::panic_display::hb5fc699eaff18078
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/panicking.rs:264:5
  16:     0x5c5d214013a1 - notan_app::graphics::Graphics::render::panic_cold_display::h0190e16af49f7e86
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/panic.rs:100:13
  17:     0x5c5d2135e472 - notan_app::graphics::Graphics::render::h4f6669fff5bb86b8
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/notan_app-0.12.1/src/graphics.rs:121:13
  18:     0x5c5d21365e21 - oculante::drawe::h51a41a8c2cff898e
                               at /home/user/{hidden}/oculante/src/main.rs:1225:5
  19:     0x5c5d213ecba6 - notan_app::builder::AppBuilder<S,B>::build::{{closure}}::hd4a9aebf598891e8
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/notan_app-0.12.1/src/builder.rs:351:25
  20:     0x5c5d213ecba6 - <notan_winit::backend::WinitBackend as notan_app::backend::BackendSystem>::initialize::{{closure}}::{{closure}}::h96529831b66867d5
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/notan_winit-0.12.1/src/backend.rs:264:31
  21:     0x5c5d21627860 - winit::platform_impl::platform::sticky_exit_callback::h4ef054fd04dfd239
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:884:9
  22:     0x5c5d21627860 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return::h43c3ac0d03f12230
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/wayland/event_loop/mod.rs:549:21
  23:     0x5c5d216299bc - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run::ha839f828e63e172e
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/wayland/event_loop/mod.rs:223:25
  24:     0x5c5d213e9d0c - winit::platform_impl::platform::EventLoop<T>::run::ha2487c765282f3f2
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:792:56
  25:     0x5c5d20eba22f - winit::event_loop::EventLoop<T>::run::h71b267ab80d09d0e
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/event_loop.rs:305:9
  26:     0x5c5d20eba22f - <notan_winit::backend::WinitBackend as notan_app::backend::BackendSystem>::initialize::{{closure}}::hc86eb4d7d7122cf4
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/notan_winit-0.12.1/src/backend.rs:119:24
  27:     0x5c5d20eba22f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd178592ea6076572
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/ops/function.rs:250:5
  28:     0x5c5d21672e0d - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdccc3eba1b2227f1
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/alloc/src/boxed.rs:2454:9
  29:     0x5c5d21672e0d - notan_app::builder::AppBuilder<S,B>::build::hc534b508979f56fe
                               at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/notan_app-0.12.1/src/builder.rs:284:25
  30:     0x5c5d21367f2b - oculante::main::hd7b3929fa67b9d92
                               at /home/user/{hidden}/oculante/src/main.rs:156:5
  31:     0x5c5d216071b6 - core::ops::function::FnOnce::call_once::h2c8cafa5ba98026f
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/ops/function.rs:250:5
  32:     0x5c5d216071b6 - std::sys::backtrace::__rust_begin_short_backtrace::he7df60e42b83e026
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/sys/backtrace.rs:154:18
  33:     0x5c5d21613ae5 - std::rt::lang_start::{{closure}}::hcbb3469b66b969c5
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/rt.rs:195:18
  34:     0x5c5d229ff65e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h826e86c25b8c24f7
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/core/src/ops/function.rs:284:13
  35:     0x5c5d229ff65e - std::panicking::try::do_call::hc6bae8c34a250977
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panicking.rs:557:40
  36:     0x5c5d229ff65e - std::panicking::try::hf60a9df2555302a3
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panicking.rs:520:19
  37:     0x5c5d229ff65e - std::panic::catch_unwind::h28a0748444713ece
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panic.rs:358:14
  38:     0x5c5d229ff65e - std::rt::lang_start_internal::{{closure}}::he4697d709567ffe5
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/rt.rs:174:48
  39:     0x5c5d229ff65e - std::panicking::try::do_call::h1779e14bd7155ea1
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panicking.rs:557:40
  40:     0x5c5d229ff65e - std::panicking::try::he7572fd700773e91
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panicking.rs:520:19
  41:     0x5c5d229ff65e - std::panic::catch_unwind::ha707ddc168d273de
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/panic.rs:358:14
  42:     0x5c5d229ff65e - std::rt::lang_start_internal::h3dbc25df42f69643
                               at /rustc/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/library/std/src/rt.rs:174:20
  43:     0x5c5d2136826c - main
  44:     0x7c59a9234e08 - <unknown>
  45:     0x7c59a9234ecc - __libc_start_main
  46:     0x5c5d20e9ed65 - _start
  47:                0x0 - <unknown>
warning: queue 0x5c5d4c677e50 destroyed while proxies still attached:
  wl_buffer#39 still attached
  wl_shm_pool#38 still attached
  xdg_wm_base#27 still attached
  wl_output#16 still attached
  wl_output#15 still attached
  wl_seat#14 still attached
  xdg_activation_v1#13 still attached
  wp_fractional_scale_manager_v1#12 still attached
  wp_viewporter#11 still attached
  zwp_text_input_manager_v3#10 still attached
  zwp_pointer_constraints_v1#9 still attached
  zwp_relative_pointer_manager_v1#8 still attached
  zxdg_decoration_manager_v1#7 still attached
  wl_subcompositor#6 still attached
  wl_compositor#5 still attached
  wl_shm#4 still attached
  wl_registry#2 still attached

**Comment by woelper** [comment]
I've mentioned here as well (original cause in that issue)
https://github.com/woelper/oculante/issues/469

**Comment by B-LechCode** [comment]
Sorry for that!
That problem occurs because the texture is overwritten after the rendering of the image was added to the "draw stack".

I need to think about a possible fix, that's not easy because swapping the calls is not easily possible. I will look on that on monday.

**Comment by Stoppedpuma** [comment]
Having a 20ms delay between frame buffer calls seems more like a hack then a fix to me, this shouldn't affect load times negatively.

**Comment by woelper** [comment]
I think that could work. I was also going to suggest we pick one single point where we update the texture so we don't have any race condition if that makes sense.

Another thing we could try later in the future is to ditch the whole story of having egui draw the texture and do that with notan as well. This might be a bit tricky in the info panel, but maybe there is another way. If the intent is to display a zoomed window to show users what is under the cursor, maybe that window could be attached to the cursor if the info panel is open? Or it could be on the top or bottom of the screen? Either way, we don't have to deal with another allocation at all and could reuse the textures we have.

**Comment by woelper** [comment]
I created an experimental PR here which does the drawing completely without egui:
https://github.com/woelper/oculante/pull/489

This does not work with large textures yet and just draws an image at the top where the old image used to be. It is ugly and is missing the "crosshairs", but I think this is something we could turn into something better and remove egui completely from this, what do you thing, @B-LechCode ?

The good stuff is that this would definitely reduce complexity and memory, but I think I need your help making it work with tiles.

**Comment by B-LechCode** [comment]
@woelper Thank you! I will have a look at it tomorrow. Removing egui would reduce complexity, but it wouldn't reduce memory requirements afaik, because the textures are only getting registered, not copied.

Changing the ui to not directly mess with the draw texture would be a thing I'd like to implement nevertheless. That would directly fix the bug, but drawing the zoom image with notan is a thing I wanted always since I implemented "big_images".
Are you ok if I implement the idea I had yesterday?

**Comment by woelper** [comment]
You are right, this would probably not reduce memory, but at least reduce the possibility for leaks and having to care about the egui textures' lifecycles.

Please go ahead with the Ui changes if you want, especially since that fixes the bug. But please be aware that once we use notan to draw the zoom image, this work could be wasted. It does look like it could be easier to do than I thought.

**Comment by B-LechCode** [comment]
I think it shouldn't be wasted, because overwriting the draw textures while building the next frame seems not to be a good practice for me. It just never was a big deal, because the textures seem to have a reference count mechanism.

**Comment by woelper** [comment]
Sounds good! Thanks!

**Comment by B-LechCode** [comment]
@woelper, @Stoppedpuma: I fixed it by implementing texture changes directly after rendering.
Please have a look and tell me if it's fixed for you, too.
I haven't seen a problem since implementing.

**Comment by woelper** [comment]
Amazing! I'll have a look soon!

**Comment by B-LechCode** [comment]
@woelper Thank you :)
I want to apply some refactoring as soon as I have more spare time. You may merge if desired - or you could wait for that.
Otherwise I will bring up a new PR with the refactoring.

**Comment by B-LechCode** [comment]
@woelper, @Stoppedpuma this was fixed, right?

**Comment by woelper** [comment]
Yes!
