### ISSUE TITLE
Active info is not read-able if the color is [127, 127, 127]

### ISSUE THREAD

**Issue by Jerakin** [woelper/oculante#5]
![Screenshot 2021-01-13 at 10 51 36](https://user-images.githubusercontent.com/5273682/104436009-5f25e200-558d-11eb-8fe9-07d950729ac6.png)

Maybe white text with black outline would make it always readable?

**Comment by woelper** [comment]
Good catch. Made all text white with black outline. Grab 0.4.13 for a fix.
