### ISSUE TITLE
Map extra mouse buttons (m4, m5 etc)

### ISSUE THREAD

**Issue by Michaelknubben** [woelper/oculante#501]
**Describe the solution you'd like**
I want to map my mouse's extra buttons to Next image and Previous image, but keymapping only allows keyboard keys.

**Describe alternatives you've considered**
For me personally, just mapping these buttons (that map to back and forward by default in windows, firefox etc) to these functions would be good, but alternatively I'd like to see mapping of mouse buttons.

**Comment by Stoppedpuma** [comment]
Going to track this in #408 as the way to set keybinds will change as apart of the redesign which should allow this to be easier UX wise (Pressing a button and using the key rather than holding and clicking to set).
