### ISSUE TITLE
Extremely large images (~50k range) may not load correctly, leaving artifacts or missing gaps in the image

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#509]
Discovered last week while testing #506, slightly annoying to reproduce as Oculante likes to crash occasionally loading these images. This issue happens every once in a while.

May cause (that I'm aware of): 

Artifacts that look like texture corruption or what an asset in a pixel art style game would look like
Incorrect colours
Entire gaps being missing

@B-LechCode Pinging you here for this in-case you have any ideas of what's causing this. (In the chance that you see this before I can reproduce this again with an image showing this, I'll add an image when I can reproduce this again.)

**Comment by B-LechCode** [comment]
Which branch did you test this with? 

I found something similar and fixed it in dynamicimage branch. I thought it was only there, but maybe I was wrong.

That happens if two consecutive image have the same size and are rgb (without alpha). Is this the case here too? Or was it on initial image load?

**Comment by Stoppedpuma** [comment]
This was upon initial load. Not sure if two of the same size in the current directory matter but if so it's possible I did have two of the same size image in the directory.

**Comment by Stoppedpuma** [comment]
> Maybe you had just out of memory glitches?

Definitely a possibility, woelper suggested something similar when I mentioned this. I think since this is unrelated to `dynamicimage` branch and that the current behaviour will change because of that, it's fine to close this if you can't reproduce? I've tried several times now to get this to happen again and haven't been able to yet. Feel free to close this if you can't reproduce this in your testing.

**Comment by woelper** [comment]
I was able to reproduce corruption if a non-alpha image is opened and then converted to alpha (image has same size). Essentially:
- Open a jpg with rgb8 mode
- Open edit panel
- Select something that has an alpha channel (such as La8)

I previously had corrupted textures, but now this crashes with:
```
thread 'main' panicked at src/texture_wrapper.rs:165:27:
Problem generating texture: "Texture type Rgba32 with 10960320 bytes, when it should be 21920640 (width: 1960 * height: 2796 * bytes: 4)"
```

**Comment by B-LechCode** [comment]
@woelper it seems you tested with dynamicimage branch! This currently only works with l8, rgb8 and rgba8, other types need to be implemented.

In master there is only rgba8 passed to textue_wrapper, and in master branch is nothing relatable at line 165.

**Comment by woelper** [comment]
I am sorry, yes this is with `dynamicimage`, correct!

**Comment by B-LechCode** [comment]
No problem!

**Comment by Stoppedpuma** [comment]
Closing in favour of the changes present in #495.
