### ISSUE TITLE
Oculante changes to minimum window size if changed from tiling to floating

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#533]
**Describe the bug**
Oculante forces itself down to the minimum resolution set in the app instead of a fractional value of the display when changing modes from tiling to floating on tiling window managers.

**To Reproduce**
1. Change window to floating mode
2. Reproduced

**Expected behavior**
Oculante should instead use a fractional values of the displays resolution so that the floating window is neither too large, nor small.

**Screenshots / sample files**
Comparison against how Firefox handles this:

[floating.webm](https://github.com/user-attachments/assets/2e38d108-958d-4968-8c80-53605d7ac99d)

**Desktop (please complete the following information):**
 - OS: Arch Linux, Sway (Wayland)

**Comment by woelper** [comment]
I don't think we have control over that. I think this should probably be reported/fixed in notan or even a level higher, maybe winit?

**Comment by Stoppedpuma** [comment]
Seems to be Sway specific and how it looks around for windowing size recommendations. Closing for now as it's not a huge deal for now or even reproduceable outside of Sway for me. This can always be revisited in the future of users report this happening outside of Sway.

For those who are encountering this, you can manually change the size in your configuration file for Sway with the following line:

`for_window [app_id="oculante"] floating_minimum_size 1600 x 900`
