### ISSUE TITLE
Undo and Redo keybinds for filter actions

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#546]
As mentioned in #516.

**Comment by woelper** [comment]
I would really not like to have undo and redo functionality. I think this is a can of worms. All filters are non-destructive anyways. I would vote to close as not planned.

**Comment by Stoppedpuma** [comment]
Agreed, this adds a lot of unnecessary complexity.

@dasbard Apologies if this one if high on your list but I think this is going to be a no, at least for now.
