### ISSUE TITLE
Switch to turbojpeg for jpeg images

### ISSUE THREAD

**Issue by UE2020** [woelper/oculante#55]
If you care about performance, you should switch to turbojpeg, which is magnitudes faster than the `image` crate when it comes to jpeg encode/decode. In a past project that I was developing, I was even able to decode a stream of jpeg images at 100 frames per second (20 fps with the image crate). There are already good Rust bindings here: https://crates.io/crates/turbojpeg

**Comment by woelper** [comment]
Amazing. I do care about performance, so this is a great suggestion. Adding that should not be too hard. Are there any drawbacks to turbojpeg compared to image?

**Comment by woelper** [comment]
I've benchmarked `turbojpeg` on a branch and it's roughly twice as fast. I will investigate a bit if this has any side effects and produces a static binary on all systems. If that works well, this is a great suggestion and should provide value for users. Thanks @UE2020 .

**Comment by woelper** [comment]
This is now merged and released.
