### ISSUE TITLE
Make the alpha channel more obvious to the user

### ISSUE THREAD

**Issue by lichspace** [woelper/oculante#561]
**Describe the bug**
this size not show
![image](https://github.com/user-attachments/assets/0e364717-b0f8-4b00-8701-2b331dbed74b)

**To Reproduce**
open png

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows,
 - Version  0.9.1

**Comment by woelper** [comment]
Thank you! Would you be able to attach the image here so the issue is easier to reproduce?

I am also tagging @B-LechCode here as our Big Image Expert :)

**Comment by Stoppedpuma** [comment]
I believe the issue here is that the user has their colour mode set to alpha. @lichspace can you see if setting to RGBA fixes this?

[rgba.webm](https://github.com/user-attachments/assets/e3ec7357-9dea-4372-bcc0-db85f38cd1b1)

**Comment by woelper** [comment]
Good call, I missed that! Maybe we want non-rgba modes to have a different color so the user notices it more easily?

**Comment by Stoppedpuma** [comment]
Odd suggestion and maybe not even possible but how about embedding a informative text if there's no alpha on the alpha channel? I think I was confused by this as well at some point as it's quite easy to miss press a to change to the alpha channel.

**Comment by lichspace** [comment]
> I believe the issue here is that the user has their colour mode set to alpha. @lichspace can you see if setting to RGBA fixes this?
> 
>  rgba.webm

yes change to rgba is ok。 but i dont know why  show alpha mode. sorry~

**Comment by woelper** [comment]
> Odd suggestion and maybe not even possible but how about embedding a informative text if there's no alpha on the alpha channel? I think I was confused by this as well at some point as it's quite easy to miss press a to change to the alpha channel. I think just changing the colour doesn't really help and may even be more confusing, maybe a gradient or repeating pattern might work better than a different colour if the informative text is off the table?

This could work in the DynamicImage branch since we can check for the image mode. We could even prevent / disable alpha mode on images without alpha channels so we don't need a message. What is more difficult are images that are rgba but have a "solid" alpha channel. You would still see white in this case.

Maybe we could have a text somewhere if the image mode is not rgba?

**Comment by Stoppedpuma** [comment]
> yes change to rgba is ok。 but i dont know why show alpha mode. sorry~

You might have accidentally pressed the keybind to switch to the alpha channel. I've opened a PR which requires holding alt by default to reduce the chances of this in the future. See #562.

**Comment by Stoppedpuma** [comment]
> > Odd suggestion and maybe not even possible but how about embedding a informative text if there's no alpha on the alpha channel? I think I was confused by this as well at some point as it's quite easy to miss press a to change to the alpha channel. I think just changing the colour doesn't really help and may even be more confusing, maybe a gradient or repeating pattern might work better than a different colour if the informative text is off the table?
> 
> This could work in the DynamicImage branch since we can check for the image mode. We could even prevent / disable alpha mode on images without alpha channels so we don't need a message. What is more difficult are images that are rgba but have a "solid" alpha channel. You would still see white in this case.
> 
> Maybe we could have a text somewhere if the image mode is not rgba?

I think a notification could be an easy implementation while also being non intrusive. Maybe fading to the accent colour and back kind of like flash on the colour channel could also work as an indicator, pretty hard to miss that one!
