### ISSUE TITLE
Prevent adding duplicate colours to colour palette

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#566]
Currently, the same colour can be added infinitely, a confirm prompt should appear asking if the user is sure they want to add a duplicate colour.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the palette_ui function to check for duplicate colors and show a confirmation prompt using egui_modal when attempting to add a duplicate color.

You can review changes in this commit: https://github.com/jacks-sam1010/woelper-oculante-566/commit/1216728de4cd58d6170f3ada8408becbdce333a7.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by woelper** [comment]
I'd advocate for using a different storage type such as a HashSet instead if duplicates are not desired.
