### ISSUE TITLE
Allow palette to properly take left and right click inputs on the UI

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#567]

**Comment by woelper** [comment]
I don't think this is an issue we should fix - right now there is no concept of being out of bounds, and I would think that users would like to pick whatever is under the cursor, even if the cursor is out of bounds. I think it makes sense to think that "edge pixels" continue at their respective sides.

**Comment by Stoppedpuma** [comment]
Seems fine to me.

**Comment by Stoppedpuma** [comment]
@woelper one thing I did actually just think of for this is being able to right click a colour in the palette to either copy the hex or remove it. This would require fixing this though so just throwing this out there.

**Comment by woelper** [comment]
Great idea! I would also like to auto-generate a palette later from the image.

**Comment by Stoppedpuma** [comment]
Got it, I'll reopen this. Another possible way we could go about this is preventing adding colours when the cursor is in the UI.
