### ISSUE TITLE
Image preview can draw above the status bar

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#568]
Same issue as what was happening with the file manager.

![image](https://github.com/user-attachments/assets/724435fe-924f-4c9e-928c-7f8d1a799436)

**Comment by woelper** [comment]
The image preview will always draw on top of everything. How did you get it to draw above the status bar?

**Comment by Stoppedpuma** [comment]
> The image preview will always draw on top of everything. How did you get it to draw above the status bar?

I added a bunch of colours to the colour palette and scrolled down.
