### ISSUE TITLE
Resizing window should keep images centered

### ISSUE THREAD

**Issue by fewkz** [woelper/oculante#57]
It would be convenient if resizing window would keep images centered, by making the offset relative to the center rather than top-left of the image

**Comment by woelper** [comment]
Thanks! This was actually the default some time ago. I was unclear about the following:
- What should happen if the user is in edit mode (and painting something maybe)? Maybe disable this feature then?
- What should happen if the user is zoomed into an image? Just do offset from the resizing side or ignore?

What is your opinion on those?

**Comment by fewkz** [comment]
I use oculante primarily for viewing images due to it's super fast startup speed. I wouldn't mind if the feature was disabled while in editing mode. I don't know how the behavior should work if you're zoomed in though

**Comment by woelper** [comment]
I think I found a good compromise/solution. I get the delta between the last frame's window size and the current one and offset accordingly. This "feels" like a good offset, please tell me if you would like it to behave differently. Maybe this can also be enabled in edit mode.

Thank you for mentioning startup speed. In `0.6.16` jpeg images open twice as fast now, as `turbojpeg` is now used to decode images.

**Comment by woelper** [comment]
Closed and released in `0.6.17`. Please reopen/comment with further feedback!
