### ISSUE TITLE
Prevent text from being selectable in preferences

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#577]
Gets in the way of scrolling by dragging in the middle. If we want to allow copying these options text, perhaps right clicking the relevant name / description should copy. The usual notification would be appreciated here as well since there's not really an indicator. Another idea I have is to faintly show the accent colour in the text when copied, I can show an example for this if this is something desired.

[drag.webm](https://github.com/user-attachments/assets/6929b345-3eaf-4a4a-8ee5-215e6a2a864f)

**Comment by woelper** [comment]
This is fixed now. The issue is that egui made selectable labels the default during a version upgrade. This is nice in some places, but in cases like these not so much.

**Comment by Stoppedpuma** [comment]
Thanks!
