### ISSUE TITLE
Flickering after opening and closing alpha tools

### ISSUE THREAD

**Issue by 0323pin** [woelper/oculante#58]
Hi,

I've just updated our package to 0.6.16
Had to build it with `--no-default-features`, as we internally still default to `jpeg` instead of `libjpeg-turbo` and these two can not co-exist. Is either one or the other.

I don't know if this could be somewhat related but, I think I've hit a bug.
When expanding the alpha tools in the info section of the GUI and then closing causes flickering of the Info field.

**Comment by woelper** [comment]
Thanks. Yes, I've been thinking of you when I added `turbojpeg` - I put it behind the `turbo` feature so it can be disabled. Sorry for not giving you a heads up earlier. If it helps, that feature could maybe be disabled under NetBSD by default?

I'll look into the other issue as well.

**Comment by 0323pin** [comment]
> If it helps, that feature could maybe be disabled under NetBSD by default?

That's exactly what I've done. Thanks for thinking about it and doing it as a feature.

> I've been thinking of you when I added turbojpeg - I put it behind the turbo feature so it can be disabled.

We do have a package for turbo and, if you build all your packages from source, you can set it to default. In which case, the feature could be on by default. But, the official pre-compiled binaries use `jpeg` as default. Hope it was clear enough, sometimes it's not easy to explain all the small things.

> I'll look into the other issue as well.
Thanks

**Comment by 0323pin** [comment]
@woelper Updated, http://mail-index.netbsd.org/pkgsrc-changes/2022/10/18/msg262192.html

**Comment by woelper** [comment]
This issue has been fixed in `0.6.18`. I've tested, please re-open if you see the issue again. Thanks for flagging this!

**Comment by 0323pin** [comment]
Thanks, I'll re-build it later today.

**Comment by woelper** [comment]
You rock, thanks!

**Comment by 0323pin** [comment]
Thank you for the fix!
All good, no more flickering. I'll merge it tomorrow, need to get some sleep now.
