### ISSUE TITLE
"Open another image" in the compare menu should work as a way of adding images to the compare list

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#580]

**Comment by woelper** [comment]
This is a bit more involved, as the compare list stores the image dimension and offset with each entry. If we load a new image at this point, the new dimensions are not yet known until the image as finished loading, which could take any amount of time or even fail. This would require some kind of special treatment such as sending a message or custom frame type.

**Comment by woelper** [comment]
I actually had an idea to fix this that seems not too intrusive.
