### ISSUE TITLE
Some buttons and dropdowns don't have a bg colour in preferences, existing colours are inaccurate.

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#583]
![image](https://github.com/user-attachments/assets/fafaa2be-517b-4aba-9edc-92298fe4fdbe)

Buttons should be #262626 in Dark mode, #FFFFFF in light mode.

Dropdowns should be #0D0D0D in dark mode, #D9D9D9 in light mode.

**Comment by woelper** [comment]
Unfortunately dropdowns and buttons use the same internal color, so both will look the same.

**Comment by Stoppedpuma** [comment]
Slightly annoying limitation but it's not horrible at least! One small oversight though is check buttons seem to be too bright still:

![image](https://github.com/user-attachments/assets/159f26ff-93d2-4d23-8a6f-559a0f5fd33d)

**Comment by woelper** [comment]
Fixed the checkbox!
