### ISSUE TITLE
Text colours do not match redesign

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#584]
Very noticeable in preferences to the point that it's almost a problem. All text is #CCCCCC in dark mode, #333333 in light mode. Text in the redesign which may appear to be slightly darker is just 50% opacity.

**Comment by woelper** [comment]
Is this just in the preferences or everywhere? Ideally I'd like to keep the text color constant throughout the app.

**Comment by Stoppedpuma** [comment]
Yes, all text everywhere is #CCCCCC in dark mode, #333333 on light mode. In the total of like two areas I can think of off the top of my head with slightly dimmed text, it's just those at 50% opacity. If you need actual hex values for that let me know.

**Comment by woelper** [comment]
All good, got it! This is fixed now. Let me know if you spot any odd things!

**Comment by Stoppedpuma** [comment]
Top bar icons, text on buttons, input boxes, and in the hamburger menu all seem to remain the old colour.

![image](https://github.com/user-attachments/assets/ad9f7936-574e-4223-a8d8-eb85887dedf0)

**Comment by woelper** [comment]
Found it, should be fixed! I also added a hex color display in the info panel for obvious reasons :)

**Comment by Stoppedpuma** [comment]
Thanks! This all seems to be correct now.
