### ISSUE TITLE
Some animated GIFs crash oculante

### ISSUE THREAD

**Issue by hahaslav** [woelper/oculante#60]
I tried to view a bunch of GIFs, but my last file `cat_in_headphones.gif` crashes the app:

https://user-images.githubusercontent.com/65510612/197695169-bdc69209-8077-40fa-8c44-7f20900fac3b.mp4

This file can be displayed in another program, so why does oculante not work with it?

Problematic file (archived): 
[cat_in_headphones.zip](https://github.com/woelper/oculante/files/9857582/cat_in_headphones.zip)

System specs:
* OS: Windows 10 21H1
* CPU: Intel Core i5-8250U
* GPU: Intel UHD Graphics 620
* Oculante version: 0.6.18

###### P.S. I am thankful to the author of oculante. Now, it is my primary image viewer because of its lightning-fast startup.

**Comment by woelper** [comment]
Thank you so much. Also great that you attached a sample. I will look into that tonight - at the very least it should not quit but display a helpful error. I can't promise I can get the image to open, as I am using the `image` library to do that. But if it is an error in that library maybe we can file a bug there, too.

**Comment by woelper** [comment]
Good news and bad news: I can get rid of the crash, but the error is from the decoding library: `Format error decoding Gif: unknown block type encountered`. So there is something wrong with the Gif, and the library refuses to load it. I'll investigate a bit further and release a fix against the crash.

**Comment by woelper** [comment]
I'll leave this open until Oculante can successfully load your sample. I'll go ahead and file an upstream bug report. Alternatively I am exploring other options/libraries to load gif.

Linking the original image here for convenience.
![cat_in_headphones](https://user-images.githubusercontent.com/3613791/198876501-61f76e9c-ef0f-46fa-8e4b-a5e5b20fcecf.gif)

**Comment by woelper** [comment]
This should now work with manually advancing Gif frames and testing them. The latest 0.6.20 release has these fixes. Happy Gif viewing!
