### ISSUE TITLE
Channels setting not true/effective when switching between files

### ISSUE THREAD

**Issue by amstaniec** [woelper/oculante#61]
Steps to reproduce:
1. open image (by default it opens with RGBA setting)
2. change channels to RGB (it changes the appearance in my case)
3. change to next image (similar to the first one)
4. the channels dropdown box stay in RGB (which is good), but the image is displayed still as if in RGBA setting was selected (which is bad)

**Comment by woelper** [comment]
Thank you so much for the issue. This is definitely an inconsistency. Would you rather:
1. Have the channels reset back to RGBA
2. Have the next image respect the current setting and display RGB if it was the previous setting?

I am not sure what the most user-friendly behavior would be. Maybe someone would hit the `a` key by accident and then just see white images when browsing their pictures. On the other hand, you might want options to persist. Maybe this could also be a global setting, such as "persist options when loading next image". There are a couple of other things which are related, such as image manipulations. One could argue if you add a filter, you might want that on the next image, too...

**Comment by amstaniec** [comment]
Thanks for responding!
IMO definetely 2.
that was my use case when I discoved the behaviour

**Comment by woelper** [comment]
Ok! I think that makes sense. I'll keep this open until it is changed.

**Comment by woelper** [comment]
I did not forget about this, @amstaniec - I realized that in order for this to work in edit mode there would be a bit of refactoring needed. I will disable the channel selection in edit mode for now and go ahead with your planned change soon.

**Comment by woelper** [comment]
This is now fixed/released in `0.6.22`. The behavior now is:
- Channel selection persists between images
- When turning on edit mode, channel selection box is greyed out and channel is set to RGBA
