### ISSUE TITLE
Lossless editing of JPEGs (rotate, crop, etc.)

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#66]
That'd be a great feature for a viewer/simple editor and there is no need to lose quality for these, more details about this: https://jpegclub.org

**Comment by woelper** [comment]
Hi, and thanks for bringing up this issue!

I hope this does not come across the wrong way, but I don't think this feature is realistic in the short or mid term. A couple of reasons:

- Oculante tries to be very generic across images. After loading, every image is just an imagebuffer and a texture. While there could be format-specific operations, this does not fit the current concept well.
- Oculante has a modifier stack with different modifiers which can have a specific order. If we wanted some operations to be lossless, for example cropping, this would rule out other operators such as brightness. I don't think that this would fit the concept well.
- Maybe in the future, we could have exclusive format-dependent operators such as "lossless crop", but it would also forbid other operations at the same time.

**Comment by eugenesvk** [comment]
>I hope this does not come across the wrong way, but I don't think this feature is realistic in the short or mid term.

Ok, no worries


> Maybe in the future, we could have exclusive format-dependent operators such as "lossless crop", but it would also forbid other operations at the same time.

This sounds similar to how it's done in other viewers/editors that support it: you get "regular" crop/rotates and then "lossless jpeg operations". I think the key is making sure that the __lossy operation__ is "harder", explicit, and creates a backup :) (e.g, in XnViewMP crop you'd you can select any crop area, but when invoking the lossless crop action, you'd only actually crop a multiple of a block; and in GraphicConverter for rotations you can even force to only use lossless operation for jpegs and configure to autoadjust size (optionally increase or decrease to match blocks of 8×8 or 16×16 or whatever the limitations are)

**Comment by woelper** [comment]
Yes, that makes a lot of sense - and thanks for the  XnView example.

In Oculante, "lossy" operations are a bit more of a grey area. Of course once you write to a lossy format you lose data if not using lossless features mentioned above. On the other hand, the whole edit stack (including cropping, resizing, blur etc) can be saved to a metafile and will be auto-applied if you open a file with metafile in the same folder. This delays lossy operations to the very moment you save and gives you more diverse lossless editing options.

**Comment by eugenesvk** [comment]
Just to clarify: even though cropping is a lossy operation on save, it's helpful to differentiate between two sources of a loss:

1. (obvious) are you didn't select is lost
2. (less obvious) generation loss even in the area you left

For the 2nd type of loss I'd argue that **by default** it shouldn't happen as it's actually an unexpected effect, so you should have a GraphicConverter-like config (though in GC this type of config only exists for rotations, "gen-lossless" cropping is a separate operation) that can force all crops to be 2nd type lossless and have the area size adjusted to match the block size, and then if you really need pixel-perfect selection, you should invoke a gen-lossy crop command

Then you can have the same keybinds for rotate/crop operations in jpeg and png and only invoke different keybinds when you need to do something lossy ;)

The storing edits in metadata/sidecar metafile/in file is more workflow specific and has separate tradeoffs

**Comment by woelper** [comment]
I think I have found a good compromise for the time being:
![image](https://user-images.githubusercontent.com/3613791/206300146-975d842a-6564-40eb-b4d2-a199253a93d3.png)

When using these transforms, the image is loaded from disk, processed, written to disk and reloaded in the viewer. This way no operation changes the image and it becomes clearer that these operations work in a certain context only. I might look into adding other transforms as well.

**Comment by woelper** [comment]
This is now in the latest release. Please give it a spin and feel free to (re)open a ticket with more suggestions.

Crop was hardest to implement. Basically it's now automatically adding a regular crop operator which drives the values for the lossless crop.
The crop origin is automatically aligned to the correct block size. This of course can slightly alter the result. The operation is only performed if a valid crop can be produced.
After a valid operation, the image is saved and reloaded.

**Comment by woelper** [comment]
There seems so be an issue with the release. Will re-open this and re-release. Sorry!

**Comment by woelper** [comment]
v0.6.26 should have the changes once built.

**Comment by eugenesvk** [comment]
Thanks, found it now :)!
The lossless rotation has a little bug — it doesn't retain the compression mode, i.e., try to rotate a progressive jpeg and you'll see it transformed into a non-progressive one

The lossless crop seems fine, though for non 8×8 multiples I've found an interesting discrepancy vs. the jpegtran reference tool: if I convert a `16×20.jpg` into `-crop 11x11+0+9` with jpegtran (so this leaves the bottom left corner), I get an `11×12` block (same in XnView and a GraphicConverter app), but with your tool I get `11×11` picture

original image
![rr2 16×20](https://user-images.githubusercontent.com/12956286/206684031-0f00d0f5-2f0e-4381-9393-10f5bf8352ef.jpg)

jpegtran cli (`jpegtran -copy all -crop 11x11+0+9 -outfile 'rr2 16×20 → 11←×11↓ jt (11x11+0+9).jpg' 'rr2 16×20.jpg'`)
![rr2 16×20 → 11←×11↓ jt (11x11+0+9)](https://user-images.githubusercontent.com/12956286/206684110-6cd2addd-4a39-4e75-8b41-c64e0f03b334.jpg)

Graphic converter (identical to jpegtran)
![rr2 16×20 → 11←×11↓ gc=jt (11x11+0+9)](https://user-images.githubusercontent.com/12956286/206684103-dc88d2a4-09fa-4c81-bd06-e49f2fdc57bd.jpg)

XnViewMP (this one also does some Huffman optimizations, so the the file turns out a bit different vs. the original)
![rr2 16×20 → 11←×11↓ xn (warning) (actually 11×12)](https://user-images.githubusercontent.com/12956286/206684117-6cc83b9b-3138-4744-9eed-a5cc86783f33.jpg)

Your tool
![rr2 16×20 → 11←×11↓ oc](https://user-images.githubusercontent.com/12956286/206684112-8d4bb3ea-cba0-4ee1-aa30-3d7f05d32f34.jpg)


Also, in XnViewMP I get a warning that some unused pixels might get removed to match the 8×8 blocks, might be worth adding a similar warning here?

**Comment by eugenesvk** [comment]
Lastly, similar to my other rotate issue, I think the UI could be much better if it were denser: all the lossless transformations could fit on one line + header (that would also have the warning)

**Comment by woelper** [comment]
First of all, thanks for the thorough testing!

> Thanks, found it now :)! The lossless rotation has a little bug — it doesn't retain the compression mode, i.e., try to rotate a progressive jpeg and you'll see it transformed into a non-progressive one

Not sure I can do something about that, but I'll have a look at the library I am using!
 
> The lossless crop seems fine, though for non 8×8 multiples I've found an interesting discrepancy vs. the jpegtran reference tool: if I convert a `16×20.jpg` into `-crop 11x11+0+9` with jpegtran (so this leaves the bottom left corner), I get an `11×12` block (same in XnView and a GraphicConverter app), but with your tool I get `11×11` picture
> 
> original image ![rr2 16×20](https://user-images.githubusercontent.com/12956286/206684031-0f00d0f5-2f0e-4381-9393-10f5bf8352ef.jpg)
> 
> jpegtran cli (`jpegtran -copy all -crop 11x11+0+9 -outfile 'rr2 16×20 → 11←×11↓ jt (11x11+0+9).jpg' 'rr2 16×20.jpg'`) ![rr2 16×20 → 11←×11↓ jt (11x11+0+9)](https://user-images.githubusercontent.com/12956286/206684110-6cd2addd-4a39-4e75-8b41-c64e0f03b334.jpg)
> 
> Graphic converter (identical to jpegtran) ![rr2 16×20 → 11←×11↓ gc=jt (11x11+0+9)](https://user-images.githubusercontent.com/12956286/206684103-dc88d2a4-09fa-4c81-bd06-e49f2fdc57bd.jpg)
> 
> XnViewMP (this one also does some Huffman optimizations, so the the file turns out a bit different vs. the original) ![rr2 16×20 → 11←×11↓ xn (warning) (actually 11×12)](https://user-images.githubusercontent.com/12956286/206684117-6cc83b9b-3138-4744-9eed-a5cc86783f33.jpg)
> 
> Your tool ![rr2 16×20 → 11←×11↓ oc](https://user-images.githubusercontent.com/12956286/206684112-8d4bb3ea-cba0-4ee1-aa30-3d7f05d32f34.jpg)
> 
> Also, in XnViewMP I get a warning that some unused pixels might get removed to match the 8×8 blocks, might be worth adding a similar warning here?

I think adding a warning might be good (or even auto-adjusting the crop). This might be just an excuse for my laziness, but my feeling is that these minor crop differences might not be very grave for end-users?

**Comment by eugenesvk** [comment]
> Not sure I can do something about that, but I'll have a look at the library I am using!

It might have a flag re. the compression type to use (just like the `jpegtran` tool has it), so it'd be a matter of detecting the current image's compression type and passing it further to the library

> This might be just an excuse for my laziness, but my feeling is that these minor crop differences might not be very grave for end-users

Well, your app's behavior is actually more desirable as it matches exactly what the user selected. **BUT** the reason I brought it up is that maybe there are limitations to jpeg that prevent you from having a losslessly cropped `11×11` box, so the fact that your app does it signifies some silent corruption or something, which is unexpected and might be hard to notice (so the worse type of bugs). How grave that is in real world use I don't really know

**Comment by woelper** [comment]
- I've updated and condensed the UI.
- As is seems now, I can set if the image should be progressive - but I can't find a way to find out if the _current_ image is progressive. So I can't keep that setting as I see it now.
- As for the cropping, I am relying on a crop method from `turbojpeg` which fails if fed the incorrect settings. I am checking if the crop completes successfully, and only then save. I hope this will not lead to corruption or undesired results, otherwise I'd open up a ticket with that library.

**Comment by eugenesvk** [comment]
> way to find out if the current image is progressive

"A progressive DCT-based JPEG can be identified by bytes “0xFF, 0xC2″." from this [SO answer](https://superuser.com/questions/1010734/how-can-i-tell-if-a-jpeg-was-saved-as-progressive)

Another bug: lossless jpeg menu doesn't show up for `.jpeg` file extensions, which are common on a Mac

**Comment by eugenesvk** [comment]
> * As for the cropping, I am relying on a crop method from `turbojpeg` which fails if fed the incorrect settings. I am checking if the crop completes successfully, and only then save. I hope this will not lead to corruption or undesired results, otherwise I'd open up a ticket with that library

But the tests were done using the latest turbojpeg `jpegtran` cli tool and I didn't get 11×11! So maybe something else is going on?
