### ISSUE TITLE
Text is blurry on a "retina" mac screen

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#67]
comparison to TextEdit (at the top)
<img width="104" alt="blurry" src="https://user-images.githubusercontent.com/12956286/205497927-b807b1bf-702b-4cb8-8bb4-3639aae50198.png">

**Comment by woelper** [comment]
Thanks!

This is most likely something that needs to be configured in `egui` or `notan`. 

Could you please check if this text is blurry:
(Egui in Notan)
https://nazariglez.github.io/notan-web/examples/egui_demo.html

And this one as well?
(Plain egui)
https://www.egui.rs/

**Comment by woelper** [comment]
Possibly related: https://github.com/Nazariglez/notan/issues/158

**Comment by eugenesvk** [comment]
Notan seems fine, not blurry
<img width="129" alt="notan" src="https://user-images.githubusercontent.com/12956286/205513947-730cf059-b5c7-4ef4-a55e-d917dfba5ccf.png">

**Comment by woelper** [comment]
Thanks for trying out. Now I need to find out if this works only well in the browser or if this is desktop specific...

**Comment by eugenesvk** [comment]
By the way, there is also this rust egui image editor https://github.com/Kl4rry/simp and it doesn't have blurry text, maybe it could help you find/fix the issue?

**Comment by woelper** [comment]
Thanks for mentioning simp, very interesting (and similar!) project. There was a window config example in notan showing how to enable hidpi mode. I've enabled and tested on OSX. It's in the next release. Please ler me know if you see something odd.
