### ISSUE TITLE
Rotate better UI

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#71]
Instead of the unintuitive `CCW` and `CW` and just  it should have 5 options:
`↑0° →90° ↓180° ←270° x°` (`←270°` could be named  `←−90°`), `x` is a user-defined rotation angle

**Comment by woelper** [comment]
This will be in the next release - apart from a custom angle, which is not supported yet.

**Comment by eugenesvk** [comment]
Thanks. I think the 0° is also useful as it allows comparison for just this operation (just like for crop you can reset back to 0
Also not sure the circle pie icons work rotations, especially since ◐ has a common different meaning in imaging

These might be better
```
    0°
↷  90°
↶ −90°
⤸ 180°
```

**Comment by woelper** [comment]
Ok, done (although I had to use matching arrows). I'd rather not use 0 degrees rotation, as I want to have a "bypass" flag on every operator to toggle them off and on.

**Comment by eugenesvk** [comment]
Thanks. Straight arrows are also fine, though with the circled ones you can get rid of the minus sign ;)
Universal bypass flag for each item sounds like a much better idea due to its consistency across filters

**Comment by woelper** [comment]
Yeah. Don't get me wrong, I liked your arrows better - but I am bound to the icons found at https://www.egui.rs/ (Look at "Font Book" to the right). I may be able to load another font with more or use images, but that's a bit overkill for me now.

**Comment by eugenesvk** [comment]
Oh, I see, yeah, I remember reading about egui pains like the font limitations (another web-one is you can't actually search for "font book" as it's not a text :))
Agree it's an overkill
