### ISSUE TITLE
macOS app doesn't open

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#76]
I can open your app by directly referencing the cli tool from a terminal, but double-clicking on the app itself does nothing, and its icon has this crossed circle overlay indicating that you can't launch the app

macOS 10.15

**Comment by woelper** [comment]
Was this always like this or is this a recent change? It might be that I need legacy support for Catalina.

**Comment by eugenesvk** [comment]
Since oculante 0.5.22 (not working), the previous 0.5.21 launches fine

**Comment by woelper** [comment]
This should now hopefully be fixed in `v0.6.29`. Please test as I don't have a mac with this OS around. I believe the cause was github actions updating the OS of their mac runners (I am auto-building oculante with github actions)

**Comment by eugenesvk** [comment]
Thanks, fixed!
