### ISSUE TITLE
AVIF extension not handled on macOS

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#77]
Get `[oculante::utils] ERROR: The image format Avif is not supported` in the terminal on a Mac

**Comment by woelper** [comment]
Good spot, thanks. I thought that the `image` library I am using supported this by default, which is not the case. I have to enable a feature flag which requires external libraries to be installed. I will probably have to ask @0323pin to test this in NetBSD as well ( `libdav1d-dev` )

**Comment by 0323pin** [comment]
@woelper what exactly should I test? With the latest version of `oculante` installed try to open an AVIF image file, with and without `dav1d` installed?

Or, testing a future version of `oculante` with the feature enabled? Will probably need linking at compile time to find `dav1d` shared libraries but, that's easy to do.

**Comment by woelper** [comment]
There is now avif support. For now it is gated behind `turbo`, which I will rename to something generic, like "external_libs" in the future. This is outlined in the Changelog as breaking. @0323pin you will need meson, ninja and dav1d if you want to have avif support.

**Comment by 0323pin** [comment]
@woelper Thanks for the heads-up.

**Comment by eugenesvk** [comment]
I can open avif files, thanks for fixing that! But for some reason they don't appear in the "Open With" on a Mac, maybe the app manifest needs to be updated as well to handle `.avif`?

**Comment by woelper** [comment]
Great you found that. I have declared it supports all image files generically in the plist, even raw files worked. But I guess Mac does not "yet" counts avif as images? I can be more explicit in the plist, maybe that works.

**Comment by eugenesvk** [comment]
copy&pasted the following to your apps plist, reset the database and it's working now, so you're right that you need to be more explicit, and I've checked the database, there is no AVIF as `public.image` indeed, only listed when it's registered by other apps that support it

```
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>AVIF</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>oculante.icns</string>
			<key>CFBundleTypeName</key>
			<string>AV1 Image Document</string>
			<key>CFBundleTypeRole</key>
			<string>Viewer</string>
			<key>LSHandlerRank</key>
			<string>Default</string>
		</dict>
```

**Comment by woelper** [comment]
Thanks, I'll add it like above!
