### ISSUE TITLE
Filter drop-down doesn't scroll with a touchpad on a Mac

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#78]
You have to manually drag the scroll bar

**Comment by woelper** [comment]
This is strange. On a MacBook Pro/Intel with Monterey, touchpad scrolling works in the filter drop-down. I've noticed it's slower than optimal, but more so on Linux and Windows.

**Comment by eugenesvk** [comment]
You mean the two-finger scroll that zooms on an image? Interesting if this basic behavior is os-version specific

**Comment by woelper** [comment]
Yes, two-finger scroll on touchpad works on my MacBook Pro. Really strange.
The only thing I could think of is to add debugging to a build and you start it with RUST_LOG=debug via the terminal and watch for raw events coming in when you scroll.

**Comment by eugenesvk** [comment]
Yeah, also noticed that scrolling is very slow on Windows, but at least it works ;)
Debugging could help

**Comment by woelper** [comment]
This should be fixed now by a notan update.
