### ISSUE TITLE
Edit the image shortcut doesn't work when inside the editing menu

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#80]
If the image area is focused, you can press <kbd>e</kbd> to toggle the editing menu
But if you move to the editing menu itself, then the <kbd>e</kbd> keybind stops working

**Comment by woelper** [comment]
This is intended, as the UI captures its own keystrokes. Otherwise entering text would be impossible. I can have a look if I can detect if text input is currently happening to ease this restriction.

**Comment by eugenesvk** [comment]
Yeah, limiting this limitation to text fields would be great

**Comment by woelper** [comment]
Note for self:
https://docs.rs/egui/latest/egui/struct.Context.html#method.wants_keyboard_input

**Comment by woelper** [comment]
This should be fixed in the next release. Thanks for the idea, seems much more robust now. Please tell me if there are shortcuts which don't work.
