### ISSUE TITLE
Allow rebinding all the default shortcuts and multiple shortcuts per command

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#81]
The minimalism should strive to allow skipping the bloat of a mouse! :)

Also ideally any command should be able to have a keybind, e.g. you should be able to losslessly rotate a jpeg with simple <kbd>[</kbd> and <kbd>]</kbd>

You might check how Sublime Text allows you to do it, though via text configs only (but still better than having crippled GUI), where every command has a unique name and you can simply put that name to any number of key(s) and then they also have this cool concept of "cascading" where you can toggle off default keybinds you don't like or change them by only including those you want to override, then your files gets meged with the default and this combination is used as the source for the app

**Comment by woelper** [comment]
Closing this. Please feel free to open separate issues if you want some features such as "rotate lossless right" implemented and exposed for binding.

**Comment by eugenesvk** [comment]
This could be left open to track multiple keybinds per command, will move the lossless rotation to a separate issue
