### ISSUE TITLE
Add JPEG XL support

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#82]
It's this awesome new format that has the capabilities to replace every other format ([brief overview](https://cloudinary.com/blog/the-case-for-jpeg-xl)) :), though unfortunately recently been pulled from Chrome flag support (hopefully will reconsider since other multimedia apps are just adding it, so would be great being able to view these files)

**Comment by eugenesvk** [comment]
Just FYI here is the issue tracking JPEG XL support in the image crate you app uses
https://github.com/image-rs/image/issues/1765

And then there is also another crate with bindings to the reference  C++ implementation that also has integration to the aforementioned image crate
https://github.com/inflation/jpegxl-rs

**Comment by woelper** [comment]
This is now done using the external library. It is off by default now and behind `jpgxl` feature until this builds on all platforms.
