### ISSUE TITLE
Info panel can't find its size, so "jitters" 

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#83]
Sometimes I get this effect with the info panel, seems that it can't settle of its size or something?

https://user-images.githubusercontent.com/12956286/206907714-552568e8-139e-4744-81f4-84d629060862.mov

**Comment by woelper** [comment]
There was a similar ticket already, I wonder where this comes from. Is this only on images with a small size? Can you maybe narrow down where this happens?

**Comment by eugenesvk** [comment]
> Is this only on images with a small size?

Nope, could also trigger it on a bigger picture. It's connected with resizing the left panel, on some sizes it starts to bug, on smaller/bigger sizes it works fine


https://user-images.githubusercontent.com/12956286/206973436-69926dd7-1aec-44c1-b3f1-a9da1dae3d39.mov

**Comment by eugenesvk** [comment]
Would it be possible to have an option to always hide the scrollbar? The panel isn't tall enough to make it useful
Although I've noticed that the scroll speed is too slow, but will open another issue for that

**Comment by woelper** [comment]
The slow scroll speed is a known issue in `notan`, and should be resolved soon.
I think the scrollbar causes the panel to flicker once it appears, for example if you expand submenus. This is why it's probably not good to disable it.

**Comment by eugenesvk** [comment]
But it would never appear if we disable it! I meant that I don't need it even with all the submenus expanded, the whole thing is just not tall enough


(as an aside, given how narrow modern scroolbars are, they are only an improvement in scrolling in huge documents, otherwise they're too small to precision-grab, so their only useful function is showing the position in a page, for which a simple "highlighter" element should be used instead or maybe a scrollbar should be collapsible into a 1px wide non-interactive line just to show that info)

**Comment by woelper** [comment]
I think as soon as there is EXIF info and you expand a couple of submenus the elements, the contents will become too large to fit. If there was no scrollbar, users would probably not notice that there were hidden elements. Also some people have a monitor with low resolution or prefer a small window size.

**Comment by eugenesvk** [comment]
> I think as soon as there is EXIF info and you expand a couple of submenus the elements, the contents will become too large to fit.

Yeah, sure, it is too large to fit, but it's just not too large to make the scrollbar useful! I still have touchpad/mouse wheel/key combos, which offer the same functionality (well, in oculante not the key combos) without having to precision-select a narrow UI element

>  If there was no scrollbar, users would probably not notice that there were hidden elements.

Those users should not disable scrollbar then! I'm certainly not proposing to removing the scrollbar for everyone

(and if gui framework had a proper scrollbar→positionbar element, then even those users would notice)

>   
>     Also some people have a monitor with low resolution or prefer a small window size.

I sometimes use those, and that's another reason why I prefer to have as little window space showing UI elements I don't use as possible

**Comment by woelper** [comment]
Your points make a lot of sense. I pushed another attempt, and I found that the zoomed image being too large (plus the scrollbars) was the issue. I've made the image a bit smaller and made scrollbars optional, so you should now get the best of both worlds I hope!

**Comment by eugenesvk** [comment]
How do you disable the scrollbar option? Otherwise the jitter is back now in v62 at the same resizing spot where the scrollbar is supposed to show/disappear

**Comment by woelper** [comment]
I'll re-open and try to find the root cause.

**Comment by eugenesvk** [comment]
this happens when scrollbar is partially visible, so (just a speculation) maybe the info panel is trying (in a loop) to fill the available width, but then realizes that there is a partial scrollbar, so it needs to shrink again, but then another condition ignores the partial scrollbar and expands it by a few pixels again to fit the available width?

**Comment by woelper** [comment]
I spent some intense time on it and I believe this should now be fixed for good ("never say never" :) ).

**Comment by eugenesvk** [comment]
If this is v0.6.63 then I can't seem to resize the info box horizontally at all

**Comment by woelper** [comment]
Exactly. The box now is fixed to a min size. It will auto-expand though to accommodate UI elements if they don't fit (for example if huge amounts of EXIF data is loaded). This means there won't be any reason to resize it as the contents don't scale with it, and if they become larger, the panel will grow in the horizontal direction.

**Comment by eugenesvk** [comment]
But then the helpful zooming mini-viewer can't be increased, that was the reason to resize the info panel horizontally, that's the piece of content that did scale with size

Also, if you still think it should be fixed, there should be no vertical resizing border as that's a bit confusing

**Comment by woelper** [comment]
Good points. Was it important to you to have the zoom view in a bigger size? For me it's helpful to understand the use case. Resizing the panel should just scale the texture, so I don't think you'd be seeing "more" of the image, just the same thing larger.

I don't want to bore you with details, but the zoom view scaling with the panel was a part of the issue. It would resize, and since it's square, also push things down below it. This would then in some cases cause the scrollbar to appear, which then in turn would scale the zoom view down, moving content below up, reducing the need for the scrollbar, and you had an endless cycle. Maybe I can find a workaround, but for now it's just easier to keep it in a fixed size.

**Comment by eugenesvk** [comment]
Yeah it was nice as it allowed to inspect some pixels without increasing he zoom of the whole image - and controlling the size of the zoom view makes it easier to not get lost
