### ISSUE TITLE
Expose format save options during editing

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#84]
For example, jpeg quality and subsampling etc.

**Comment by woelper** [comment]
That is a good idea. For now, I've tried to keep everything generic over all formats - this request would mean that every format has its own save options.

Maybe there is a middle ground to expose this for common formats or define options like "quality" which work across multiple formats.

**Comment by eugenesvk** [comment]
> like "quality" which work across multiple formats

I think these don't even work for a single format, e.g., for JPEGs every encoder has a different scale of the "simple" 0-100, so you can't even have a generic 80 and expect it to produce similar quality of the most common image format :(

**Comment by Stoppedpuma** [comment]
Has been implemented, not all formats have support for this but this should improve in the future.
