### ISSUE TITLE
Can't type in crop text input field

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#86]
(mentioned it in another issue, but opening a separate one so it's not lost)
I can't type any numbers in the crop input fields, can only select the numbers with the arrow keys and also delete them (you can't see the typing part on the video, but I'm typing numbers and letters, nothing gets inserted)

https://user-images.githubusercontent.com/12956286/206977800-00cd8531-bf97-4083-9a4f-53bb54a9f661.mov

**Comment by woelper** [comment]
This does work here, and I can't reproduce. Is this still an issue?

**Comment by eugenesvk** [comment]
Yes, but just figured out that this is the same issue as 3rd point here https://github.com/woelper/oculante/issues/105, modifiers were "stuck", so I couldn't type anything (that explains why the video has auto-selecting the input field)
