### ISSUE TITLE
Template-customizable title bar / status bar info

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#90]
It would be great to be able to put the title bar (and also a status bar that doesn't yet exist) to some use and use some templating language to allow user-editable image information messages like zoom %, bit depth, full path, dimensions, some EXIF fields, etc. to make the viewer really informative

(for example, XnViewMP has this great functionality, which also extends to tooltips and info overlays)

**Comment by woelper** [comment]
This is not currently possible, since the window title can't be set dynamically. Once this is exposed this could be a good idea!

**Comment by eugenesvk** [comment]
What about using this in your own "toolbar" area? With a proper borderless mode https://github.com/woelper/oculante/issues/43 the title bar will be gone anyway

**Comment by woelper** [comment]
This would of course be possible!

**Comment by woelper** [comment]
This feature has now arrived in notan. You can now format the title bar as you wish (within reason :) )

![image](https://user-images.githubusercontent.com/3613791/221407034-d91d655e-1ea1-4c3d-a633-54b119ee6a5f.png)
(will be in next release)
