### ISSUE TITLE
macOS permission issue when a single file is set to be "opened with" oculante

### ISSUE THREAD

**Issue by eugenesvk** [woelper/oculante#92]
I've discovered a strange behavior: if I set oculante as the default app for a **single file**, I get the following error that I only usually get for applications, not documents:
<img width="416" alt="id" src="https://user-images.githubusercontent.com/12956286/207244307-2afada6d-ec47-481c-ab07-d0069ea84e76.png">

However, if I set oculante as the default app for ALL the files of a given type, then opening the same file(!) doesn't show any errors
(this happens after I've already confirmed in the in Security&Privacy that it's ok to run oculante, tried `codesign --force --deep --sign -` the app, but didn't help)

**Comment by woelper** [comment]
It seems this is a duplicate of #33. This unfortunately is super hard to fix due to how OSX works and to the fact that it does not give programs to arguments passed to the app.

**Comment by eugenesvk** [comment]
Oh sorry, thought already saw that issue, but couldn't find in search

What about the second issue, is it related to the first or separate?

**Comment by woelper** [comment]
The second issue seems separate. I can't reproduce this unfortunately - I think I've right-clicked the app on first start and chose open, after that I can associate images with it

**Comment by woelper** [comment]
I suspect this has to do something with the plist file, which is more or less mac black magic. I am happy for any extra info. If you want to get your hands dirty, you can modify the app's plist yourself and see if you can find out something...

**Comment by eugenesvk** [comment]
Lol, if I change a downloaded picture (a single file) to be opened with mac's own Preview, it also fails with exactly the same warning message!!!
Only the default app (the is registered for all the files),  seems to continue to open just fine, so it's look like a weird platform bug
Also given that I don't see the point of trying to change an app handler just for a given file (I only did it for testing), not sure there is anything to do in your app

**Comment by eugenesvk** [comment]
Meanwhile i've found the explanation of the broken design why setting a launch app for a single file fails, while setting the same app for all the files suceeds
https://apple.stackexchange.com/questions/251205/why-is-osx-telling-me-i-cant-open-a-document-from-an-unidentified-developer

> if you set a document to open in a particular app, what it actually does is attach some metadata to the file
> "Change all" ... removes the metadata from the file, and instead makes an entry in your Launch Services preferences saying that you prefer to have files of that type open in that app. Since the setting is now a personal setting rather than a note attached to an untrusted file, the problem goes away.
